import abc
import asyncio
import zmq
import zmq.asyncio
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from collections.abc import Callable as Callable, Sequence
from dataclasses import dataclass
from typing import Any, TypeAlias
from vllm.config import VllmConfig as VllmConfig
from vllm.envs import VLLM_ENGINE_READY_TIMEOUT_S as VLLM_ENGINE_READY_TIMEOUT_S
from vllm.logger import init_logger as init_logger
from vllm.lora.request import LoRARequest as LoRARequest
from vllm.tasks import SupportedTask as SupportedTask
from vllm.tracing import instrument as instrument
from vllm.utils.async_utils import in_loop as in_loop
from vllm.utils.network_utils import (
    close_sockets as close_sockets,
    get_open_zmq_inproc_path as get_open_zmq_inproc_path,
    make_zmq_socket as make_zmq_socket,
)
from vllm.v1.engine import (
    EEPNotificationType as EEPNotificationType,
    EEP_NOTIFICATION_CALL_ID as EEP_NOTIFICATION_CALL_ID,
    EngineCoreOutputs as EngineCoreOutputs,
    EngineCoreRequest as EngineCoreRequest,
    EngineCoreRequestType as EngineCoreRequestType,
    PauseMode as PauseMode,
    ReconfigureDistributedRequest as ReconfigureDistributedRequest,
    ReconfigureRankType as ReconfigureRankType,
    UtilityOutput as UtilityOutput,
)
from vllm.v1.engine.coordinator import DPCoordinator as DPCoordinator
from vllm.v1.engine.core import (
    EngineCore as EngineCore,
    EngineCoreProc as EngineCoreProc,
)
from vllm.v1.engine.exceptions import EngineDeadError as EngineDeadError
from vllm.v1.engine.utils import (
    CoreEngineActorManager as CoreEngineActorManager,
    CoreEngineProcManager as CoreEngineProcManager,
    get_engine_zmq_addresses as get_engine_zmq_addresses,
    launch_core_engines as launch_core_engines,
)
from vllm.v1.executor import Executor as Executor
from vllm.v1.pool.late_interaction import (
    get_late_interaction_engine_index as get_late_interaction_engine_index,
)
from vllm.v1.serial_utils import (
    MsgpackDecoder as MsgpackDecoder,
    MsgpackEncoder as MsgpackEncoder,
    bytestr as bytestr,
)

logger: Incomplete
AnyFuture: TypeAlias
EngineIdentity = bytes

class EngineCoreClient(ABC, metaclass=abc.ABCMeta):
    @staticmethod
    def make_client(
        multiprocess_mode: bool,
        asyncio_mode: bool,
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
    ) -> EngineCoreClient: ...
    @staticmethod
    def make_async_mp_client(
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
        client_addresses: dict[str, str] | None = None,
        client_count: int = 1,
        client_index: int = 0,
    ) -> AsyncMPClient: ...
    @abstractmethod
    def shutdown(self): ...
    def get_output(self) -> EngineCoreOutputs: ...
    def get_supported_tasks(self) -> tuple[SupportedTask, ...]: ...
    def add_request(self, request: EngineCoreRequest) -> None: ...
    def profile(
        self, is_start: bool = True, profile_prefix: str | None = None
    ) -> None: ...
    def reset_mm_cache(self) -> None: ...
    def reset_prefix_cache(
        self, reset_running_requests: bool = False, reset_connector: bool = False
    ) -> bool: ...
    def reset_encoder_cache(self) -> None: ...
    def sleep(self, level: int = 1, mode: PauseMode = "abort") -> None: ...
    def wake_up(self, tags: list[str] | None = None) -> None: ...
    def is_sleeping(self) -> bool: ...
    def execute_dummy_batch(self) -> None: ...
    async def execute_dummy_batch_async(self) -> None: ...
    def abort_requests(self, request_ids: list[str]) -> None: ...
    def add_lora(self, lora_request: LoRARequest) -> bool: ...
    def remove_lora(self, lora_id: int) -> bool: ...
    def list_loras(self) -> set[int]: ...
    def pin_lora(self, lora_id: int) -> bool: ...
    def save_sharded_state(
        self, path: str, pattern: str | None = None, max_size: int | None = None
    ) -> None: ...
    def collective_rpc(
        self,
        method: str | Callable[..., _R],
        timeout: float | None = None,
        args: tuple = (),
        kwargs: dict[str, Any] | None = None,
    ) -> list[_R]: ...
    def dp_engines_running(self) -> bool: ...
    async def scale_elastic_ep(self, new_data_parallel_size: int) -> None: ...
    async def get_output_async(self) -> EngineCoreOutputs: ...
    async def get_supported_tasks_async(self) -> tuple[SupportedTask, ...]: ...
    async def add_request_async(self, request: EngineCoreRequest) -> None: ...
    async def profile_async(
        self, is_start: bool = True, profile_prefix: str | None = None
    ) -> None: ...
    async def reset_mm_cache_async(self) -> None: ...
    async def reset_prefix_cache_async(
        self, reset_running_requests: bool = False, reset_connector: bool = False
    ) -> bool: ...
    async def reset_encoder_cache_async(self) -> None: ...
    async def sleep_async(self, level: int = 1, mode: PauseMode = "abort") -> None: ...
    async def wake_up_async(self, tags: list[str] | None = None) -> None: ...
    async def is_sleeping_async(self) -> bool: ...
    async def abort_requests_async(self, request_ids: list[str]) -> None: ...
    async def add_lora_async(self, lora_request: LoRARequest) -> bool: ...
    async def remove_lora_async(self, lora_id: int) -> bool: ...
    async def list_loras_async(self) -> set[int]: ...
    async def pin_lora_async(self, lora_id: int) -> bool: ...
    async def save_sharded_state_async(
        self, path: str, pattern: str | None = None, max_size: int | None = None
    ) -> None: ...
    async def collective_rpc_async(
        self,
        method: str | Callable[..., _R],
        timeout: float | None = None,
        args: tuple = (),
        kwargs: dict[str, Any] | None = None,
    ) -> list[_R]: ...

class InprocClient(EngineCoreClient):
    engine_core: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_output(self) -> EngineCoreOutputs: ...
    def get_supported_tasks(self) -> tuple[SupportedTask, ...]: ...
    def add_request(self, request: EngineCoreRequest) -> None: ...
    def abort_requests(self, request_ids: list[str]) -> None: ...
    def shutdown(self) -> None: ...
    def profile(
        self, is_start: bool = True, profile_prefix: str | None = None
    ) -> None: ...
    def reset_mm_cache(self) -> None: ...
    def reset_prefix_cache(
        self, reset_running_requests: bool = False, reset_connector: bool = False
    ) -> bool: ...
    def reset_encoder_cache(self) -> None: ...
    def sleep(self, level: int = 1, mode: PauseMode = "abort") -> None: ...
    def wake_up(self, tags: list[str] | None = None) -> None: ...
    def is_sleeping(self) -> bool: ...
    def execute_dummy_batch(self) -> None: ...
    def add_lora(self, lora_request: LoRARequest) -> bool: ...
    def remove_lora(self, lora_id: int) -> bool: ...
    def list_loras(self) -> set[int]: ...
    def pin_lora(self, lora_id: int) -> bool: ...
    def save_sharded_state(
        self, path: str, pattern: str | None = None, max_size: int | None = None
    ) -> None: ...
    def collective_rpc(
        self,
        method: str | Callable[..., _R],
        timeout: float | None = None,
        args: tuple = (),
        kwargs: dict[str, Any] | None = None,
    ) -> list[_R]: ...
    def dp_engines_running(self) -> bool: ...

@dataclass
class BackgroundResources:
    ctx: zmq.Context
    engine_manager: CoreEngineProcManager | CoreEngineActorManager | None = ...
    coordinator: DPCoordinator | None = ...
    output_socket: zmq.Socket | zmq.asyncio.Socket | None = ...
    input_socket: zmq.Socket | zmq.asyncio.Socket | None = ...
    first_req_send_socket: zmq.asyncio.Socket | None = ...
    first_req_rcv_socket: zmq.asyncio.Socket | None = ...
    stats_update_socket: zmq.asyncio.Socket | None = ...
    output_queue_task: asyncio.Task | None = ...
    stats_update_task: asyncio.Task | None = ...
    shutdown_path: str | None = ...
    engine_dead: bool = ...
    def __call__(self) -> None: ...
    def validate_alive(self, frames: Sequence[zmq.Frame]): ...

@dataclass
class ElasticScalingCache:
    existing_core_engines: list[EngineIdentity]
    num_new_core_engines: int
    pending_notifications: dict[EEPNotificationType, set[int]]

def allocate_stateless_group_ports(parallel_config, new_data_parallel_size: int): ...

class MPClient(EngineCoreClient):
    vllm_config: Incomplete
    encoder: Incomplete
    decoder: Incomplete
    ctx: Incomplete
    resources: Incomplete
    engines_running: bool
    stats_update_address: str | None
    input_socket: Incomplete
    engine_ranks_managed: Incomplete
    core_engines: list[EngineIdentity]
    core_engine: EngineIdentity
    utility_results: dict[int, AnyFuture]
    pending_messages: Incomplete
    def __init__(
        self,
        asyncio_mode: bool,
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
        client_addresses: dict[str, str] | None = None,
    ) -> None: ...
    def shutdown(self) -> None: ...
    def ensure_alive(self) -> None: ...
    def add_pending_message(self, tracker: zmq.MessageTracker, msg: Any): ...
    def free_pending_messages(self) -> None: ...
    def dp_engines_running(self) -> bool: ...
    def start_engine_core_monitor(self) -> None: ...

class SyncMPClient(MPClient):
    is_dp: Incomplete
    outputs_queue: Incomplete
    output_queue_thread: Incomplete
    def __init__(
        self, vllm_config: VllmConfig, executor_class: type[Executor], log_stats: bool
    ) -> None: ...
    engines_running: bool
    def get_output(self) -> EngineCoreOutputs: ...
    def call_utility(self, method: str, *args) -> Any: ...
    def get_supported_tasks(self) -> tuple[SupportedTask, ...]: ...
    def add_request(self, request: EngineCoreRequest) -> None: ...
    def abort_requests(self, request_ids: list[str]) -> None: ...
    def profile(
        self, is_start: bool = True, profile_prefix: str | None = None
    ) -> None: ...
    def reset_mm_cache(self) -> None: ...
    def reset_prefix_cache(
        self, reset_running_requests: bool = False, reset_connector: bool = False
    ) -> bool: ...
    def reset_encoder_cache(self) -> None: ...
    def add_lora(self, lora_request: LoRARequest) -> bool: ...
    def remove_lora(self, lora_id: int) -> bool: ...
    def list_loras(self) -> set[int]: ...
    def pin_lora(self, lora_id: int) -> bool: ...
    def sleep(self, level: int = 1, mode: PauseMode = "abort") -> None: ...
    def wake_up(self, tags: list[str] | None = None) -> None: ...
    def is_sleeping(self) -> bool: ...
    def execute_dummy_batch(self) -> None: ...
    def collective_rpc(
        self,
        method: str | Callable[..., _R],
        timeout: float | None = None,
        args: tuple = (),
        kwargs: dict[str, Any] | None = None,
    ) -> list[_R]: ...
    def save_sharded_state(
        self, path: str, pattern: str | None = None, max_size: int | None = None
    ) -> None: ...

class AsyncMPClient(MPClient):
    client_count: Incomplete
    client_index: Incomplete
    outputs_queue: Incomplete
    def __init__(
        self,
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
        client_addresses: dict[str, str] | None = None,
        client_count: int = 1,
        client_index: int = 0,
    ) -> None: ...
    async def get_output_async(self) -> EngineCoreOutputs: ...
    async def call_utility_async(self, method: str, *args) -> Any: ...
    async def get_supported_tasks_async(self) -> tuple[SupportedTask, ...]: ...
    async def add_request_async(self, request: EngineCoreRequest) -> None: ...
    async def abort_requests_async(self, request_ids: list[str]) -> None: ...
    async def pause_scheduler_async(
        self, mode: PauseMode = "abort", clear_cache: bool = True
    ) -> None: ...
    async def resume_scheduler_async(self) -> None: ...
    async def is_scheduler_paused_async(self) -> bool: ...
    async def profile_async(
        self, is_start: bool = True, profile_prefix: str | None = None
    ) -> None: ...
    async def reset_mm_cache_async(self) -> None: ...
    async def reset_prefix_cache_async(
        self, reset_running_requests: bool = False, reset_connector: bool = False
    ) -> bool: ...
    async def reset_encoder_cache_async(self) -> None: ...
    async def sleep_async(self, level: int = 1, mode: PauseMode = "abort") -> None: ...
    async def wake_up_async(self, tags: list[str] | None = None) -> None: ...
    async def is_sleeping_async(self) -> bool: ...
    async def execute_dummy_batch_async(self) -> None: ...
    async def add_lora_async(self, lora_request: LoRARequest) -> bool: ...
    async def remove_lora_async(self, lora_id: int) -> bool: ...
    async def list_loras_async(self) -> set[int]: ...
    async def pin_lora_async(self, lora_id: int) -> bool: ...
    async def save_sharded_state_async(
        self, path: str, pattern: str | None = None, max_size: int | None = None
    ) -> None: ...
    async def collective_rpc_async(
        self,
        method: str | Callable[..., _R],
        timeout: float | None = None,
        args: tuple = (),
        kwargs: dict[str, Any] | None = None,
    ) -> list[_R]: ...

class DPAsyncMPClient(AsyncMPClient):
    current_wave: int
    lb_engines: list[list[int]]
    eep_scaling_cache: ElasticScalingCache | None
    first_req_sock_addr: Incomplete
    first_req_send_socket: Incomplete
    def __init__(
        self,
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
        client_addresses: dict[str, str] | None = None,
        client_count: int = 1,
        client_index: int = 0,
    ) -> None: ...
    async def add_request_async(self, request: EngineCoreRequest) -> None: ...
    def get_core_engine_for_request(self, request: EngineCoreRequest): ...

class DPLBAsyncMPClient(DPAsyncMPClient):
    client_count: Incomplete
    reqs_in_flight: dict[str, EngineIdentity]
    eng_start_index: Incomplete
    def __init__(
        self,
        vllm_config: VllmConfig,
        executor_class: type[Executor],
        log_stats: bool,
        client_addresses: dict[str, str] | None = None,
        client_count: int = 1,
        client_index: int = 0,
    ) -> None: ...
    def get_core_engine_for_request(
        self, request: EngineCoreRequest
    ) -> EngineIdentity: ...
    async def call_utility_async(self, method: str, *args) -> Any: ...
    @staticmethod
    async def process_engine_outputs(self, outputs: EngineCoreOutputs): ...
    eep_scaling_cache: Incomplete
    @staticmethod
    async def eep_process_engine_core_notification(
        self, notification_data: tuple[str, int]
    ): ...
    async def abort_requests_async(self, request_ids: list[str]) -> None: ...
    async def scale_elastic_ep(self, new_data_parallel_size: int) -> None: ...
