"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class JointAttentionConcept(nn.Module):
    def __init__(self) -> None: ...
    def __call__(
        self,
        hidden_states: mx.array,
        encoder_hidden_states: mx.array,
        encoder_hidden_states_concept: mx.array,
        image_rotary_emb: mx.array,
        image_rotary_emb_concept: mx.array,
    ) -> tuple[mx.array, mx.array, mx.array, mx.array, mx.array]: ...
