import abc
import torch
from abc import ABC, abstractmethod
from torch import nn as nn
from typing import Any
from vllm.model_executor.layers.quantization import (
    QuantizationMethods as QuantizationMethods,
)
from vllm.model_executor.models.utils import WeightsMapper as WeightsMapper

class QuantizeMethodBase(ABC, metaclass=abc.ABCMeta):
    uses_meta_device: bool
    @abstractmethod
    def create_weights(
        self, layer: torch.nn.Module, *weight_args, **extra_weight_attrs
    ): ...
    @abstractmethod
    def apply(self, layer: torch.nn.Module, *args, **kwargs) -> torch.Tensor: ...
    def embedding(self, layer: torch.nn.Module, *args, **kwargs) -> torch.Tensor: ...
    def process_weights_after_loading(self, layer: nn.Module) -> None: ...

def method_has_implemented_embedding(
    method_class: type[QuantizeMethodBase],
) -> bool: ...

class QuantizationConfig(ABC, metaclass=abc.ABCMeta):
    packed_modules_mapping: dict[str, list[str]]
    def __init__(self) -> None: ...
    @abstractmethod
    def get_name(self) -> QuantizationMethods: ...
    @abstractmethod
    def get_supported_act_dtypes(self) -> list[torch.dtype]: ...
    @classmethod
    @abstractmethod
    def get_min_capability(cls) -> int: ...
    @staticmethod
    @abstractmethod
    def get_config_filenames() -> list[str]: ...
    @classmethod
    @abstractmethod
    def from_config(cls, config: dict[str, Any]) -> QuantizationConfig: ...
    @classmethod
    def override_quantization_method(
        cls, hf_quant_cfg, user_quant
    ) -> QuantizationMethods | None: ...
    @staticmethod
    def get_from_keys(config: dict[str, Any], keys: list[str]) -> Any: ...
    @staticmethod
    def get_from_keys_or(
        config: dict[str, Any], keys: list[str], default: Any
    ) -> Any: ...
    @abstractmethod
    def get_quant_method(
        self, layer: torch.nn.Module, prefix: str
    ) -> QuantizeMethodBase | None: ...
    def get_cache_scale(self, name: str) -> str | None: ...
    def apply_vllm_mapper(self, hf_to_vllm_mapper: WeightsMapper): ...
    def maybe_update_config(self, model_name: str): ...
    def is_mxfp4_quant(self, prefix: str, layer: torch.nn.Module) -> bool: ...
