"""
This type stub file was generated by pyright.
"""

from mflux.models.common.weights.mapping.weight_mapping import (
    WeightMapping,
    WeightTarget,
)

class ZImageWeightMapping(WeightMapping):
    @staticmethod
    def get_text_encoder_mapping() -> list[WeightTarget]: ...
    @staticmethod
    def get_vae_mapping() -> list[WeightTarget]: ...
    @staticmethod
    def get_transformer_mapping() -> list[WeightTarget]: ...
