"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn

class FOVHead(nn.Module):
    def __init__(self) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
