# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import typing

@typing.final
class NetReceiver: ...

@typing.final
class NetSender: ...

@typing.final
class PySession:
    @staticmethod
    def init() -> collections.abc.Awaitable[PySession]: ...
    def net_receiver(self, key: builtins.str) -> NetReceiver: ...
    def net_sender(self, key: builtins.str) -> NetSender: ...
    def state_proxy(self) -> StateProxy: ...

@typing.final
class StateProxy:
    def snapshot(self) -> collections.abc.Awaitable[str]: ...
