# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing

__all__ = [
    "NetReceiver",
    "NetSender",
    "NetworkingHandle",
    "PyFromSwarm",
    "PySession",
    "StateProxy",
]

@typing.final
class NetReceiver:
    def recv(self) -> collections.abc.Awaitable[bytes | None]: ...

@typing.final
class NetSender:
    def send(self, data: bytes) -> collections.abc.Awaitable[bool]: ...

@typing.final
class NetworkingHandle:
    @staticmethod
    def new(identity: bytes, bootstrap_peers: typing.Sequence[builtins.str], listen_port: builtins.int) -> tuple[NetworkingHandle, PySession]: ...
    async def gossipsub_subscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Subscribe to a `GossipSub` topic.
        
        Returns `True` if the subscription worked. Returns `False` if we were already subscribed.
        """
    async def gossipsub_unsubscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Unsubscribes from a `GossipSub` topic.
        
        Returns `True` if we were subscribed to this topic. Returns `False` if we were not subscribed.
        """
    async def gossipsub_publish(self, topic: builtins.str, data: bytes) -> None:
        r"""
        Publishes a message with multiple topics to the `GossipSub` network.
        
        If no peers are found that subscribe to this topic, throws `NoPeersSubscribedToTopicError` exception.
        """
    async def recv(self) -> PyFromSwarm: ...

class PyFromSwarm:
    @typing.final
    class Connection(PyFromSwarm):
        __match_args__ = ("connected",)
        @property
        def connected(self) -> builtins.bool: ...
        def __new__(cls, connected: builtins.bool) -> PyFromSwarm.Connection: ...
    
    @typing.final
    class Message(PyFromSwarm):
        __match_args__ = ("topic", "data",)
        @property
        def topic(self) -> builtins.str: ...
        @property
        def data(self) -> bytes: ...
        def __new__(cls, topic: builtins.str, data: bytes) -> PyFromSwarm.Message: ...
    

@typing.final
class PySession:
    def net_receiver(self, key: builtins.str) -> NetReceiver: ...
    def net_sender(self, key: builtins.str) -> NetSender: ...
    def state_proxy(self) -> StateProxy: ...

@typing.final
class StateProxy:
    def snapshot(self) -> collections.abc.Awaitable[str]: ...

