model_id = "mlx-community/Llama-3.1-Nemotron-Nano-4B-v1.1-bf16"
n_layers = 32
hidden_size = 3072
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "bf16"
base_model = "NVIDIA Llama-3.1-Nemotron-Nano-4B-v1.1"
capabilities = ["text"]

context_length = 131072

[storage_size]
in_bytes = 9025492992

# Source: https://huggingface.co/nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1
[sampling_defaults]
temperature = 0.6
top_p = 0.95

# Source: https://huggingface.co/nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1
[sampling_defaults.non_thinking]
temperature = 0.0
