model_id = "mlx-community/Llama-4-Scout-17B-16E-Instruct-8bit"
n_layers = 48
hidden_size = 5120
num_key_value_heads = 8
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "8bit"
base_model = "Llama 4 Scout"
capabilities = ["text"]

[storage_size]
in_bytes = 115434854619
