model_id = "unsloth/GLM-4.7-Flash-GGUF"
n_layers = 47
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
family = "glm"
quantization = "GGUF"
base_model = "GLM 4.7 Flash"
capabilities = ["text", "thinking", "thinking_toggle"]

[storage_size]
in_bytes = 35624923488
