model_id = "unsloth/Qwen3-Coder-Next-GGUF"
n_layers = 48
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
family = "qwen"
quantization = "GGUF"
base_model = "Qwen3 Coder Next"
capabilities = ["text", "code"]

[storage_size]
in_bytes = 157548627945
