"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from typing import TYPE_CHECKING
from mflux.models.common.config.config import Config
from mflux.models.common.schedulers.base_scheduler import BaseScheduler

if TYPE_CHECKING:
    ...
class FlowMatchEulerDiscreteScheduler(BaseScheduler):
    def __init__(self, config: Config) -> None:
        ...
    
    @property
    def sigmas(self) -> mx.array:
        ...
    
    @property
    def timesteps(self) -> mx.array:
        ...
    
    def set_image_seq_len(self, image_seq_len: int) -> None:
        ...
    
    @staticmethod
    def get_timesteps_and_sigmas(image_seq_len: int, num_inference_steps: int, num_train_timesteps: int = ...) -> tuple[mx.array, mx.array]:
        ...
    
    def step(self, noise: mx.array, timestep: int, latents: mx.array, **kwargs) -> mx.array:
        ...
    
    def scale_model_input(self, latents: mx.array, t: int) -> mx.array:
        ...
    


