"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from typing import TYPE_CHECKING
from mflux.models.common.config.config import Config
from mflux.models.common.schedulers.base_scheduler import BaseScheduler

if TYPE_CHECKING:
    ...
class SeedVR2EulerScheduler(BaseScheduler):
    def __init__(self, config: Config) -> None:
        ...
    
    @property
    def timesteps(self) -> mx.array:
        ...
    
    @property
    def sigmas(self) -> mx.array:
        ...
    
    def step(self, noise: mx.array, timestep: int, latents: mx.array, **kwargs) -> mx.array:
        ...
    


