import torch
import torch.nn as nn
from _typeshed import Incomplete
from vllm.distributed import (
    divide as divide,
    get_tensor_model_parallel_rank as get_tensor_model_parallel_rank,
    get_tensor_model_parallel_world_size as get_tensor_model_parallel_world_size,
)
from vllm.logger import init_logger as init_logger
from vllm.model_executor.custom_op import CustomOp as CustomOp
from vllm.model_executor.utils import set_weight_attrs as set_weight_attrs
from vllm.platforms import current_platform as current_platform
from vllm.triton_utils import tl as tl, triton as triton
from vllm.utils.collection_utils import LazyDict as LazyDict

logger: Incomplete

def swiglustep_and_mul_triton(
    output: torch.Tensor, input: torch.Tensor, limit: float = 7.0
): ...

class FatreluAndMul(CustomOp):
    threshold: Incomplete
    op: Incomplete
    def __init__(self, threshold: float = 0.0) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...

class SiluAndMul(CustomOp):
    op: Incomplete
    def __init__(self, *, compile_native: bool = True) -> None: ...
    @staticmethod
    def forward_native(x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...

class MulAndSilu(CustomOp):
    op: Incomplete
    def __init__(self) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...

class GeluAndMulSparse(CustomOp):
    approximate: Incomplete
    std_multiplier: Incomplete
    def __init__(
        self, activation_sparsity: float, approximate: str = "none"
    ) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...

class GeluAndMul(CustomOp):
    approximate: Incomplete
    op: Incomplete
    def __init__(self, approximate: str = "none") -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class SwigluOAIAndMul(CustomOp):
    alpha: Incomplete
    limit: Incomplete
    def __init__(self, alpha: float = 1.702, limit: float = 7.0) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class SwigluStepAndMul(CustomOp):
    limit: Incomplete
    def __init__(self, limit: float = 7.0) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class NewGELU(CustomOp):
    op: Incomplete
    def __init__(self) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...

class FastGELU(CustomOp):
    op: Incomplete
    def __init__(self) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...

class QuickGELU(CustomOp):
    op: Incomplete
    def __init__(self) -> None: ...
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_xpu(self, x: torch.Tensor) -> torch.Tensor: ...

class ReLUSquaredActivation(CustomOp):
    def forward_native(self, x: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, x: torch.Tensor) -> torch.Tensor: ...

class XIELU(CustomOp):
    alpha_p: Incomplete
    alpha_n: Incomplete
    with_vector_loads: Incomplete
    def __init__(
        self,
        alpha_p_init: float = 0.8,
        alpha_n_init: float = 0.8,
        beta: float = 0.5,
        eps: float = -1e-06,
        dtype: torch.dtype = ...,
        with_vector_loads: bool = False,
    ) -> None: ...
    def forward_native(self, input: torch.Tensor) -> torch.Tensor: ...
    def forward_cuda(self, input: torch.Tensor) -> torch.Tensor: ...

class ScaledActivation(nn.Module):
    act: Incomplete
    input_is_parallel: Incomplete
    scales: Incomplete
    def __init__(
        self,
        act_module: nn.Module,
        intermediate_size: int,
        input_is_parallel: bool = True,
        params_dtype: torch.dtype | None = None,
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    def weight_loader(self, param: nn.Parameter, loaded_weight: torch.Tensor): ...

def get_act_fn(act_fn_name: str) -> nn.Module: ...
def get_act_and_mul_fn(act_fn_name: str) -> nn.Module: ...
