from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Any
from vllm.entrypoints.chat_utils import (
    ChatTemplateContentFormatOption as ChatTemplateContentFormatOption,
)
from vllm.exceptions import VLLMValidationError as VLLMValidationError
from vllm.inputs import (
    EmbedsPrompt as EmbedsPrompt,
    TextPrompt as TextPrompt,
    TokensPrompt as TokensPrompt,
)
from vllm.logger import init_logger as init_logger
from vllm.multimodal.media.connector import (
    merge_media_io_kwargs as merge_media_io_kwargs,
)
from vllm.tokenizers import TokenizerLike as TokenizerLike
from vllm.utils.import_utils import LazyLoader as LazyLoader

logger: Incomplete

def merge_kwargs(
    defaults: dict[str, Any] | None,
    overrides: dict[str, Any] | None,
    /,
    *,
    unset_values: tuple[object, ...] = (None, "auto"),
) -> dict[str, Any]: ...
def recursively_merge_kwargs(
    defaults: dict[str, Any] | None,
    overrides: dict[str, Any] | None,
    /,
    *,
    unset_values: tuple[object, ...] = (None, "auto"),
) -> dict[str, Any]: ...
@dataclass(frozen=True)
class ChatParams:
    chat_template: str | None = ...
    chat_template_content_format: ChatTemplateContentFormatOption = ...
    chat_template_kwargs: dict[str, Any] = field(default_factory=dict)
    media_io_kwargs: dict[str, dict[str, Any]] | None = ...
    mm_processor_kwargs: dict[str, Any] | None = ...
    def with_defaults(
        self,
        default_chat_template_kwargs: dict[str, Any] | None = None,
        default_media_io_kwargs: dict[str, dict[str, Any]] | None = None,
        default_mm_processor_kwargs: dict[str, Any] | None = None,
    ): ...
    def get_apply_chat_template_kwargs(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class TokenizeParams:
    max_total_tokens: int | None
    max_output_tokens: int = ...
    pad_prompt_tokens: int | None = ...
    truncate_prompt_tokens: int | None = ...
    do_lower_case: bool = ...
    add_special_tokens: bool = ...
    needs_detokenization: bool = ...
    max_total_tokens_param: str = ...
    max_output_tokens_param: str = ...
    truncate_prompt_tokens_param: str = ...
    @property
    def max_input_tokens(self) -> int | None: ...
    def __post_init__(self) -> None: ...
    def with_kwargs(self, **tokenization_kwargs: Any): ...
    def get_encode_kwargs(self) -> dict[str, Any]: ...
    def apply_pre_tokenization(
        self, tokenizer: TokenizerLike | None, prompt: TextPrompt
    ) -> TextPrompt: ...
    def apply_post_tokenization(
        self, tokenizer: TokenizerLike | None, prompt: TokensPrompt | EmbedsPrompt
    ) -> TokensPrompt | EmbedsPrompt: ...
