"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class SingleBlockAttention(nn.Module):
    num_heads: int
    head_dimension: int
    to_q: nn.Linear
    to_k: nn.Linear
    to_v: nn.Linear
    norm_q: nn.RMSNorm
    norm_k: nn.RMSNorm

    def __init__(self) -> None: ...
    def __call__(
        self, hidden_states: mx.array, image_rotary_emb: mx.array
    ) -> mx.array: ...
