"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class SiglipVisionEmbeddings(nn.Module):
    embed_dim = ...
    image_size = ...
    patch_size = ...
    def __init__(self) -> None:
        ...
    
    def __call__(self, pixel_values: mx.array) -> mx.array:
        ...
    


