"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class SiglipVisionTransformer(nn.Module):
    def __init__(self) -> None: ...
    def __call__(self, pixel_values: mx.array) -> mx.array: ...
