"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn

class DepthProUtil:
    @staticmethod
    def split(x: mx.array, overlap_ratio: float = ...) -> mx.array:
        ...
    
    @staticmethod
    def interpolate(x: mx.array, size=..., scale_factor=...): # -> array:
        ...
    
    @staticmethod
    def apply_conv(x: mx.array, conv_module: nn.Module) -> mx.array:
        ...
    


