"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from dataclasses import dataclass
from pathlib import Path
from PIL import Image

@dataclass
class DepthResult:
    depth_image: Image.Image
    depth_array: mx.array
    min_depth: float
    max_depth: float
    ...


class DepthPro:
    def __init__(self, quantize: int | None = ...) -> None:
        ...
    
    def create_depth_map(self, image_path: str | Path) -> DepthResult:
        ...
    


