from typing import Any, Literal
from vllm.config.utils import config as config
from vllm.v1.attention.backends.registry import (
    AttentionBackendEnum as AttentionBackendEnum,
)

@config
class AttentionConfig:
    backend: AttentionBackendEnum | None = ...
    flash_attn_version: Literal[2, 3, 4] | None = ...
    use_prefill_decode_attention: bool = ...
    flash_attn_max_num_splits_for_cuda_graph: int = ...
    use_cudnn_prefill: bool = ...
    use_trtllm_ragged_deepseek_prefill: bool = ...
    use_trtllm_attention: bool | None = ...
    disable_flashinfer_prefill: bool = ...
    disable_flashinfer_q_quantization: bool = ...
    use_prefill_query_quantization: bool = ...
    def compute_hash(self) -> str: ...
    @classmethod
    def validate_backend_before(cls, value: Any) -> Any: ...
