from _typeshed import Incomplete
from pydantic import SkipValidation as SkipValidation
from typing import ClassVar
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger

logger: Incomplete
CacheDType: Incomplete
MambaDType: Incomplete
MambaCacheMode: Incomplete
PrefixCachingHashAlgo: Incomplete
KVOffloadingBackend: Incomplete

@config
class CacheConfig:
    DEFAULT_BLOCK_SIZE: ClassVar[int] = ...
    block_size: SkipValidation[int] = ...
    user_specified_block_size: bool = ...
    gpu_memory_utilization: float = ...
    cache_dtype: CacheDType = ...
    is_attention_free: bool = ...
    num_gpu_blocks_override: int | None = ...
    sliding_window: int | None = ...
    enable_prefix_caching: bool = ...
    prefix_caching_hash_algo: PrefixCachingHashAlgo = ...
    calculate_kv_scales: bool = ...
    cpu_kvcache_space_bytes: int | None = ...
    mamba_page_size_padded: int | None = ...
    mamba_block_size: int | None = ...
    mamba_cache_dtype: MambaDType = ...
    mamba_ssm_cache_dtype: MambaDType = ...
    mamba_cache_mode: MambaCacheMode = ...
    num_gpu_blocks: int | None = ...
    num_cpu_blocks: int | None = ...
    kv_sharing_fast_prefill: bool = ...
    kv_cache_memory_bytes: int | None = ...
    kv_offloading_size: float | None = ...
    kv_offloading_backend: KVOffloadingBackend = ...
    def compute_hash(self) -> str: ...
    def metrics_info(self): ...
