import enum
from _typeshed import Incomplete
from collections import Counter
from collections.abc import Callable as Callable
from pathlib import Path
from typing import Any, Literal
from vllm.compilation.passes.inductor_pass import (
    CallableInductorPass as CallableInductorPass,
    InductorPass as InductorPass,
)
from vllm.config import VllmConfig as VllmConfig
from vllm.config.utils import (
    Range as Range,
    config as config,
    get_hash_factors as get_hash_factors,
    hash_factors as hash_factors,
)
from vllm.logger import init_logger as init_logger
from vllm.platforms import current_platform as current_platform
from vllm.utils.import_utils import resolve_obj_by_qualname as resolve_obj_by_qualname
from vllm.utils.math_utils import round_up as round_up
from vllm.utils.torch_utils import is_torch_equal_or_newer as is_torch_equal_or_newer

logger: Incomplete

class CompilationMode(enum.IntEnum):
    NONE = 0
    STOCK_TORCH_COMPILE = 1
    DYNAMO_TRACE_ONCE = 2
    VLLM_COMPILE = 3

class CUDAGraphMode(enum.Enum):
    NONE = 0
    PIECEWISE = 1
    FULL = 2
    FULL_DECODE_ONLY = ...
    FULL_AND_PIECEWISE = ...
    def decode_mode(self) -> CUDAGraphMode: ...
    def mixed_mode(self) -> CUDAGraphMode: ...
    def has_mode(self, mode: CUDAGraphMode) -> bool: ...
    def requires_piecewise_compilation(self) -> bool: ...
    def max_cudagraph_mode(self) -> CUDAGraphMode: ...
    def has_full_cudagraphs(self) -> bool: ...
    def has_piecewise_cudagraphs(self) -> bool: ...
    def separate_routine(self) -> bool: ...
    @classmethod
    def valid_runtime_modes(cls) -> frozenset["CUDAGraphMode"]: ...
    def is_valid_runtime_mode(self) -> bool: ...
    def __bool__(self) -> bool: ...

@config
class PassConfig:
    fuse_norm_quant: bool = ...
    fuse_act_quant: bool = ...
    fuse_attn_quant: bool = ...
    eliminate_noops: bool = ...
    enable_sp: bool = ...
    fuse_gemm_comms: bool = ...
    fuse_allreduce_rms: bool = ...
    enable_qk_norm_rope_fusion: bool = ...
    fuse_act_padding: bool = ...
    fuse_rope_kvcache: bool = ...
    rope_kvcache_fusion_max_token_num: int = ...
    fi_allreduce_fusion_max_size_mb: float | None = ...
    sp_min_token_num: int | None = ...
    def flashinfer_max_size(self, world_size: int) -> int | None: ...
    @staticmethod
    def default_fi_allreduce_fusion_max_size_mb() -> dict[int, float]: ...
    def compute_hash(self) -> str: ...
    def __post_init__(self) -> None: ...
    def log_enabled_passes(self) -> None: ...

class DynamicShapesType(str, enum.Enum):
    BACKED = "backed"
    UNBACKED = "unbacked"
    BACKED_SIZE_OBLIVIOUS = "backed_size_oblivious"

@config
class DynamicShapesConfig:
    type: DynamicShapesType = ...
    evaluate_guards: bool = ...
    assume_32_bit_indexing: bool = ...
    def compute_hash(self) -> str: ...

@config
class CompilationConfig:
    mode: CompilationMode = ...
    debug_dump_path: Path | None = ...
    cache_dir: str = ...
    compile_cache_save_format: Literal["binary", "unpacked"] = ...
    backend: str = ...
    custom_ops: list[str] = ...
    splitting_ops: list[str] | None = ...
    compile_mm_encoder: bool = ...
    compile_sizes: list[int | str] | None = ...
    compile_ranges_endpoints: list[int] | None = ...
    inductor_compile_config: dict = ...
    inductor_passes: dict[str, str] = ...
    cudagraph_mode: CUDAGraphMode = ...
    cudagraph_num_of_warmups: int = ...
    cudagraph_capture_sizes: list[int] | None = ...
    cudagraph_copy_inputs: bool = ...
    cudagraph_specialize_lora: bool = ...
    use_inductor_graph_partition: bool = ...
    pass_config: PassConfig = ...
    max_cudagraph_capture_size: int = ...
    dynamic_shapes_config: DynamicShapesConfig = ...
    local_cache_dir: str = ...
    fast_moe_cold_start: bool | None = ...
    enabled_custom_ops: Counter[str] = ...
    disabled_custom_ops: Counter[str] = ...
    traced_files: set[str] = ...
    compilation_time: float = ...
    static_forward_context: dict[str, Any] = ...
    static_all_moe_layers: list[str] = ...
    def compute_hash(self) -> str: ...
    @classmethod
    def validate_mode_before(cls, value: Any) -> Any: ...
    @classmethod
    def validate_cudagraph_mode_before(cls, value: Any) -> Any: ...
    @classmethod
    def validate_pass_config_before(cls, value: Any) -> Any: ...
    @classmethod
    def validate_compile_cache_save_format(cls, value: str) -> str: ...
    def __post_init__(self) -> None: ...
    def init_backend(self, vllm_config: VllmConfig) -> str | Callable: ...
    def post_init_cudagraph_sizes(self) -> None: ...
    def set_splitting_ops_for_v1(
        self, all2all_backend: str, data_parallel_size: int = 1
    ): ...
    def set_splitting_ops_for_attn_fusion(self) -> None: ...
    def splitting_ops_contain_attention(self) -> bool: ...
    def is_attention_compiled_piecewise(self) -> bool: ...
    def custom_op_log_check(self) -> None: ...
    def is_custom_op_enabled(self, op: str) -> bool: ...
    def adjust_cudagraph_sizes_for_spec_decode(
        self, uniform_decode_query_len: int, tensor_parallel_size: int
    ): ...
    def adjust_cudagraph_sizes_for_mamba_cache(
        self, num_mamba_cache_blocks: int
    ) -> None: ...
    def get_compile_ranges(self) -> list[Range]: ...
