from _typeshed import Incomplete
from typing import Any, Literal
from vllm.config.utils import config as config

ECProducer: Incomplete
ECConsumer: Incomplete
ECRole = Literal[ECProducer, ECConsumer]

@config
class ECTransferConfig:
    ec_connector: str | None = ...
    engine_id: str | None = ...
    ec_buffer_device: str | None = ...
    ec_buffer_size: float = ...
    ec_role: ECRole | None = ...
    ec_rank: int | None = ...
    ec_parallel_size: int = ...
    ec_ip: str = ...
    ec_port: int = ...
    ec_connector_extra_config: dict[str, Any] = ...
    ec_connector_module_path: str | None = ...
    def compute_hash(self) -> str: ...
    def __post_init__(self) -> None: ...
    @property
    def is_ec_transfer_instance(self) -> bool: ...
    @property
    def is_ec_producer(self) -> bool: ...
    @property
    def is_ec_consumer(self) -> bool: ...
    def get_from_extra_config(self, key, default) -> Any: ...
