from typing import Literal
from vllm.config.utils import config as config

@config
class KVEventsConfig:
    enable_kv_cache_events: bool = ...
    publisher: Literal["null", "zmq"] = ...
    endpoint: str = ...
    replay_endpoint: str | None = ...
    buffer_steps: int = ...
    hwm: int = ...
    max_queue_size: int = ...
    topic: str = ...
    def __post_init__(self) -> None: ...
