from _typeshed import Incomplete
from typing import Any, Literal
from vllm.config.utils import config as config
from vllm.utils.hashing import safe_hash as safe_hash

KVProducer: Incomplete
KVConsumer: Incomplete
KVRole = Literal[KVProducer, KVConsumer]

@config
class KVTransferConfig:
    kv_connector: str | None = ...
    engine_id: str | None = ...
    kv_buffer_device: str | None = ...
    kv_buffer_size: float = ...
    kv_role: KVRole | None = ...
    kv_rank: int | None = ...
    kv_parallel_size: int = ...
    kv_ip: str = ...
    kv_port: int = ...
    kv_connector_extra_config: dict[str, Any] = ...
    kv_connector_module_path: str | None = ...
    enable_permute_local_kv: bool = ...
    kv_load_failure_policy: Literal["recompute", "fail"] = ...
    def compute_hash(self) -> str: ...
    def __post_init__(self) -> None: ...
    @property
    def is_kv_transfer_instance(self) -> bool: ...
    @property
    def is_kv_producer(self) -> bool: ...
    @property
    def is_kv_consumer(self) -> bool: ...
    def get_from_extra_config(self, key, default) -> Any: ...
