from _typeshed import Incomplete
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.model_executor.model_loader import LoadFormats as LoadFormats
from vllm.model_executor.model_loader.tensorizer import (
    TensorizerConfig as TensorizerConfig,
)
from vllm.utils.hashing import safe_hash as safe_hash

logger: Incomplete

@config
class LoadConfig:
    load_format: str | LoadFormats = ...
    download_dir: str | None = ...
    safetensors_load_strategy: str = ...
    model_loader_extra_config: dict | TensorizerConfig = ...
    device: str | None = ...
    ignore_patterns: list[str] | str = ...
    use_tqdm_on_load: bool = ...
    pt_load_map_location: str | dict[str, str] = ...
    def compute_hash(self) -> str: ...
