import torch
from _typeshed import Incomplete
from pydantic import ConfigDict
from vllm.config import ModelConfig as ModelConfig
from vllm.config.cache import CacheConfig as CacheConfig
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.utils.hashing import safe_hash as safe_hash

logger: Incomplete
LoRADType: Incomplete
MaxLoRARanks: Incomplete
LoRAExtraVocabSize: Incomplete

@config(config=ConfigDict(arbitrary_types_allowed=True))
class LoRAConfig:
    max_lora_rank: MaxLoRARanks = ...
    max_loras: int = ...
    fully_sharded_loras: bool = ...
    max_cpu_loras: int | None = ...
    lora_dtype: torch.dtype | LoRADType = ...
    default_mm_loras: dict[str, str] | None = ...
    enable_tower_connector_lora: bool = ...
    specialize_active_lora: bool = ...
    def compute_hash(self) -> str: ...
    def verify_with_model_config(self, model_config: ModelConfig): ...
