import torch
from _typeshed import Incomplete
from collections.abc import Callable, Generator
from dataclasses import InitVar
from functools import cached_property as cached_property
from pydantic import ConfigDict
from transformers import PretrainedConfig
from typing import Any
from vllm.config.load import LoadConfig as LoadConfig
from vllm.config.model_arch import ModelArchitectureConfig as ModelArchitectureConfig
from vllm.config.multimodal import (
    MMCacheType as MMCacheType,
    MMEncoderTPMode as MMEncoderTPMode,
    MultiModalConfig as MultiModalConfig,
)
from vllm.config.parallel import ParallelConfig as ParallelConfig
from vllm.config.pooler import PoolerConfig as PoolerConfig
from vllm.config.scheduler import RunnerType as RunnerType
from vllm.config.utils import config as config, getattr_iter as getattr_iter
from vllm.logger import init_logger as init_logger
from vllm.model_executor.layers.quantization import (
    QuantizationMethods as QuantizationMethods,
)
from vllm.platforms import current_platform as current_platform
from vllm.tasks import ScoreType as ScoreType
from vllm.transformers_utils.config import (
    ConfigFormat as ConfigFormat,
    get_config as get_config,
    get_hf_image_processor_config as get_hf_image_processor_config,
    get_hf_text_config as get_hf_text_config,
    get_pooling_config as get_pooling_config,
    get_sentence_transformer_tokenizer_config as get_sentence_transformer_tokenizer_config,
    is_encoder_decoder as is_encoder_decoder,
    is_rope_parameters_nested as is_rope_parameters_nested,
    try_get_dense_modules as try_get_dense_modules,
    try_get_generation_config as try_get_generation_config,
    try_get_tokenizer_config as try_get_tokenizer_config,
    uses_mrope as uses_mrope,
    uses_xdrope_dim as uses_xdrope_dim,
)
from vllm.transformers_utils.gguf_utils import (
    is_gguf as is_gguf,
    is_remote_gguf as is_remote_gguf,
    maybe_patch_hf_config_from_gguf as maybe_patch_hf_config_from_gguf,
    split_remote_gguf as split_remote_gguf,
)
from vllm.transformers_utils.model_arch_config_convertor import (
    MODEL_ARCH_CONFIG_CONVERTORS as MODEL_ARCH_CONFIG_CONVERTORS,
    ModelArchConfigConvertorBase as ModelArchConfigConvertorBase,
)
from vllm.transformers_utils.runai_utils import (
    ObjectStorageModel as ObjectStorageModel,
    is_runai_obj_uri as is_runai_obj_uri,
)
from vllm.transformers_utils.utils import maybe_model_redirect as maybe_model_redirect
from vllm.utils.import_utils import LazyLoader as LazyLoader
from vllm.v1.attention.backends.registry import (
    AttentionBackendEnum as AttentionBackendEnum,
)
from vllm.v1.sample.logits_processor import LogitsProcessor as LogitsProcessor

logger: Incomplete
RunnerOption: Incomplete
ConvertType: Incomplete
ConvertOption: Incomplete
TokenizerMode: Incomplete
ModelDType: Incomplete
LogprobsMode: Incomplete
HfOverrides = dict[str, Any] | Callable[[PretrainedConfig], PretrainedConfig]
ModelImpl: Incomplete
LayerBlockType: Incomplete
AttnTypeStr: Incomplete

@config(config=ConfigDict(arbitrary_types_allowed=True))
class ModelConfig:
    model: str = ...
    model_weights: str = ...
    runner: RunnerOption = ...
    convert: ConvertOption = ...
    tokenizer: str = ...
    tokenizer_mode: TokenizerMode | str = ...
    trust_remote_code: bool = ...
    dtype: ModelDType | torch.dtype = ...
    seed: int = ...
    hf_config: PretrainedConfig = ...
    hf_text_config: PretrainedConfig = ...
    hf_config_path: str | None = ...
    allowed_local_media_path: str = ...
    allowed_media_domains: list[str] | None = ...
    revision: str | None = ...
    code_revision: str | None = ...
    tokenizer_revision: str | None = ...
    max_model_len: int = ...
    spec_target_max_model_len: int | None = ...
    quantization: QuantizationMethods | str | None = ...
    allow_deprecated_quantization: bool = ...
    enforce_eager: bool = ...
    enable_return_routed_experts: bool = ...
    max_logprobs: int = ...
    logprobs_mode: LogprobsMode = ...
    disable_sliding_window: bool = ...
    disable_cascade_attn: bool = ...
    skip_tokenizer_init: bool = ...
    enable_prompt_embeds: bool = ...
    served_model_name: str | list[str] | None = ...
    config_format: str | ConfigFormat = ...
    hf_token: bool | str | None = ...
    hf_overrides: HfOverrides = ...
    generation_config: str = ...
    override_generation_config: dict[str, Any] = ...
    enable_sleep_mode: bool = ...
    model_impl: str | ModelImpl = ...
    override_attention_dtype: str | None = ...
    logits_processors: list[str | type[LogitsProcessor]] | None = ...
    io_processor_plugin: str | None = ...
    pooler_config: PoolerConfig | None = ...
    multimodal_config: MultiModalConfig | None = ...
    language_model_only: InitVar[bool] = ...
    limit_mm_per_prompt: InitVar[dict[str, int | dict[str, int]] | None] = ...
    enable_mm_embeds: InitVar[bool | None] = ...
    media_io_kwargs: InitVar[dict[str, dict[str, Any]] | None] = ...
    mm_processor_kwargs: InitVar[dict[str, Any] | None] = ...
    mm_processor_cache_gb: InitVar[float | None] = ...
    mm_processor_cache_type: InitVar[MMCacheType | None] = ...
    mm_shm_cache_max_object_size_mb: InitVar[int | None] = ...
    mm_encoder_only: InitVar[bool | None] = ...
    mm_encoder_tp_mode: InitVar[MMEncoderTPMode | None] = ...
    mm_encoder_attn_backend: InitVar[AttentionBackendEnum | str | None] = ...
    interleave_mm_strings: InitVar[bool | None] = ...
    skip_mm_profiling: InitVar[bool | None] = ...
    video_pruning_rate: InitVar[float | None] = ...
    def compute_hash(self) -> str: ...
    attention_chunk_size = ...
    encoder_config = ...
    hf_image_processor_config = ...
    model_arch_config = ...
    runner_type = ...
    convert_type = ...
    original_max_model_len = ...
    config_updated = ...
    def __post_init__(
        self,
        language_model_only: bool,
        limit_mm_per_prompt: dict[str, int | dict[str, int]] | None,
        enable_mm_embeds: bool | None,
        media_io_kwargs: dict[str, dict[str, Any]] | None,
        mm_processor_kwargs: dict[str, Any] | None,
        mm_processor_cache_gb: float | None,
        mm_processor_cache_type: MMCacheType | None,
        mm_shm_cache_max_object_size_mb: int | None,
        mm_encoder_only: bool | None,
        mm_encoder_tp_mode: MMEncoderTPMode | None,
        mm_encoder_attn_backend: AttentionBackendEnum | str | None,
        interleave_mm_strings: bool | None,
        skip_mm_profiling: bool | None,
        video_pruning_rate: float | None,
    ) -> None: ...
    def get_model_arch_config(self) -> ModelArchitectureConfig: ...
    @classmethod
    def validate_quantization_before(cls, value: Any) -> Any: ...
    def validate_model_config_after(self) -> ModelConfig: ...
    def using_transformers_backend(self) -> bool: ...
    @property
    def registry(self): ...
    @property
    def architectures(self) -> list[str]: ...
    @property
    def architecture(self) -> str: ...
    def maybe_pull_model_tokenizer_for_runai(
        self, model: str, tokenizer: str
    ) -> None: ...
    def verify_dual_chunk_attention_config(self, load_config: LoadConfig) -> None: ...
    def verify_with_parallel_config(self, parallel_config: ParallelConfig) -> None: ...
    def get_sliding_window(self) -> int | None: ...
    def get_vocab_size(self) -> int: ...
    def get_hidden_size(self) -> int: ...
    def get_inputs_embeds_size(self) -> int: ...
    @property
    def is_deepseek_mla(self) -> bool: ...
    @cached_property
    def is_mm_prefix_lm(self) -> bool: ...
    def get_head_size(self) -> int: ...
    def get_total_num_kv_heads(self) -> int: ...
    def get_num_kv_heads(self, parallel_config: ParallelConfig) -> int: ...
    def get_num_attention_heads(self, parallel_config: ParallelConfig) -> int: ...
    def get_num_experts(self) -> int: ...
    def get_total_num_hidden_layers(self) -> int: ...
    def get_layers_start_end_indices(
        self, parallel_config: ParallelConfig
    ) -> tuple[int, int]: ...
    def get_num_layers(self, parallel_config: ParallelConfig) -> int: ...
    def get_num_layers_by_block_type(
        self, parallel_config: ParallelConfig, block_type: LayerBlockType = "attention"
    ) -> int: ...
    def get_mamba_chunk_size(self) -> int | None: ...
    def get_multimodal_config(self) -> MultiModalConfig: ...
    def try_get_generation_config(self) -> dict[str, Any]: ...
    def get_diff_sampling_param(self) -> dict[str, Any]: ...
    @cached_property
    def is_encoder_decoder(self) -> bool: ...
    @property
    def uses_alibi(self) -> bool: ...
    @property
    def uses_mrope(self) -> bool: ...
    @property
    def uses_xdrope_dim(self) -> int: ...
    @property
    def is_multimodal_model(self) -> bool: ...
    @property
    def is_multimodal_raw_input_only_model(self) -> bool: ...
    @property
    def requires_raw_input_tokens(self) -> bool: ...
    @property
    def score_type(self) -> ScoreType: ...
    @property
    def is_pp_supported(self) -> bool: ...
    @property
    def is_attention_free(self) -> bool: ...
    @property
    def is_hybrid(self) -> bool: ...
    @property
    def has_noops(self) -> bool: ...
    @property
    def has_inner_state(self): ...
    @property
    def supports_mamba_prefix_caching(self) -> bool: ...
    @property
    def use_mla(self) -> bool: ...
    @property
    def is_matryoshka(self) -> bool: ...
    @property
    def matryoshka_dimensions(self): ...
    @property
    def use_sep_token(self) -> bool: ...
    @property
    def head_dtype(self) -> torch.dtype: ...
    @property
    def embedding_size(self): ...
    def get_and_verify_max_len(self, max_model_len: int): ...
    @property
    def attn_type(self) -> AttnTypeStr: ...
    @property
    def is_chunked_prefill_supported(self) -> bool: ...
    @property
    def is_prefix_caching_supported(self) -> bool: ...
    @property
    def is_moe(self) -> bool: ...
    @property
    def is_quantized(self) -> bool: ...
    def is_nvfp4_quantized(self) -> bool: ...

def get_served_model_name(model: str, served_model_name: str | list[str] | None): ...
def iter_architecture_defaults() -> Generator[Incomplete, Incomplete]: ...
def try_match_architecture_defaults(
    architecture: str,
    *,
    runner_type: RunnerType | None = None,
    convert_type: ConvertType | None = None,
) -> tuple[str, tuple[RunnerType, ConvertType]] | None: ...
def str_dtype_to_torch_dtype(type: str): ...
