from _typeshed import Incomplete
from collections.abc import Mapping
from typing import Any, TypeAlias, TypedDict
from vllm.config.utils import config as config
from vllm.utils.hashing import safe_hash as safe_hash
from vllm.v1.attention.backends.registry import (
    AttentionBackendEnum as AttentionBackendEnum,
)

class BaseDummyOptions:
    count: int

class VideoDummyOptions(BaseDummyOptions):
    num_frames: int | None
    width: int | None
    height: int | None

class ImageDummyOptions(BaseDummyOptions):
    width: int | None
    height: int | None

class AudioDummyOptions(BaseDummyOptions):
    length: int | None

class MultiModalDummyOptionsBuiltins(TypedDict, total=False):
    image: ImageDummyOptions
    video: VideoDummyOptions
    audio: AudioDummyOptions

MMEncoderTPMode: Incomplete
MMCacheType: Incomplete
MMDummyOptions: TypeAlias = dict[str, BaseDummyOptions]

@config
class MultiModalConfig:
    language_model_only: bool = ...
    limit_per_prompt: MMDummyOptions = ...
    enable_mm_embeds: bool = ...
    media_io_kwargs: dict[str, dict[str, Any]] = ...
    mm_processor_kwargs: dict[str, object] | None = ...
    mm_processor_cache_gb: float = ...
    mm_processor_cache_type: MMCacheType = ...
    mm_shm_cache_max_object_size_mb: int = ...
    mm_encoder_only: bool = ...
    mm_encoder_tp_mode: MMEncoderTPMode = ...
    mm_encoder_attn_backend: AttentionBackendEnum | None = ...
    interleave_mm_strings: bool = ...
    skip_mm_profiling: bool = ...
    video_pruning_rate: float | None = ...
    def compute_hash(self) -> str: ...
    def get_limit_per_prompt(self, modality: str) -> int: ...
    def merge_mm_processor_kwargs(
        self, inference_kwargs: Mapping[str, object]
    ) -> dict[str, object]: ...
    def is_multimodal_pruning_enabled(self): ...
