from _typeshed import Incomplete
from functools import cached_property as cached_property
from vllm import version as version
from vllm.config.utils import config as config
from vllm.utils.hashing import safe_hash as safe_hash

DetailedTraceModules: Incomplete

@config
class ObservabilityConfig:
    show_hidden_metrics_for_version: str | None = ...
    @cached_property
    def show_hidden_metrics(self) -> bool: ...
    otlp_traces_endpoint: str | None = ...
    collect_detailed_traces: list[DetailedTraceModules] | None = ...
    kv_cache_metrics: bool = ...
    kv_cache_metrics_sample: float = ...
    cudagraph_metrics: bool = ...
    enable_layerwise_nvtx_tracing: bool = ...
    enable_mfu_metrics: bool = ...
    enable_mm_processor_stats: bool = ...
    enable_logging_iteration_details: bool = ...
    @cached_property
    def collect_model_forward_time(self) -> bool: ...
    @cached_property
    def collect_model_execute_time(self) -> bool: ...
    def compute_hash(self) -> str: ...
