from _typeshed import Incomplete
from vllm.config.utils import config as config

OffloadBackend: Incomplete

@config
class UVAOffloadConfig:
    cpu_offload_gb: float = ...
    cpu_offload_params: set[str] = ...

@config
class PrefetchOffloadConfig:
    offload_group_size: int = ...
    offload_num_in_group: int = ...
    offload_prefetch_step: int = ...
    offload_params: set[str] = ...

@config
class OffloadConfig:
    offload_backend: OffloadBackend = ...
    uva: UVAOffloadConfig = ...
    prefetch: PrefetchOffloadConfig = ...
    def validate_offload_config(self) -> OffloadConfig: ...
    def compute_hash(self) -> str: ...
