from _typeshed import Incomplete
from collections.abc import Callable as Callable
from ray.runtime_env import RuntimeEnv as RuntimeEnv
from ray.util.placement_group import PlacementGroup as PlacementGroup
from torch.distributed import ProcessGroup as ProcessGroup, Store as Store
from typing import Literal, overload
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.model_executor.layers.batch_invariant import (
    vllm_is_batch_invariant as vllm_is_batch_invariant,
)
from vllm.platforms import current_platform as current_platform
from vllm.utils.network_utils import get_open_ports_list as get_open_ports_list
from vllm.utils.torch_utils import (
    cuda_device_count_stateless as cuda_device_count_stateless,
)
from vllm.v1.executor import Executor as Executor

logger: Incomplete
ExpertPlacementStrategy: Incomplete
DistributedExecutorBackend: Incomplete
DataParallelBackend: Incomplete
EPLBPolicyOption: Incomplete
DCPCommBackend: Incomplete
All2AllBackend: Incomplete

@config
class EPLBConfig:
    window_size: int = ...
    step_interval: int = ...
    num_redundant_experts: int = ...
    log_balancedness: bool = ...
    log_balancedness_interval: int = ...
    use_async: bool = ...
    policy: EPLBPolicyOption = ...

@config
class ParallelConfig:
    pipeline_parallel_size: int = ...
    tensor_parallel_size: int = ...
    prefill_context_parallel_size: int = ...
    data_parallel_size: int = ...
    data_parallel_size_local: int = ...
    data_parallel_rank: int = ...
    data_parallel_rank_local: int | None = ...
    data_parallel_master_ip: str = ...
    data_parallel_rpc_port: int = ...
    data_parallel_master_port: int = ...
    data_parallel_backend: DataParallelBackend = ...
    data_parallel_external_lb: bool = ...
    data_parallel_hybrid_lb: bool = ...
    is_moe_model: bool | None = ...
    enable_expert_parallel: bool = ...
    enable_eplb: bool = ...
    eplb_config: EPLBConfig = ...
    expert_placement_strategy: ExpertPlacementStrategy = ...
    all2all_backend: All2AllBackend = ...
    max_parallel_loading_workers: int | None = ...
    disable_custom_all_reduce: bool = ...
    enable_elastic_ep: bool = ...
    enable_dbo: bool = ...
    ubatch_size: int = ...
    dbo_decode_token_threshold: int = ...
    dbo_prefill_token_threshold: int = ...
    disable_nccl_for_dp_synchronization: bool | None = ...
    ray_workers_use_nsight: bool = ...
    ray_runtime_env: RuntimeEnv | None = ...
    placement_group: PlacementGroup | None = ...
    distributed_executor_backend: (
        str | DistributedExecutorBackend | type[Executor] | None
    ) = ...
    worker_cls: str = ...
    sd_worker_cls: str = ...
    worker_extension_cls: str = ...
    master_addr: str = ...
    master_port: int = ...
    node_rank: int = ...
    nnodes: int = ...
    distributed_timeout_seconds: int | None = ...
    world_size: int = ...
    rank: int = ...
    decode_context_parallel_size: int = ...
    dcp_kv_cache_interleave_size: int = ...
    dcp_comm_backend: DCPCommBackend = ...
    cp_kv_cache_interleave_size: int = ...
    data_parallel_index: int = ...
    @property
    def world_size_across_dp(self) -> int: ...
    @property
    def use_ubatching(self) -> bool: ...
    @property
    def num_ubatches(self) -> int: ...
    @property
    def local_engines_only(self) -> bool: ...
    def get_next_dp_init_port(self) -> int: ...
    def allocate_elastic_ep_ports(self) -> None: ...
    def get_next_stateless_world_group_port(self) -> list[int]: ...
    def get_next_stateless_dp_group_port(self) -> list[int]: ...
    def get_next_stateless_ep_group_port(self) -> list[int]: ...
    def get_next_stateless_eplb_group_port(self) -> list[int]: ...
    @overload
    def stateless_init_dp_group(
        self, return_store: Literal[False] = ...
    ) -> ProcessGroup: ...
    @overload
    def stateless_init_dp_group(
        self, return_store: Literal[True] = ...
    ) -> tuple[ProcessGroup, Store]: ...
    @property
    def use_sequence_parallel_moe(self) -> bool: ...
    @property
    def node_rank_within_dp(self) -> int: ...
    @property
    def nnodes_within_dp(self) -> int: ...
    @property
    def local_world_size(self) -> int: ...
    @staticmethod
    def has_unfinished_dp(dp_group: ProcessGroup, has_unfinished: bool) -> bool: ...
    @staticmethod
    def sync_kv_cache_memory_size(
        dp_group: ProcessGroup, kv_cache_memory: int
    ) -> int: ...
    def compute_hash(self): ...
    def __post_init__(self) -> None: ...
    @property
    def use_ray(self) -> bool: ...
