from _typeshed import Incomplete
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.utils.hashing import safe_hash as safe_hash

logger: Incomplete
SequencePoolingType: Incomplete
SEQ_POOLING_TYPES: tuple[SequencePoolingType, ...]
TokenPoolingType: Incomplete
TOK_POOLING_TYPES: tuple[TokenPoolingType, ...]

@config
class PoolerConfig:
    pooling_type: SequencePoolingType | TokenPoolingType | None = ...
    seq_pooling_type: SequencePoolingType | None = ...
    tok_pooling_type: TokenPoolingType | None = ...
    use_activation: bool | None = ...
    dimensions: int | None = ...
    enable_chunked_processing: bool = ...
    max_embed_len: int | None = ...
    logit_bias: float | None = ...
    step_tag_id: int | None = ...
    returned_token_ids: list[int] | None = ...
    def __post_init__(self) -> None: ...
    def get_seq_pooling_type(self) -> SequencePoolingType: ...
    def get_tok_pooling_type(self) -> TokenPoolingType: ...
    def compute_hash(self) -> str: ...
