from _typeshed import Incomplete
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.utils.hashing import safe_hash as safe_hash

logger: Incomplete
ProfilerKind: Incomplete

@config
class ProfilerConfig:
    profiler: ProfilerKind | None = ...
    torch_profiler_dir: str = ...
    torch_profiler_with_stack: bool = ...
    torch_profiler_with_flops: bool = ...
    torch_profiler_use_gzip: bool = ...
    torch_profiler_dump_cuda_time_total: bool = ...
    torch_profiler_record_shapes: bool = ...
    torch_profiler_with_memory: bool = ...
    ignore_frontend: bool = ...
    delay_iterations: int = ...
    max_iterations: int = ...
    warmup_iterations: int = ...
    active_iterations: int = ...
    wait_iterations: int = ...
    def compute_hash(self) -> str: ...
