from _typeshed import Incomplete
from collections.abc import Callable as Callable
from dataclasses import InitVar
from typing import ClassVar
from typing_extensions import Self
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.utils.hashing import safe_hash as safe_hash
from vllm.utils.import_utils import resolve_obj_by_qualname as resolve_obj_by_qualname
from vllm.v1.core.sched.interface import SchedulerInterface as SchedulerInterface

logger: Incomplete
RunnerType: Incomplete
SchedulerPolicy: Incomplete

@config
class SchedulerConfig:
    max_model_len: InitVar[int]
    is_encoder_decoder: InitVar[bool]
    DEFAULT_MAX_NUM_BATCHED_TOKENS: ClassVar[int] = ...
    DEFAULT_MAX_NUM_SEQS: ClassVar[int] = ...
    runner_type: RunnerType = ...
    max_num_batched_tokens: int = ...
    max_num_scheduled_tokens: int | None = ...
    max_num_seqs: int = ...
    max_num_partial_prefills: int = ...
    max_long_partial_prefills: int = ...
    long_prefill_token_threshold: int = ...
    enable_chunked_prefill: bool = ...
    is_multimodal_model: bool = ...
    max_num_encoder_input_tokens: int = ...
    encoder_cache_size: int = ...
    policy: SchedulerPolicy = ...
    disable_chunked_mm_input: bool = ...
    scheduler_cls: str | type[object] | None = ...
    disable_hybrid_kv_cache_manager: bool | None = ...
    async_scheduling: bool | None = ...
    stream_interval: int = ...
    @staticmethod
    def default_factory(**kwargs): ...
    def get_scheduler_cls(self) -> type["SchedulerInterface"]: ...
    def compute_hash(self) -> str: ...
    def __post_init__(self, max_model_len: int, is_encoder_decoder: bool) -> None: ...
    def verify_max_model_len(self, max_model_len: int) -> Self: ...
