import vllm.model_executor.layers.quantization as me_quant
from _typeshed import Incomplete
from pydantic import SkipValidation as SkipValidation
from transformers import PretrainedConfig as PretrainedConfig
from vllm.config import LoadConfig as LoadConfig
from vllm.config.model import ModelConfig as ModelConfig
from vllm.config.parallel import ParallelConfig as ParallelConfig
from vllm.config.utils import config as config
from vllm.logger import init_logger as init_logger
from vllm.transformers_utils.config import get_hf_text_config as get_hf_text_config
from vllm.utils.hashing import safe_hash as safe_hash
from vllm.utils.import_utils import (
    LazyLoader as LazyLoader,
    has_arctic_inference as has_arctic_inference,
)

logger: Incomplete
MTPModelTypes: Incomplete
EagleModelTypes: Incomplete
NgramGPUTypes: Incomplete
SpeculativeMethod: Incomplete

@config
class SpeculativeConfig:
    enforce_eager: bool | None = ...
    num_speculative_tokens: int = ...
    model: str | None = ...
    method: SpeculativeMethod | None = ...
    draft_tensor_parallel_size: int | None = ...
    tensor_parallel_size: int | None = ...
    quantization: me_quant.QuantizationMethods | None = ...
    max_model_len: int | None = ...
    revision: str | None = ...
    code_revision: str | None = ...
    disable_padded_drafter_batch: bool = ...
    use_local_argmax_reduction: bool = ...
    prompt_lookup_max: int | None = ...
    prompt_lookup_min: int | None = ...
    speculative_token_tree: str | None = ...
    parallel_drafting: bool = ...
    target_model_config: SkipValidation[ModelConfig] = ...
    target_parallel_config: SkipValidation[ParallelConfig] = ...
    draft_model_config: SkipValidation[ModelConfig] = ...
    draft_parallel_config: SkipValidation[ParallelConfig] = ...
    suffix_decoding_max_tree_depth: int = ...
    suffix_decoding_max_cached_requests: int = ...
    suffix_decoding_max_spec_factor: float = ...
    suffix_decoding_min_token_prob: float = ...
    draft_load_config: LoadConfig | None = ...
    def compute_hash(self) -> str: ...
    @staticmethod
    def hf_config_override(hf_config: PretrainedConfig) -> PretrainedConfig: ...
    def __post_init__(self): ...
    def update_arch_(self) -> None: ...
    @staticmethod
    def create_draft_parallel_config(
        target_parallel_config: ParallelConfig,
        speculative_draft_tensor_parallel_size: int,
    ) -> ParallelConfig: ...
    def verify_equal_vocab_size_if_draft_model(self) -> None: ...
    @property
    def max_num_new_slots_for_drafting(self) -> int: ...
    def use_eagle(self) -> bool: ...
    def uses_draft_model(self) -> bool: ...
    def uses_extract_hidden_states(self) -> bool: ...
    def use_ngram_gpu(self) -> bool: ...
