from vllm.config.utils import config as config

@config
class SpeechToTextConfig:
    sample_rate: float = ...
    max_audio_clip_s: int | None = ...
    overlap_chunk_second: int = ...
    min_energy_split_window_size: int | None = ...
    @property
    def allow_audio_chunking(self) -> bool: ...
