from _typeshed import Incomplete
from vllm.config.utils import config as config
from vllm.utils.hashing import safe_hash as safe_hash

StructuredOutputsBackend: Incomplete

@config
class StructuredOutputsConfig:
    backend: StructuredOutputsBackend = ...
    disable_any_whitespace: bool = ...
    disable_additional_properties: bool = ...
    reasoning_parser: str = ...
    reasoning_parser_plugin: str = ...
    enable_in_reasoning: bool = ...
    def compute_hash(self) -> str: ...
