from .attention import AttentionConfig as AttentionConfig
from .cache import CacheConfig as CacheConfig
from .compilation import (
    CUDAGraphMode as CUDAGraphMode,
    CompilationConfig as CompilationConfig,
    CompilationMode as CompilationMode,
)
from .device import DeviceConfig as DeviceConfig
from .ec_transfer import ECTransferConfig as ECTransferConfig
from .kernel import KernelConfig as KernelConfig
from .kv_events import KVEventsConfig as KVEventsConfig
from .kv_transfer import KVTransferConfig as KVTransferConfig
from .load import LoadConfig as LoadConfig
from .lora import LoRAConfig as LoRAConfig
from .model import ModelConfig as ModelConfig
from .observability import ObservabilityConfig as ObservabilityConfig
from .offload import OffloadConfig as OffloadConfig
from .parallel import ParallelConfig as ParallelConfig
from .profiler import ProfilerConfig as ProfilerConfig
from .scheduler import SchedulerConfig as SchedulerConfig
from .speculative import (
    EagleModelTypes as EagleModelTypes,
    NgramGPUTypes as NgramGPUTypes,
    SpeculativeConfig as SpeculativeConfig,
)
from .structured_outputs import StructuredOutputsConfig as StructuredOutputsConfig
from .utils import SupportsHash as SupportsHash, config as config, replace as replace
from .weight_transfer import WeightTransferConfig as WeightTransferConfig
from _typeshed import Incomplete
from contextlib import contextmanager
from enum import IntEnum
from pathlib import Path
from pydantic import ConfigDict
from transformers import PretrainedConfig as PretrainedConfig
from typing import TypeVar
from vllm.logger import (
    enable_trace_function_call as enable_trace_function_call,
    init_logger as init_logger,
)
from vllm.model_executor.layers.quantization.base_config import (
    QuantizationConfig as QuantizationConfig,
)
from vllm.transformers_utils.runai_utils import is_runai_obj_uri as is_runai_obj_uri
from vllm.utils import random_uuid as random_uuid
from vllm.utils.hashing import safe_hash as safe_hash
from vllm.v1.kv_cache_interface import KVCacheConfig as KVCacheConfig

logger: Incomplete

class OptimizationLevel(IntEnum):
    O0 = 0
    O1 = 1
    O2 = 2
    O3 = 3

PerformanceMode: Incomplete
IS_QUANTIZED: bool
IS_DENSE: bool

def enable_norm_fusion(cfg: VllmConfig) -> bool: ...
def enable_act_fusion(cfg: VllmConfig) -> bool: ...
def enable_allreduce_rms_fusion(cfg: VllmConfig) -> bool: ...
def enable_rope_kvcache_fusion(cfg: VllmConfig) -> bool: ...
def enable_norm_pad_fusion(cfg: VllmConfig) -> bool: ...

OPTIMIZATION_LEVEL_00: Incomplete
OPTIMIZATION_LEVEL_01: Incomplete
OPTIMIZATION_LEVEL_02: Incomplete
OPTIMIZATION_LEVEL_03: Incomplete
OPTIMIZATION_LEVEL_TO_CONFIG: Incomplete

@config(config=ConfigDict(arbitrary_types_allowed=True))
class VllmConfig:
    model_config: ModelConfig = ...
    cache_config: CacheConfig = ...
    parallel_config: ParallelConfig = ...
    scheduler_config: SchedulerConfig = ...
    device_config: DeviceConfig = ...
    load_config: LoadConfig = ...
    offload_config: OffloadConfig = ...
    attention_config: AttentionConfig = ...
    kernel_config: KernelConfig = ...
    lora_config: LoRAConfig | None = ...
    speculative_config: SpeculativeConfig | None = ...
    structured_outputs_config: StructuredOutputsConfig = ...
    observability_config: ObservabilityConfig = ...
    quant_config: QuantizationConfig | None = ...
    compilation_config: CompilationConfig = ...
    profiler_config: ProfilerConfig = ...
    kv_transfer_config: KVTransferConfig | None = ...
    kv_events_config: KVEventsConfig | None = ...
    ec_transfer_config: ECTransferConfig | None = ...
    additional_config: dict | SupportsHash = ...
    instance_id: str = ...
    optimization_level: OptimizationLevel = ...
    performance_mode: PerformanceMode = ...
    weight_transfer_config: WeightTransferConfig | None = ...
    def compute_hash(self) -> str: ...
    @property
    def num_speculative_tokens(self) -> int: ...
    @property
    def needs_dp_coordinator(self) -> bool: ...
    def enable_trace_function_call_for_thread(self) -> None: ...
    @staticmethod
    def get_quantization_config(
        model_config: ModelConfig, load_config: LoadConfig
    ) -> QuantizationConfig | None: ...
    def with_hf_config(
        self, hf_config: PretrainedConfig, architectures: list[str] | None = None
    ) -> VllmConfig: ...
    def __post_init__(self): ...
    def update_sizes_for_sequence_parallelism(self, possible_sizes: list) -> list: ...
    def try_verify_and_update_config(self) -> None: ...
    def compile_debug_dump_path(self) -> Path | None: ...
    def validate_block_size(self) -> None: ...
    def validate_mamba_block_size(self) -> VllmConfig: ...

@contextmanager
def set_current_vllm_config(
    vllm_config: VllmConfig, check_compile: bool = False, prefix: str | None = None
): ...
def get_cached_compilation_config(): ...
def get_current_vllm_config() -> VllmConfig: ...
def get_current_vllm_config_or_none() -> VllmConfig | None: ...

T = TypeVar("T")

def get_layers_from_vllm_config(
    vllm_config: VllmConfig, layer_type: type[T], layer_names: list[str] | None = None
) -> dict[str, T]: ...
