"""
This type stub file was generated by pyright.
"""

import mlx.core as mx

from mflux.models.flux.model.flux_vae.vae import VAE

class KontextUtil:
    @staticmethod
    def create_image_conditioning_latents(
        vae: VAE,
        height: int,
        width: int,
        image_path: str,
    ) -> tuple[mx.array, mx.array]: ...
