import torch
from _typeshed import Incomplete
from vllm.scalar_type import ScalarType as ScalarType, scalar_types as scalar_types

MACHETE_PREPACKED_BLOCK_SHAPE: Incomplete

def query_machete_supported_quant_types(zero_points: bool) -> list[ScalarType]: ...
def query_machete_supported_act_types(zero_points: bool) -> list[ScalarType]: ...
def query_machete_supported_group_sizes(act_type: torch.dtype) -> list[int]: ...
def check_machete_supports_shape(
    in_features: int, out_features: int
) -> tuple[bool, str | None]: ...
