__all__ = ["break_fp4_bytes", "dequantize_to_dtype", "ref_nvfp4_quant"]

def break_fp4_bytes(a, dtype): ...
def dequantize_to_dtype(
    tensor_fp4, tensor_sf, global_scale, dtype, device, block_size: int = 16
): ...
def ref_nvfp4_quant(x, global_scale, block_size): ...
