import torch
from _typeshed import Incomplete
from vllm.platforms import current_platform as current_platform

def sparse_cutlass_supported() -> bool: ...
def cutlass_fp8_supported() -> bool: ...
def cutlass_block_fp8_supported() -> bool: ...
def cutlass_group_gemm_supported() -> bool: ...

CUTLASS_FP8_SUPPORTED: Incomplete
CUTLASS_BLOCK_FP8_SUPPORTED: Incomplete

def per_tensor_dequantize(
    tensor: torch.Tensor, inv_scale: float | torch.Tensor
) -> torch.Tensor: ...
def all_close_1d(x: torch.Tensor) -> bool: ...
def convert_to_channelwise(
    weight_scale: torch.Tensor, logical_widths: list[int]
) -> tuple[torch.Tensor, torch.Tensor]: ...
def requantize_with_max_scale(
    weight: torch.Tensor, weight_scale: torch.Tensor, logical_widths: list[int]
) -> tuple[torch.Tensor, torch.Tensor]: ...
def normalize_e4m3fn_to_e4m3fnuz(
    weight: torch.Tensor,
    weight_scale: torch.Tensor,
    input_scale: torch.Tensor | None = None,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor | None]: ...
