from .repo_utils import list_filtered_repo_files as list_filtered_repo_files
from _typeshed import Incomplete
from functools import cache
from os import PathLike
from pathlib import Path
from transformers import PretrainedConfig as PretrainedConfig, SiglipVisionConfig
from vllm.logger import init_logger as init_logger

logger: Incomplete

@cache
def check_gguf_file(model: str | PathLike) -> bool: ...
@cache
def is_remote_gguf(model: str | Path) -> bool: ...
def is_valid_gguf_quant_type(gguf_quant_type: str) -> bool: ...
def split_remote_gguf(model: str | Path) -> tuple[str, str]: ...
def is_gguf(model: str | Path) -> bool: ...
def detect_gguf_multimodal(model: str) -> Path | None: ...
def extract_vision_config_from_gguf(mmproj_path: str) -> SiglipVisionConfig | None: ...
def maybe_patch_hf_config_from_gguf(
    model: str, hf_config: PretrainedConfig
) -> PretrainedConfig: ...
def get_gguf_file_path_from_hf(
    repo_id: str | Path, quant_type: str, revision: str | None = None
) -> str: ...
