from _typeshed import Incomplete
from transformers import PretrainedConfig as PretrainedConfig
from typing import final
from vllm import envs as envs
from vllm.config.model_arch import ModelArchitectureConfig as ModelArchitectureConfig
from vllm.config.utils import getattr_iter as getattr_iter
from vllm.logger import init_logger as init_logger
from vllm.transformers_utils.config import (
    ConfigFormat as ConfigFormat,
    try_get_safetensors_metadata as try_get_safetensors_metadata,
)
from vllm.utils.torch_utils import (
    common_broadcastable_dtype as common_broadcastable_dtype,
)

logger: Incomplete

class ModelArchConfigConvertorBase:
    hf_config: Incomplete
    hf_text_config: Incomplete
    def __init__(
        self, hf_config: PretrainedConfig, hf_text_config: PretrainedConfig
    ) -> None: ...
    def get_architectures(self) -> list[str]: ...
    def get_num_hidden_layers(self) -> int: ...
    def get_total_num_attention_heads(self) -> int: ...
    def get_vocab_size(self) -> int: ...
    def get_hidden_size(self) -> int: ...
    def get_head_size(self) -> int: ...
    def get_total_num_kv_heads(self) -> int: ...
    def get_num_experts_from_block_configs(self) -> int: ...
    def get_num_experts(self) -> int: ...
    @final
    @classmethod
    def get_torch_dtype(
        cls,
        hf_config: PretrainedConfig,
        model_id: str,
        revision: str | None,
        config_format: ConfigFormat,
    ): ...
    def get_quantization_config(self): ...
    def is_deepseek_mla(self) -> bool: ...
    def derive_max_model_len_and_key(self) -> tuple[float, str | None]: ...
    def convert(self) -> ModelArchitectureConfig: ...

class MambaModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_head_size(self) -> int: ...
    def get_total_num_kv_heads(self) -> int: ...

class TerratorchModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_head_size(self) -> int: ...
    def get_total_num_kv_heads(self) -> int: ...

class MedusaModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_head_size(self) -> int: ...
    def get_total_num_kv_heads(self) -> int: ...

class Zamba2ModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_head_size(self) -> int: ...

class FalconModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_total_num_kv_heads(self) -> int: ...

class MPTModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_total_num_kv_heads(self) -> int: ...

class DbrxModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_total_num_kv_heads(self) -> int: ...

class NemotronNasModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_total_num_kv_heads(self) -> int: ...

class DeepSeekMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class MimoMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class GLM4MoeMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class ErnieMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class Qwen3NextMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class Qwen3_5MTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class PanguUltraMoeMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

class LongCatFlashMTPModelArchConfigConvertor(ModelArchConfigConvertorBase):
    def get_num_hidden_layers(self) -> int: ...

MODEL_ARCH_CONFIG_CONVERTORS: Incomplete
