from _typeshed import Incomplete
from functools import cache
from os import PathLike
from typing import Any
from vllm.logger import init_logger as init_logger

logger: Incomplete

def is_s3(model_or_path: str) -> bool: ...
def is_gcs(model_or_path: str) -> bool: ...
def is_cloud_storage(model_or_path: str) -> bool: ...
def without_trust_remote_code(kwargs: dict[str, Any]) -> dict[str, Any]: ...
def modelscope_list_repo_files(
    repo_id: str, revision: str | None = None, token: str | bool | None = None
) -> list[str]: ...
@cache
def maybe_model_redirect(model: str) -> str: ...
def parse_safetensors_file_metadata(path: str | PathLike) -> dict[str, Any]: ...
def convert_model_repo_to_path(model_repo: str) -> str: ...
