"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional

import mlx.core as mx
from mflux.models.common.weights.mapping.weight_mapping import WeightTarget

class WeightMapper:
    @staticmethod
    def apply_mapping(
        hf_weights: Dict[str, mx.array],
        mapping: List[WeightTarget],
        num_blocks: Optional[int] = ...,
        num_layers: Optional[int] = ...,
    ) -> Dict: ...
