"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mflux.models.common.tokenizer import Tokenizer
from mflux.models.flux.model.flux_text_encoder.clip_encoder.clip_encoder import CLIPEncoder
from mflux.models.flux.model.flux_text_encoder.t5_encoder.t5_encoder import T5Encoder

"""
This type stub file was generated by pyright.
"""
class PromptEncoder:
    @staticmethod
    def encode_prompt(prompt: str, prompt_cache: dict[str, tuple[mx.array, mx.array]], t5_tokenizer: Tokenizer, clip_tokenizer: Tokenizer, t5_text_encoder: T5Encoder, clip_text_encoder: CLIPEncoder) -> tuple[mx.array, mx.array]:
        ...
    


