from collections.abc import Iterable, Iterator
from torch import fx as fx
from torch._ops import OpOverload, OpOverloadPacket
from torch.fx.node import Target as Target

def is_func(node: fx.Node, target: Target) -> bool: ...
def is_auto_func(node: fx.Node, op: OpOverload) -> bool: ...
def find_auto_fn_maybe(nodes: Iterable[fx.Node], op: OpOverload) -> fx.Node | None: ...
def find_auto_fn(nodes: Iterable[fx.Node], op: OpOverload) -> fx.Node: ...
def find_getitem_maybe(node: fx.Node, idx: int) -> fx.Node | None: ...
def find_getitem(node: fx.Node, idx: int) -> fx.Node: ...
def find_op_nodes(
    op: OpOverload | OpOverloadPacket, graph: fx.Graph
) -> Iterator[fx.Node]: ...
def get_only_user(node: fx.Node) -> fx.Node: ...
