"""
This type stub file was generated by pyright.
"""

from mflux.models.common.lora.layer.linear_lora_layer import LoRALinear
from mlx import nn

class FusedLoRALinear(nn.Module):
    def __init__(
        self, base_linear: nn.Linear | nn.QuantizedLinear, loras: list[LoRALinear]
    ) -> None: ...
    def __call__(self, x):  # -> array:
        ...
