import torch
from .types import LayerTensors

__all__ = ["get_layer_tensors", "get_layer_params_buffers", "get_layer_size"]

def get_layer_tensors(layer: torch.nn.Module) -> dict[str, torch.Tensor]: ...
def get_layer_params_buffers(layer: torch.nn.Module) -> LayerTensors: ...
def get_layer_size(layer: torch.nn.Module) -> int: ...
