from dataclasses import dataclass
from openai_harmony import Message as HarmonyMessage
from typing import Final
from vllm.entrypoints.mcp.tool_server import ToolServer as ToolServer
from vllm.entrypoints.openai.responses.context import (
    StreamingHarmonyContext as StreamingHarmonyContext,
)
from vllm.entrypoints.openai.responses.protocol import (
    ResponseReasoningPartAddedEvent as ResponseReasoningPartAddedEvent,
    ResponseReasoningPartDoneEvent as ResponseReasoningPartDoneEvent,
    StreamingResponsesResponse as StreamingResponsesResponse,
)
from vllm.utils import random_uuid as random_uuid

TOOL_NAME_TO_MCP_SERVER_LABEL: Final[dict[str, str]]

@dataclass
class StreamingState:
    current_content_index: int = ...
    current_output_index: int = ...
    current_item_id: str = ...
    current_call_id: str = ...
    sent_output_item_added: bool = ...
    is_first_function_call_delta: bool = ...
    def reset_for_new_item(self) -> None: ...

def is_mcp_tool_by_namespace(recipient: str | None) -> bool: ...
def emit_text_delta_events(
    delta: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_reasoning_delta_events(
    delta: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_function_call_delta_events(
    delta: str, function_name: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_mcp_delta_events(
    delta: str, state: StreamingState, recipient: str
) -> list[StreamingResponsesResponse]: ...
def emit_code_interpreter_delta_events(
    delta: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_text_output_done_events(
    text: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_reasoning_done_events(
    text: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_function_call_done_events(
    function_name: str, arguments: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_mcp_completion_events(
    recipient: str, arguments: str, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_content_delta_events(
    ctx: StreamingHarmonyContext, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_previous_item_done_events(
    previous_item: HarmonyMessage, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_browser_tool_events(
    previous_item: HarmonyMessage, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_code_interpreter_completion_events(
    previous_item: HarmonyMessage, state: StreamingState
) -> list[StreamingResponsesResponse]: ...
def emit_tool_action_events(
    ctx: StreamingHarmonyContext, state: StreamingState, tool_server: ToolServer | None
) -> list[StreamingResponsesResponse]: ...
