"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenAttention(nn.Module):
    def __init__(
        self,
        hidden_size: int,
        num_attention_heads: int,
        num_key_value_heads: int = ...,
        max_position_embeddings: int = ...,
        rope_theta: float = ...,
        rope_scaling: dict = ...,
    ) -> None: ...
    def __call__(
        self,
        hidden_states: mx.array,
        attention_mask: mx.array | None = ...,
        position_embeddings: tuple[mx.array, mx.array] | None = ...,
    ) -> mx.array: ...
