"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

"""
This type stub file was generated by pyright.
"""

class QwenTextEncoder(nn.Module):
    def __init__(self) -> None: ...
    def __call__(
        self, input_ids: mx.array, attention_mask: mx.array
    ) -> tuple[mx.array, mx.array]: ...
