"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class PatchMerger(nn.Module):
    def __init__(self, context_dim: int, hidden_size: int, spatial_merge_size: int = ...) -> None:
        ...
    
    def __call__(self, x: mx.array, grid_thw: mx.array) -> mx.array:
        ...
    


