"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class VisionRotaryEmbedding(nn.Module):
    def __init__(self, dim: int, theta: float = ...) -> None: ...
    def __call__(self, max_grid_size: int) -> mx.array: ...
