"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class VisionAttention(nn.Module):
    def __init__(self, embed_dim: int = ..., num_heads: int = ...) -> None: ...
    def __call__(
        self, x: mx.array, position_embeddings=..., cu_seqlens=...
    ) -> mx.array: ...
