from collections.abc import Sequence

from tinygrad.dtype import DType

class Tensor:
    shape: tuple[int, ...]
    dtype: DType

    def __init__(
        self,
        data: object,
        device: str | None = None,
        dtype: DType | None = None,
        requires_grad: bool | None = None,
    ) -> None: ...
    def realize(self) -> Tensor: ...
    def numpy(self) -> _HostArray: ...
    def to(self, device: str | None) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    def permute(self, *order: int) -> Tensor: ...
    def transpose(self, dim0: int = 1, dim1: int = 0) -> Tensor: ...
    def expand(self, *shape: int) -> Tensor: ...
    def shrink(self, arg: tuple[tuple[int, int] | None, ...]) -> Tensor: ...
    def matmul(self, other: Tensor) -> Tensor: ...
    def mean(self, axis: int, keepdim: bool = False) -> Tensor: ...
    def square(self) -> Tensor: ...
    def rsqrt(self) -> Tensor: ...
    def softmax(self, axis: int) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def silu(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def reciprocal(self) -> Tensor: ...
    def pow(self, exponent: Tensor | float) -> Tensor: ...
    def float(self) -> Tensor: ...
    def cast(self, dtype: DType) -> Tensor: ...
    def bitcast(self, dtype: DType) -> Tensor: ...
    def cat(self, *tensors: Tensor, dim: int = 0) -> Tensor: ...
    def where(self, true_value: Tensor | float, false_value: Tensor | float) -> Tensor: ...
    @property
    def nbytes(self) -> int: ...
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: Tensor | float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: Tensor | float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __pow__(self, other: Tensor | float) -> Tensor: ...
    def __gt__(self, other: Tensor | float) -> Tensor: ...
    def __lt__(self, other: Tensor | float) -> Tensor: ...
    def __ge__(self, other: Tensor | float) -> Tensor: ...
    def __le__(self, other: Tensor | float) -> Tensor: ...
    def __and__(self, other: Tensor) -> Tensor: ...
    def __getitem__(self, index: Tensor | tuple[object, ...] | slice) -> Tensor: ...
    @staticmethod
    def arange(
        start: int,
        stop: int | None = None,
        step: int = 1,
        dtype: DType | None = None,
    ) -> Tensor: ...
    @staticmethod
    def full(
        shape: tuple[int, ...],
        fill_value: float,
        dtype: DType | None = None,
        device: str | None = None,
    ) -> Tensor: ...
    @staticmethod
    def randn(*shape: int, dtype: DType | None = None) -> Tensor: ...


class _HostArray:
    shape: tuple[int, ...]

    def tobytes(self) -> bytes: ...
    def reshape(self, shape: Sequence[int]) -> _HostArray: ...
