import abc
from abc import ABC, abstractmethod
from collections import deque
from collections.abc import Iterable, Iterator
from enum import Enum
from vllm.v1.request import Request as Request

class SchedulingPolicy(Enum):
    FCFS = "fcfs"
    PRIORITY = "priority"

class RequestQueue(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def add_request(self, request: Request) -> None: ...
    @abstractmethod
    def pop_request(self) -> Request: ...
    @abstractmethod
    def peek_request(self) -> Request: ...
    @abstractmethod
    def prepend_request(self, request: Request) -> None: ...
    @abstractmethod
    def prepend_requests(self, requests: RequestQueue) -> None: ...
    @abstractmethod
    def remove_request(self, request: Request) -> None: ...
    @abstractmethod
    def remove_requests(self, requests: Iterable[Request]) -> None: ...
    @abstractmethod
    def __bool__(self) -> bool: ...
    @abstractmethod
    def __len__(self) -> int: ...
    @abstractmethod
    def __iter__(self) -> Iterator[Request]: ...

class FCFSRequestQueue(deque[Request], RequestQueue):
    def add_request(self, request: Request) -> None: ...
    def pop_request(self) -> Request: ...
    def peek_request(self) -> Request: ...
    def prepend_request(self, request: Request) -> None: ...
    def prepend_requests(self, requests: RequestQueue) -> None: ...
    def remove_request(self, request: Request) -> None: ...
    def remove_requests(self, requests: Iterable[Request]) -> None: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Request]: ...

class PriorityRequestQueue(RequestQueue):
    def __init__(self) -> None: ...
    def add_request(self, request: Request) -> None: ...
    def pop_request(self) -> Request: ...
    def peek_request(self) -> Request: ...
    def prepend_request(self, request: Request) -> None: ...
    def prepend_requests(self, requests: RequestQueue) -> None: ...
    def remove_request(self, request: Request) -> None: ...
    def remove_requests(self, requests: Iterable[Request]) -> None: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Request]: ...

def create_request_queue(policy: SchedulingPolicy) -> RequestQueue: ...
