from dataclasses import dataclass

@dataclass
class EngineArgs:
    model: str = ...
    served_model_name: str | list[str] | None = ...
    tokenizer: str | None = ...
    trust_remote_code: bool = ...
    dtype: str = ...
    seed: int = ...
    max_model_len: int | None = ...
    gpu_memory_utilization: float = ...
    enforce_eager: bool = ...
    tensor_parallel_size: int = ...
    pipeline_parallel_size: int = ...
    quantization: str | None = ...
    load_format: str = ...
    enable_sleep_mode: bool = ...
