import argparse
import torch
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from dataclasses import dataclass
from typing import Any, TypeAlias, TypeVar
from typing_extensions import TypeIs
from vllm.config import (
    AttentionConfig as AttentionConfig,
    CacheConfig as CacheConfig,
    CompilationConfig as CompilationConfig,
    ConfigType as ConfigType,
    DeviceConfig as DeviceConfig,
    ECTransferConfig as ECTransferConfig,
    EPLBConfig as EPLBConfig,
    KVEventsConfig as KVEventsConfig,
    KVTransferConfig as KVTransferConfig,
    KernelConfig as KernelConfig,
    LoRAConfig as LoRAConfig,
    LoadConfig as LoadConfig,
    ModelConfig as ModelConfig,
    MultiModalConfig as MultiModalConfig,
    ObservabilityConfig as ObservabilityConfig,
    OffloadConfig as OffloadConfig,
    ParallelConfig as ParallelConfig,
    PoolerConfig as PoolerConfig,
    PrefetchOffloadConfig as PrefetchOffloadConfig,
    ProfilerConfig as ProfilerConfig,
    SchedulerConfig as SchedulerConfig,
    SpeculativeConfig as SpeculativeConfig,
    StructuredOutputsConfig as StructuredOutputsConfig,
    UVAOffloadConfig as UVAOffloadConfig,
    VllmConfig as VllmConfig,
    WeightTransferConfig as WeightTransferConfig,
    get_attr_docs as get_attr_docs,
)
from vllm.config.cache import (
    CacheDType as CacheDType,
    KVOffloadingBackend as KVOffloadingBackend,
    MambaCacheMode as MambaCacheMode,
    MambaDType as MambaDType,
    PrefixCachingHashAlgo as PrefixCachingHashAlgo,
)
from vllm.config.device import Device as Device
from vllm.config.kernel import MoEBackend as MoEBackend
from vllm.config.lora import MaxLoRARanks as MaxLoRARanks
from vllm.config.model import (
    ConvertOption as ConvertOption,
    HfOverrides as HfOverrides,
    LogprobsMode as LogprobsMode,
    ModelDType as ModelDType,
    RunnerOption as RunnerOption,
    TokenizerMode as TokenizerMode,
)
from vllm.config.multimodal import (
    MMCacheType as MMCacheType,
    MMEncoderTPMode as MMEncoderTPMode,
)
from vllm.config.observability import DetailedTraceModules as DetailedTraceModules
from vllm.config.parallel import (
    All2AllBackend as All2AllBackend,
    DCPCommBackend as DCPCommBackend,
    DataParallelBackend as DataParallelBackend,
    DistributedExecutorBackend as DistributedExecutorBackend,
    ExpertPlacementStrategy as ExpertPlacementStrategy,
)
from vllm.config.scheduler import SchedulerPolicy as SchedulerPolicy
from vllm.config.utils import get_field as get_field
from vllm.config.vllm import (
    OptimizationLevel as OptimizationLevel,
    PerformanceMode as PerformanceMode,
)
from vllm.logger import init_logger as init_logger, suppress_logging as suppress_logging
from vllm.model_executor.layers.quantization import (
    QuantizationMethods as QuantizationMethods,
)
from vllm.model_executor.model_loader import LoadFormats as LoadFormats
from vllm.platforms import (
    CpuArchEnum as CpuArchEnum,
    current_platform as current_platform,
)
from vllm.plugins import load_general_plugins as load_general_plugins
from vllm.ray.lazy_utils import (
    is_in_ray_actor as is_in_ray_actor,
    is_ray_initialized as is_ray_initialized,
)
from vllm.transformers_utils.config import (
    is_interleaved as is_interleaved,
    maybe_override_with_speculators as maybe_override_with_speculators,
)
from vllm.transformers_utils.gguf_utils import is_gguf as is_gguf
from vllm.transformers_utils.repo_utils import get_model_path as get_model_path
from vllm.transformers_utils.utils import is_cloud_storage as is_cloud_storage
from vllm.usage.usage_lib import UsageContext as UsageContext
from vllm.utils.argparse_utils import FlexibleArgumentParser as FlexibleArgumentParser
from vllm.utils.mem_constants import GiB_bytes as GiB_bytes
from vllm.utils.network_utils import get_ip as get_ip
from vllm.utils.torch_utils import (
    resolve_kv_cache_dtype_string as resolve_kv_cache_dtype_string,
)
from vllm.v1.attention.backends.registry import (
    AttentionBackendEnum as AttentionBackendEnum,
)
from vllm.v1.executor import Executor as Executor
from vllm.v1.sample.logits_processor import LogitsProcessor as LogitsProcessor

logger: Incomplete
T = TypeVar("T")
TypeHint: TypeAlias = type[Any] | object
TypeHintT: TypeAlias = type[T] | object

def parse_type(return_type: Callable[[str], T]) -> Callable[[str], T]: ...
def optional_type(return_type: Callable[[str], T]) -> Callable[[str], T | None]: ...
def union_dict_and_str(val: str) -> str | dict[str, str] | None: ...
def is_type(type_hint: TypeHint, type: TypeHintT) -> TypeIs[TypeHintT]: ...
def contains_type(type_hints: set[TypeHint], type: TypeHintT) -> bool: ...
def get_type(type_hints: set[TypeHint], type: TypeHintT) -> TypeHintT: ...
def literal_to_kwargs(type_hints: set[TypeHint]) -> dict[str, Any]: ...
def collection_to_kwargs(
    type_hints: set[TypeHint], type: TypeHint
) -> dict[str, Any]: ...
def is_not_builtin(type_hint: TypeHint) -> bool: ...
def get_type_hints(type_hint: TypeHint) -> set[TypeHint]: ...

NEEDS_HELP: Incomplete

def get_kwargs(cls) -> dict[str, dict[str, Any]]: ...
@dataclass
class EngineArgs:
    model: str = ...
    enable_return_routed_experts: bool = ...
    model_weights: str = ...
    served_model_name: str | list[str] | None = ...
    tokenizer: str | None = ...
    hf_config_path: str | None = ...
    runner: RunnerOption = ...
    convert: ConvertOption = ...
    skip_tokenizer_init: bool = ...
    enable_prompt_embeds: bool = ...
    tokenizer_mode: TokenizerMode | str = ...
    trust_remote_code: bool = ...
    allowed_local_media_path: str = ...
    allowed_media_domains: list[str] | None = ...
    download_dir: str | None = ...
    safetensors_load_strategy: str = ...
    load_format: str | LoadFormats = ...
    config_format: str = ...
    dtype: ModelDType = ...
    kv_cache_dtype: CacheDType = ...
    seed: int = ...
    max_model_len: int = ...
    cudagraph_capture_sizes: list[int] | None = ...
    max_cudagraph_capture_size: int | None = ...
    distributed_executor_backend: (
        str | DistributedExecutorBackend | type[Executor] | None
    ) = ...
    pipeline_parallel_size: int = ...
    master_addr: str = ...
    master_port: int = ...
    nnodes: int = ...
    node_rank: int = ...
    distributed_timeout_seconds: int | None = ...
    tensor_parallel_size: int = ...
    prefill_context_parallel_size: int = ...
    decode_context_parallel_size: int = ...
    dcp_comm_backend: DCPCommBackend = ...
    dcp_kv_cache_interleave_size: int = ...
    cp_kv_cache_interleave_size: int = ...
    data_parallel_size: int = ...
    data_parallel_rank: int | None = ...
    data_parallel_start_rank: int | None = ...
    data_parallel_size_local: int | None = ...
    data_parallel_address: str | None = ...
    data_parallel_rpc_port: int | None = ...
    data_parallel_hybrid_lb: bool = ...
    data_parallel_external_lb: bool = ...
    data_parallel_backend: DataParallelBackend = ...
    enable_expert_parallel: bool = ...
    moe_backend: MoEBackend = ...
    all2all_backend: All2AllBackend = ...
    enable_elastic_ep: bool = ...
    enable_dbo: bool = ...
    ubatch_size: int = ...
    dbo_decode_token_threshold: int = ...
    dbo_prefill_token_threshold: int = ...
    disable_nccl_for_dp_synchronization: bool | None = ...
    eplb_config: EPLBConfig = ...
    enable_eplb: bool = ...
    expert_placement_strategy: ExpertPlacementStrategy = ...
    max_parallel_loading_workers: int | None = ...
    block_size: int | None = ...
    enable_prefix_caching: bool | None = ...
    prefix_caching_hash_algo: PrefixCachingHashAlgo = ...
    disable_sliding_window: bool = ...
    disable_cascade_attn: bool = ...
    offload_backend: str = ...
    cpu_offload_gb: float = ...
    cpu_offload_params: set[str] = ...
    offload_group_size: int = ...
    offload_num_in_group: int = ...
    offload_prefetch_step: int = ...
    offload_params: set[str] = ...
    gpu_memory_utilization: float = ...
    kv_cache_memory_bytes: int | None = ...
    max_num_batched_tokens: int | None = ...
    max_num_partial_prefills: int = ...
    max_long_partial_prefills: int = ...
    long_prefill_token_threshold: int = ...
    max_num_seqs: int | None = ...
    max_logprobs: int = ...
    logprobs_mode: LogprobsMode = ...
    disable_log_stats: bool = ...
    aggregate_engine_logging: bool = ...
    revision: str | None = ...
    code_revision: str | None = ...
    hf_token: bool | str | None = ...
    hf_overrides: HfOverrides = ...
    tokenizer_revision: str | None = ...
    quantization: QuantizationMethods | str | None = ...
    allow_deprecated_quantization: bool = ...
    enforce_eager: bool = ...
    disable_custom_all_reduce: bool = ...
    language_model_only: bool = ...
    limit_mm_per_prompt: dict[str, int | dict[str, int]] = ...
    enable_mm_embeds: bool = ...
    interleave_mm_strings: bool = ...
    media_io_kwargs: dict[str, dict[str, Any]] = ...
    mm_processor_kwargs: dict[str, Any] | None = ...
    mm_processor_cache_gb: float = ...
    mm_processor_cache_type: MMCacheType | None = ...
    mm_shm_cache_max_object_size_mb: int = ...
    mm_encoder_only: bool = ...
    mm_encoder_tp_mode: MMEncoderTPMode = ...
    mm_encoder_attn_backend: AttentionBackendEnum | str | None = ...
    io_processor_plugin: str | None = ...
    skip_mm_profiling: bool = ...
    video_pruning_rate: float | None = ...
    enable_lora: bool = ...
    max_loras: int = ...
    max_lora_rank: MaxLoRARanks = ...
    default_mm_loras: dict[str, str] | None = ...
    fully_sharded_loras: bool = ...
    max_cpu_loras: int | None = ...
    lora_dtype: str | torch.dtype | None = ...
    enable_tower_connector_lora: bool = ...
    specialize_active_lora: bool = ...
    ray_workers_use_nsight: bool = ...
    num_gpu_blocks_override: int | None = ...
    model_loader_extra_config: dict = ...
    ignore_patterns: str | list[str] = ...
    enable_chunked_prefill: bool | None = ...
    disable_chunked_mm_input: bool = ...
    disable_hybrid_kv_cache_manager: bool | None = ...
    structured_outputs_config: StructuredOutputsConfig = ...
    reasoning_parser: str = ...
    reasoning_parser_plugin: str | None = ...
    speculative_config: dict[str, Any] | None = ...
    show_hidden_metrics_for_version: str | None = ...
    otlp_traces_endpoint: str | None = ...
    collect_detailed_traces: list[DetailedTraceModules] | None = ...
    kv_cache_metrics: bool = ...
    kv_cache_metrics_sample: float = ...
    cudagraph_metrics: bool = ...
    enable_layerwise_nvtx_tracing: bool = ...
    enable_mfu_metrics: bool = ...
    enable_logging_iteration_details: bool = ...
    enable_mm_processor_stats: bool = ...
    scheduling_policy: SchedulerPolicy = ...
    scheduler_cls: str | type[object] | None = ...
    pooler_config: PoolerConfig | None = ...
    compilation_config: CompilationConfig = ...
    attention_config: AttentionConfig = ...
    kernel_config: KernelConfig = ...
    enable_flashinfer_autotune: bool = ...
    worker_cls: str = ...
    worker_extension_cls: str = ...
    profiler_config: ProfilerConfig = ...
    kv_transfer_config: KVTransferConfig | None = ...
    kv_events_config: KVEventsConfig | None = ...
    ec_transfer_config: ECTransferConfig | None = ...
    generation_config: str = ...
    enable_sleep_mode: bool = ...
    override_generation_config: dict[str, Any] = ...
    model_impl: str = ...
    override_attention_dtype: str | None = ...
    attention_backend: AttentionBackendEnum | None = ...
    calculate_kv_scales: bool = ...
    mamba_cache_dtype: MambaDType = ...
    mamba_ssm_cache_dtype: MambaDType = ...
    mamba_block_size: int | None = ...
    mamba_cache_mode: MambaCacheMode = ...
    additional_config: dict[str, Any] = ...
    use_tqdm_on_load: bool = ...
    pt_load_map_location: str | dict[str, str] = ...
    logits_processors: list[str | type[LogitsProcessor]] | None = ...
    async_scheduling: bool | None = ...
    stream_interval: int = ...
    kv_sharing_fast_prefill: bool = ...
    optimization_level: OptimizationLevel = ...
    performance_mode: PerformanceMode = ...
    kv_offloading_size: float | None = ...
    kv_offloading_backend: KVOffloadingBackend = ...
    tokens_only: bool = ...
    weight_transfer_config: WeightTransferConfig | None = ...
    fail_on_environ_validation: bool = ...
    def __post_init__(self) -> None: ...
    @staticmethod
    def add_cli_args(parser: FlexibleArgumentParser) -> FlexibleArgumentParser: ...
    @classmethod
    def from_cli_args(cls, args: argparse.Namespace): ...
    def create_model_config(self) -> ModelConfig: ...
    def validate_tensorizer_args(self) -> None: ...
    def create_load_config(self) -> LoadConfig: ...
    def create_speculative_config(
        self, target_model_config: ModelConfig, target_parallel_config: ParallelConfig
    ) -> SpeculativeConfig | None: ...
    def create_engine_config(
        self, usage_context: UsageContext | None = None, headless: bool = False
    ) -> VllmConfig: ...
    @classmethod
    def get_batch_defaults(
        cls, world_size: int
    ) -> tuple[dict[UsageContext | None, int], dict[UsageContext | None, int]]: ...

@dataclass
class AsyncEngineArgs(EngineArgs):
    enable_log_requests: bool = ...
    @staticmethod
    def add_cli_args(
        parser: FlexibleArgumentParser, async_args_only: bool = False
    ) -> FlexibleArgumentParser: ...

def human_readable_int(value: str) -> int: ...
def human_readable_int_or_auto(value: str) -> int: ...
