# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing

_T = typing.TypeVar("_T")

class _CallableGetter(typing.Protocol[_T]):
    def __call__(self) -> _T: ...

__all__ = [
    "CliArgs",
    "ConfigArgs",
    "DeprecatedArgs",
    "ExoHome",
    "FromSwarm",
    "LocatorArgs",
    "LocatorConfig",
    "LogFiles",
    "ModelsDirs",
    "NetworkingHandle",
    "Pidfile",
    "PidfileError",
    "Verbosity",
]

@typing.final
class CliArgs:
    @property
    def verbosity(self) -> Verbosity: ...
    @verbosity.setter
    def verbosity(self, value: Verbosity) -> None: ...
    @property
    def force_master(self) -> builtins.bool: ...
    @force_master.setter
    def force_master(self, value: builtins.bool) -> None: ...
    @property
    def api_enabled(self) -> builtins.bool: ...
    @api_enabled.setter
    def api_enabled(self, value: builtins.bool) -> None: ...
    @property
    def api_port(self) -> builtins.int: ...
    @api_port.setter
    def api_port(self, value: builtins.int) -> None: ...
    @property
    def worker_enabled(self) -> builtins.bool: ...
    @worker_enabled.setter
    def worker_enabled(self, value: builtins.bool) -> None: ...
    @property
    def downloads_enabled(self) -> builtins.bool: ...
    @downloads_enabled.setter
    def downloads_enabled(self, value: builtins.bool) -> None: ...
    @property
    def offline(self) -> builtins.bool: ...
    @offline.setter
    def offline(self, value: builtins.bool) -> None: ...
    @property
    def continuous_batching_enabled(self) -> builtins.bool: ...
    @continuous_batching_enabled.setter
    def continuous_batching_enabled(self, value: builtins.bool) -> None: ...
    @property
    def legacy_daemon(self) -> builtins.bool: ...
    @legacy_daemon.setter
    def legacy_daemon(self, value: builtins.bool) -> None: ...
    @property
    def bootstrap_peers(self) -> typing.Optional[builtins.list[builtins.str]]: ...
    @bootstrap_peers.setter
    def bootstrap_peers(self, value: typing.Optional[typing.Sequence[builtins.str]]) -> None: ...
    @property
    def namespace(self) -> builtins.str: ...
    @namespace.setter
    def namespace(self, value: builtins.str) -> None: ...
    @property
    def zenoh_port(self) -> builtins.int: ...
    @zenoh_port.setter
    def zenoh_port(self, value: builtins.int) -> None: ...
    @property
    def discovery_port(self) -> builtins.int: ...
    @discovery_port.setter
    def discovery_port(self, value: builtins.int) -> None: ...
    @property
    def fast_synch(self) -> typing.Optional[builtins.bool]: ...
    @fast_synch.setter
    def fast_synch(self, value: typing.Optional[builtins.bool]) -> None: ...
    @property
    def locator(self) -> _CallableGetter[LocatorArgs]: ...
    @locator.setter
    def locator(self, value: LocatorArgs) -> None: ...
    @property
    def config(self) -> _CallableGetter[ConfigArgs]: ...
    @config.setter
    def config(self, value: ConfigArgs) -> None: ...
    @property
    def deprecated(self) -> _CallableGetter[DeprecatedArgs]: ...
    @deprecated.setter
    def deprecated(self, value: DeprecatedArgs) -> None: ...
    @staticmethod
    def from_env_only() -> CliArgs:
        r"""
        Create only from env-variables
        """
    @staticmethod
    def parse_from(argv: typing.Sequence[builtins.str]) -> CliArgs: ...
    @staticmethod
    def parse() -> CliArgs: ...
    def to_bytes(self) -> builtins.list[builtins.int]: ...
    @staticmethod
    def from_bytes(bytes: typing.Sequence[builtins.int]) -> CliArgs: ...
    def __reduce__(self) -> tuple[typing.Any, tuple]: ...

@typing.final
class ConfigArgs:
    r"""
    Arguments that will end up in the final configuration go here.
    
    The precedence of the final configuration object will be:
     - Defaults < Config file < Env < Cli args
    
    # Important
     - Make sure all are [`Option<T>`] so we can make it combinable with other
       sources of configuration
    """
    ...

@typing.final
class DeprecatedArgs:
    r"""
    Deprecated arguments go here.
    
    # Important
     - Make sure all are `hide = true` so it won't appear in `--help`
     - Make sure all are [`Option<T>`] so them being missing doesn't cause issues
     - Edit [`Self::get_error`] to handle changes of new/removed args in here
    """
    @property
    def libp2p_port(self) -> typing.Optional[builtins.int]: ...
    @libp2p_port.setter
    def libp2p_port(self, value: typing.Optional[builtins.int]) -> None: ...

@typing.final
class ExoHome:
    @property
    def config(self) -> pathlib.Path: ...
    @config.setter
    def config(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def data(self) -> pathlib.Path: ...
    @data.setter
    def data(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def cache(self) -> pathlib.Path: ...
    @cache.setter
    def cache(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...

class FromSwarm:
    @typing.final
    class Connection(FromSwarm):
        __match_args__ = ("connected",)
        @property
        def connected(self) -> builtins.bool: ...
        def __new__(cls, connected: builtins.bool) -> FromSwarm.Connection: ...
    
    @typing.final
    class Message(FromSwarm):
        __match_args__ = ("topic", "data",)
        @property
        def topic(self) -> builtins.str: ...
        @property
        def data(self) -> bytes: ...
        def __new__(cls, topic: builtins.str, data: bytes) -> FromSwarm.Message: ...
    
    ...

@typing.final
class LocatorArgs:
    r"""
    Arguments that are needed to resolve paths to files go here.
    
    This is needed for such things as resolving the path of the configuration `.toml` file,
    therefore any args here cannot be specified by the configuration `.toml` file.
    
    By default, any path-like argument goes here, but can be moved to [`ConfigArgs`] if needed.
    """
    @property
    def exo_home(self) -> typing.Optional[pathlib.Path]: ...
    @exo_home.setter
    def exo_home(self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> None: ...
    @property
    def default_models_dir(self) -> typing.Optional[pathlib.Path]: ...
    @default_models_dir.setter
    def default_models_dir(self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> None: ...
    @property
    def models_read_only_dirs(self) -> typing.Optional[builtins.list[pathlib.Path]]: ...
    @models_read_only_dirs.setter
    def models_read_only_dirs(self, value: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]]) -> None: ...
    @property
    def models_dirs(self) -> typing.Optional[builtins.list[pathlib.Path]]: ...
    @models_dirs.setter
    def models_dirs(self, value: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]]) -> None: ...
    @property
    def config_file(self) -> typing.Optional[pathlib.Path]: ...
    @config_file.setter
    def config_file(self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> None: ...

@typing.final
class LocatorConfig:
    @property
    def exo_home(self) -> _CallableGetter[ExoHome]: ...
    @exo_home.setter
    def exo_home(self, value: ExoHome) -> None: ...
    @property
    def models_dirs(self) -> _CallableGetter[ModelsDirs]: ...
    @models_dirs.setter
    def models_dirs(self, value: ModelsDirs) -> None: ...
    @property
    def log_files(self) -> _CallableGetter[LogFiles]: ...
    @log_files.setter
    def log_files(self, value: LogFiles) -> None: ...
    @property
    def pid_file(self) -> pathlib.Path: ...
    @pid_file.setter
    def pid_file(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def node_zid(self) -> pathlib.Path: ...
    @node_zid.setter
    def node_zid(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def config_file(self) -> pathlib.Path: ...
    @config_file.setter
    def config_file(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def custom_model_cards_dir(self) -> pathlib.Path: ...
    @custom_model_cards_dir.setter
    def custom_model_cards_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def event_log_dir(self) -> pathlib.Path: ...
    @event_log_dir.setter
    def event_log_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def image_cache_dir(self) -> pathlib.Path: ...
    @image_cache_dir.setter
    def image_cache_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def tracing_cache_dir(self) -> pathlib.Path: ...
    @tracing_cache_dir.setter
    def tracing_cache_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @staticmethod
    def default() -> LocatorConfig:
        r"""
        Create default instance
        """
    @staticmethod
    def from_env_only() -> LocatorConfig:
        r"""
        Create only from env-variables
        """
    @staticmethod
    def resolve(args: LocatorArgs) -> LocatorConfig: ...

@typing.final
class LogFiles:
    @property
    def exo_log_dir(self) -> pathlib.Path: ...
    @exo_log_dir.setter
    def exo_log_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def exo_log(self) -> pathlib.Path: ...
    @exo_log.setter
    def exo_log(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def exo_runner_log_dir(self) -> pathlib.Path: ...
    @exo_runner_log_dir.setter
    def exo_runner_log_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def exo_runner_stdout_log(self) -> pathlib.Path: ...
    @exo_runner_stdout_log.setter
    def exo_runner_stdout_log(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def exo_runner_stderr_log(self) -> pathlib.Path: ...
    @exo_runner_stderr_log.setter
    def exo_runner_stderr_log(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...

@typing.final
class ModelsDirs:
    @property
    def default_models_dir(self) -> pathlib.Path: ...
    @default_models_dir.setter
    def default_models_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def models_read_only_dirs(self) -> builtins.list[pathlib.Path]: ...
    @models_read_only_dirs.setter
    def models_read_only_dirs(self, value: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> None: ...
    @property
    def models_dirs(self) -> builtins.list[pathlib.Path]: ...
    @models_dirs.setter
    def models_dirs(self, value: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> None: ...

@typing.final
class NetworkingHandle:
    @staticmethod
    def new(identity: builtins.str, namespace: builtins.str, listen_port: builtins.int, discovery_service_port: builtins.int) -> NetworkingHandle: ...
    async def recv(self) -> FromSwarm: ...
    async def gossipsub_subscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Subscribe to a `GossipSub` topic.
        
        Returns `True` if the subscription worked. Returns `False` if we were already subscribed.
        """
    async def gossipsub_unsubscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Unsubscribes from a `GossipSub` topic.
        
        Returns `True` if we were subscribed to this topic. Returns `False` if we were not subscribed.
        """
    async def gossipsub_publish(self, topic: builtins.str, data: bytes) -> None:
        r"""
        Publishes a message with multiple topics to the `GossipSub` network.
        
        If no peers are found that subscribe to this topic, throws `NoPeersSubscribedToTopicError` exception.
        """

@typing.final
class Pidfile:
    r"""
    A PID file protected with a lock.
    
    An instance of `Pidfile` can be used to manage a PID file: create it,
    lock it, detect already running daemons. It is backed by [`pidfile`]
    functions of `libbsd`/`libutil` which use `flopen` to lock the PID
    file.
    
    When a PID file is created, the process ID of the current process is
    *not* written there, making it possible to lock the PID file before
    forking and only write the ID of the forked process when it is ready.
    
    The PID file is deleted automatically when the `Pidfile` comes out of
    the scope. To close the PID file without deleting it, for example, in
    the parent process of a forked daemon, call `close()`.
    
    [`exit`]: https://doc.rust-lang.org/std/process/fn.exit.html
    [`pidfile`]: https://linux.die.net/man/3/pidfile
    [`daemon`(3)]: https://linux.die.net/man/3/daemon
    """
    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path, mode: builtins.int) -> Pidfile:
        r"""
        Creates a new PID file and locks it.
        
        If the PID file cannot be locked, returns `PidfileError::AlreadyRunning` with
        a PID of the already running process, or `None` if no PID has been written to
        the PID file yet.
        """
    def write(self) -> None:
        r"""
        Writes the current process ID to the PID file.
        
        The file is truncated before writing.
        """
    def as_raw_fd(self) -> builtins.int:
        r"""
        Extracts the raw file descriptor.
        
        This function is typically used to **borrow** an owned file descriptor.
        When used in this way, this method does **not** pass ownership of the
        raw file descriptor to the caller, and the file descriptor is only
        guaranteed to be valid while the original object has not yet been
        destroyed.
        """
    def close(self) -> None:
        r"""
        Closes the PID file and releases associated resources.
        """

@typing.final
class PidfileError(builtins.Exception):
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Verbosity(enum.Enum):
    Off = ...
    Error = ...
    Warn = ...
    Info = ...
    Debug = ...
    Trace = ...
