import torch
from collections.abc import Iterable, Mapping
from typing import Any

def deep_compare(dict1: Any, dict2: Any) -> bool: ...
def should_ignore_layer(
    layer_name: str | None,
    ignore: Iterable[str],
    fused_mapping: Mapping[str, list[str]] = ...,
) -> bool: ...
def check_equal_or_regex_match(layer_name: str, targets: Iterable[str]) -> bool: ...
def quark_quantize_weight_to_mxfp4(w: torch.Tensor): ...
