"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class CLIPTextModel(nn.Module):
    def __init__(self, dims: int, num_encoder_layers: int) -> None:
        ...
    
    def __call__(self, tokens: mx.array) -> tuple[mx.array, mx.array]:
        ...
    
    @staticmethod
    def create_causal_attention_mask(input_shape: tuple) -> mx.array:
        ...
    


