"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mflux.models.common.tokenizer import Tokenizer
from mflux.models.qwen.model.qwen_text_encoder.qwen_text_encoder import QwenTextEncoder

"""
This type stub file was generated by pyright.
"""

class QwenPromptEncoder:
    @staticmethod
    def encode_prompt(
        prompt: str,
        negative_prompt: str,
        prompt_cache: dict[str, tuple[mx.array, mx.array, mx.array, mx.array]],
        qwen_tokenizer: Tokenizer,
        qwen_text_encoder: QwenTextEncoder,
    ) -> tuple[mx.array, mx.array, mx.array, mx.array]: ...
