"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenRMSNorm(nn.Module):
    def __init__(self, hidden_size: int, eps: float = ...) -> None: ...
    def __call__(self, hidden_states: mx.array) -> mx.array: ...
