from typing import Any

TOOLS_SYSTEM_TEMPLATE: str
bos_token: str
eos_token: str
thinking_start_token: str
thinking_end_token: str
dsml_token: str
system_msg_template: str
user_msg_template: str
assistant_msg_template: str
thinking_template: str
response_format_template: str
tool_call_template: str
tool_calls_template: str
tool_output_template: str

def to_json(value: Any) -> str: ...
def tools_from_openai_format(tools): ...
def tool_calls_from_openai_format(tool_calls): ...
def tool_calls_to_openai_format(tool_calls): ...
def encode_arguments_to_dsml(tool_call: dict[str, str]) -> str: ...
def decode_dsml_to_arguments(
    tool_name: str, tool_args: dict[str, tuple[str, str]]
) -> dict[str, str]: ...
def render_tools(tools: list[dict[str, str | dict[str, Any]]]) -> str: ...
def find_last_user_index(messages: list[dict[str, Any]]) -> int: ...
def render_message(
    index: int, messages: list[dict[str, Any]], thinking_mode: str
) -> str: ...
def drop_thinking_messages(
    messages: list[dict[str, Any]], last_user_idx: int | None = None
) -> list[dict[str, Any]]: ...
def encode_messages(
    messages: list[dict[str, Any]],
    thinking_mode: str,
    context: list[dict[str, Any]] | None = None,
    drop_thinking: bool = True,
    add_default_bos_token: bool = True,
) -> str: ...
def parse_tool_calls(index: int, text: str): ...
def parse_message_from_completion_text(text: str, thinking_mode: str): ...
