from typing import Protocol

class TokenizerLike(Protocol):
    @property
    def eos_token_id(self) -> int: ...
    @property
    def vocab_size(self) -> int: ...
    def encode(self, text: str, add_special_tokens: bool = ...) -> list[int]: ...
    def decode(self, ids: list[int] | int, skip_special_tokens: bool = ...) -> str: ...
    def apply_chat_template(
        self,
        messages: list[dict[str, str]],
        tools: list[dict[str, object]] | None = ...,
        **kwargs: object,
    ) -> str | list[int]: ...
