# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

@typing.final
class StateProxy:
    @staticmethod
    async def init() -> StateProxy: ...
    async def snapshot(self) -> str: ...

