import abc
import prometheus_client
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from collections.abc import Iterable
from dataclasses import dataclass
from pydantic import BaseModel
from typing import Any, Protocol
from typing_extensions import Self
from vllm.config import VllmConfig as VllmConfig
from vllm.logger import init_logger as init_logger
from vllm.utils.torch_utils import (
    STR_DTYPE_TO_TORCH_DTYPE as STR_DTYPE_TO_TORCH_DTYPE,
    get_dtype_size as get_dtype_size,
    get_kv_cache_torch_dtype as get_kv_cache_torch_dtype,
)
from vllm.v1.core.sched.output import SchedulerOutput as SchedulerOutput

logger: Incomplete

class InvalidComponent(Exception): ...

@dataclass
class DebugPerfStats:
    calc_duration: float = ...
    num_prefill_requests: int = ...
    num_decode_requests: int = ...
    context_breakdown: dict[str, int] | None = ...
    num_flops_per_gpu_breakdown: dict[str, int] | None = ...
    num_read_bytes_per_gpu_breakdown: dict[str, int] | None = ...
    num_write_bytes_per_gpu_breakdown: dict[str, int] | None = ...

@dataclass
class PerfStats:
    num_flops_per_gpu: int = ...
    num_read_bytes_per_gpu: int = ...
    num_write_bytes_per_gpu: int = ...
    debug_stats: DebugPerfStats | None = ...

@dataclass
class ExecutionContext:
    num_prefill_requests: int = ...
    prefill_num_tokens: int = ...
    prefill_context_len: int = ...
    prefill_token_context_product: int = ...
    num_decode_requests: int = ...
    decode_num_tokens: int = ...
    decode_context_len: int = ...
    decode_token_context_product: int = ...
    def add(self, num_tokens: int, context_len: int, is_prefill: bool) -> None: ...
    def total_num_tokens(self) -> int: ...
    def total_token_context_product(self) -> int: ...
    def num_logits_tokens(self) -> int: ...
    @classmethod
    def from_single_request(
        cls, num_tokens: int, context_len: int, is_prefill: bool
    ) -> ExecutionContext: ...

class ParsedArgs:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def model_dump(self) -> dict[str, Any]: ...

class Parser(Protocol):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class ParserChain:
    parsers: Incomplete
    def __init__(self, *parsers: Parser) -> None: ...
    def add_parser(self, parser: Parser) -> None: ...
    def parse(self, vllm_config: VllmConfig) -> ParsedArgs: ...

class ComponentMetrics(BaseModel, ABC, metaclass=abc.ABCMeta):
    @classmethod
    @abstractmethod
    def component_type(cls) -> str: ...
    @classmethod
    @abstractmethod
    def get_parser(cls) -> ParserChain: ...
    def __init_subclass__(cls) -> None: ...
    @classmethod
    def from_vllm_config(cls, vllm_config: VllmConfig) -> Self: ...
    @classmethod
    def registered_metrics(cls) -> Iterable[type["ComponentMetrics"]]: ...
    @abstractmethod
    def get_num_flops_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    @abstractmethod
    def get_read_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    @abstractmethod
    def get_write_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_num_flops(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...
    def get_read_bytes(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...
    def get_write_bytes(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...

class BaseConfigParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class BaseAttentionConfigParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class AttentionQuantizationConfigParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class AttentionMetrics(ComponentMetrics):
    num_hidden_layers: int
    hidden_size: int
    num_attention_heads: int
    activation_byte_size: int
    tp_size: int
    pp_size: int
    num_key_value_heads: int
    head_dim: int
    cache_byte_size: int
    weight_byte_size: int | float
    @classmethod
    def component_type(cls) -> str: ...
    @classmethod
    def get_parser(cls) -> ParserChain: ...
    def get_num_flops_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_read_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_write_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...

class BaseFfnConfigParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class FfnParallelParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class InterleaveMoeLayerStepParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class MoeLayerFreqParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class FfnQuantizationConfigParser(Parser):
    def parse(self, args: ParsedArgs, vllm_config: VllmConfig) -> ParsedArgs: ...

class FfnMetrics(ComponentMetrics):
    num_hidden_layers: int
    hidden_size: int
    activation_byte_size: int
    pp_size: int
    ffn_tp_size: int
    ffn_ep_size: int
    intermediate_size: int
    num_experts: int
    num_experts_per_tok: int
    moe_intermediate_size: int
    num_shared_experts: int
    num_moe_layers: int
    weight_byte_size: int | float
    def validate_moe_fields(self) -> Self: ...
    @classmethod
    def component_type(cls) -> str: ...
    @classmethod
    def get_parser(cls) -> ParserChain: ...
    def get_num_flops_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_read_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_write_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...

class UnembedMetrics(ComponentMetrics):
    hidden_size: int
    vocab_size: int
    weight_byte_size: int
    activation_byte_size: int
    tp_size: int
    @classmethod
    def component_type(cls) -> str: ...
    @classmethod
    def get_parser(cls) -> ParserChain: ...
    def get_num_flops_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_read_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_write_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...

class ModelMetrics:
    vllm_config: Incomplete
    metrics: list[ComponentMetrics]
    def __init__(self, vllm_config: VllmConfig) -> None: ...
    def is_enabled(self) -> bool: ...
    def get_num_flops(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...
    def get_read_bytes(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...
    def get_write_bytes(self, ctx: ExecutionContext, per_gpu: bool = True) -> int: ...
    def get_num_flops_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_read_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_write_bytes_breakdown(
        self, ctx: ExecutionContext, per_gpu: bool = True
    ) -> dict[str, int]: ...
    def get_step_perf_stats_per_gpu(
        self, scheduler_output: SchedulerOutput
    ) -> PerfStats: ...

class PerfMetricsDebugLogging:
    def __init__(self) -> None: ...
    total_calc_duration: float
    total_num_prefill_requests: int
    total_num_decode_requests: int
    total_num_batches: int
    total_context_breakdown: dict[str, int]
    total_num_flops_per_gpu_breakdown: dict[str, int]
    total_read_bytes_per_gpu_breakdown: dict[str, int]
    total_write_bytes_per_gpu_breakdown: dict[str, int]
    def reset(self) -> None: ...
    def observe(self, debug_stats: DebugPerfStats) -> None: ...
    def log(self, log_fn, log_prefix: str, delta_time: float): ...

class PerfMetricsLogging:
    vllm_config: Incomplete
    pp_size: Incomplete
    debug_logging: PerfMetricsDebugLogging | None
    def __init__(self, vllm_config: VllmConfig) -> None: ...
    last_log_time: Incomplete
    total_num_flops_per_gpu: int
    total_read_bytes_per_gpu: int
    total_write_bytes_per_gpu: int
    def reset(self) -> None: ...
    def observe(self, perf_stats: PerfStats) -> None: ...
    def log(self, log_fn=..., log_prefix: str = "") -> None: ...

class PerfMetricsProm:
    counter_flops: Incomplete
    counter_read_bytes: Incomplete
    counter_write_bytes: Incomplete
    def __init__(
        self,
        vllm_config: VllmConfig,
        labelnames: list[str],
        per_engine_labelvalues: dict[int, list[object]],
    ) -> None: ...
    def observe(self, perf_stats: PerfStats, engine_idx: int = 0): ...

def make_per_engine(
    counter: prometheus_client.Counter, per_engine_labelvalues: dict[int, list[object]]
): ...
def get_required(obj: object, attr: str): ...
def getattr_from_list(obj: object, attrs: list[str], default: object = None): ...
