from _typeshed import Incomplete
from prometheus_client import CollectorRegistry
from vllm.logger import init_logger as init_logger

logger: Incomplete

def setup_multiprocess_prometheus() -> None: ...
def get_prometheus_registry() -> CollectorRegistry: ...
def unregister_vllm_metrics() -> None: ...
def shutdown_prometheus() -> None: ...
