from _typeshed import Incomplete
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any
from vllm.compilation.cuda_graph import CUDAGraphStat as CUDAGraphStat
from vllm.v1.engine import (
    EngineCoreEvent as EngineCoreEvent,
    EngineCoreOutput as EngineCoreOutput,
    FinishReason as FinishReason,
)
from vllm.v1.metrics.perf import PerfStats as PerfStats
from vllm.v1.spec_decode.metrics import SpecDecodingStats as SpecDecodingStats

@dataclass
class BaseCacheStats:
    reset: bool = ...
    requests: int = ...
    queries: int = ...
    hits: int = ...

class CachingMetrics:
    max_recent_requests: Incomplete
    aggregated_requests: int
    aggregated_query_total: int
    aggregated_query_hit: int
    query_queue: Incomplete
    def __init__(self, max_recent_requests: int = 1000) -> None: ...
    def observe(self, stats: BaseCacheStats): ...
    def reset(self) -> None: ...
    @property
    def empty(self) -> bool: ...
    @property
    def hit_rate(self) -> float: ...

@dataclass
class PrefixCacheStats(BaseCacheStats):
    preempted_requests: int = ...
    preempted_queries: int = ...
    preempted_hits: int = ...
    def record(self, num_tokens: int, num_hits: int, preempted: bool) -> None: ...

@dataclass
class MultiModalCacheStats(BaseCacheStats):
    def record(self, num_queries: int, num_hits: int) -> None: ...

@dataclass
class KVCacheEvictionEvent:
    lifetime_seconds: float
    idle_seconds: float
    reuse_gaps_seconds: tuple[float, ...]

@dataclass
class SchedulerStats:
    num_running_reqs: int = ...
    num_waiting_reqs: int = ...
    step_counter: int = ...
    current_wave: int = ...
    kv_cache_usage: float = ...
    encoder_cache_usage: float = ...
    prefix_cache_stats: PrefixCacheStats = field(default_factory=PrefixCacheStats)
    connector_prefix_cache_stats: PrefixCacheStats | None = ...
    kv_cache_eviction_events: list[KVCacheEvictionEvent] = field(default_factory=list)
    spec_decoding_stats: SpecDecodingStats | None = ...
    kv_connector_stats: dict[str, Any] | None = ...
    waiting_lora_adapters: dict[str, int] = field(default_factory=dict)
    running_lora_adapters: dict[str, int] = field(default_factory=dict)
    cudagraph_stats: CUDAGraphStat | None = ...
    perf_stats: PerfStats | None = ...

@dataclass
class RequestStateStats:
    num_generation_tokens: int = ...
    arrival_time: float = ...
    queued_ts: float = ...
    scheduled_ts: float = ...
    first_token_ts: float = ...
    last_token_ts: float = ...
    first_token_latency: float = ...
    is_corrupted: bool = ...

@dataclass
class FinishedRequestStats:
    finish_reason: FinishReason
    e2e_latency: float = ...
    num_prompt_tokens: int = ...
    num_generation_tokens: int = ...
    max_tokens_param: int | None = ...
    queued_time: float = ...
    prefill_time: float = ...
    inference_time: float = ...
    decode_time: float = ...
    mean_time_per_output_token: float = ...
    is_corrupted: bool = ...
    num_cached_tokens: int = ...

@dataclass
class PromptTokenStats:
    ALL_SOURCES: tuple[str, ...] = ...
    computed: int = ...
    local_cache_hit: int = ...
    external_kv_transfer: int = ...
    cached_tokens: int = ...
    recomputed_tokens: int = ...
    total: int = ...
    def update_from_output(
        self, num_cached_tokens: int, num_external_computed_tokens: int, prompt_len: int
    ) -> None: ...
    def get_by_source(self, source: str) -> int: ...

class IterationStats:
    iteration_timestamp: Incomplete
    num_generation_tokens: int
    prompt_token_stats: Incomplete
    num_preempted_reqs: int
    finished_requests: list[FinishedRequestStats]
    max_num_generation_tokens_iter: list[int]
    n_params_iter: list[int]
    time_to_first_tokens_iter: list[float]
    inter_token_latencies_iter: list[float]
    num_corrupted_reqs: int
    def __init__(self) -> None: ...
    @property
    def num_prompt_tokens(self) -> int: ...
    def update_from_output(
        self,
        output: EngineCoreOutput,
        engine_core_timestamp: float,
        is_prefilling: bool,
        prompt_len: int,
        req_stats: RequestStateStats,
        lora_states: LoRARequestStates,
        lora_name: str | None,
    ): ...
    def update_from_events(
        self,
        req_id: str,
        events: list["EngineCoreEvent"],
        is_prefilling: bool,
        req_stats: RequestStateStats,
        lora_states: LoRARequestStates,
        lora_name: str | None,
    ): ...
    def update_from_finished_request(
        self,
        finish_reason: FinishReason,
        num_prompt_tokens: int,
        max_tokens_param: int | None,
        req_stats: RequestStateStats,
        num_cached_tokens: int = 0,
    ): ...

class LoRAStats:
    waiting: set[str]
    running: set[str]
    def __init__(self) -> None: ...
    def update(self, req_id: str, waiting: bool, running: bool): ...
    @property
    def empty(self) -> bool: ...

class LoRARequestStates:
    log_stats: Incomplete
    requests: defaultdict[str, LoRAStats]
    def __init__(self, log_stats: bool = False) -> None: ...
    def request_waiting(self, req_id: str, lora_name: str | None): ...
    def request_running(self, req_id: str, lora_name: str | None): ...
    def request_finished(self, req_id: str, lora_name: str | None): ...
    def update_scheduler_stats(self, scheduler_stats: SchedulerStats | None): ...
