"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn
from functools import partial

@partial(mx.compile, shapeless=True)
def swiglu(gate, x): ...
@partial(mx.compile, shapeless=True)
def xielu(x, alpha_p, alpha_n, beta, eps):  # -> array:
    ...

class XieLU(nn.Module):
    def __init__(
        self, alpha_p_init=..., alpha_n_init=..., beta=..., eps=...
    ) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
