import abc
import enum
import torch
from abc import ABC, abstractmethod
from dataclasses import dataclass
from vllm.config import VllmConfig as VllmConfig
from vllm.tokenizers import TokenizerLike as TokenizerLike

class StructuredOutputOptions(enum.Enum):
    JSON = ...
    JSON_OBJECT = ...
    REGEX = ...
    GRAMMAR = ...
    CHOICE = ...
    STRUCTURAL_TAG = ...

StructuredOutputKey = tuple[StructuredOutputOptions, str]

class StructuredOutputGrammar(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def accept_tokens(self, request_id: str, tokens: list[int]) -> bool: ...
    @abstractmethod
    def validate_tokens(self, tokens: list[int]) -> list[int]: ...
    @abstractmethod
    def rollback(self, num_tokens: int) -> None: ...
    @abstractmethod
    def fill_bitmask(self, bitmask: torch.Tensor, batch_index: int) -> None: ...
    @abstractmethod
    def is_terminated(self) -> bool: ...
    @abstractmethod
    def reset(self): ...

@dataclass
class StructuredOutputBackend(ABC, metaclass=abc.ABCMeta):
    vllm_config: VllmConfig
    tokenizer: TokenizerLike
    vocab_size: int
    @abstractmethod
    def compile_grammar(
        self, request_type: StructuredOutputOptions, grammar_spec: str
    ) -> StructuredOutputGrammar: ...
    @abstractmethod
    def allocate_token_bitmask(self, max_num_seqs: int) -> torch.Tensor: ...
    @abstractmethod
    def destroy(self): ...
