import lmformatenforcer
import torch
from dataclasses import dataclass, field
from transformers import PreTrainedTokenizerBase as PreTrainedTokenizerBase
from vllm.sampling_params import SamplingParams as SamplingParams
from vllm.utils.import_utils import LazyLoader as LazyLoader
from vllm.v1.structured_output.backend_types import (
    StructuredOutputBackend as StructuredOutputBackend,
    StructuredOutputGrammar as StructuredOutputGrammar,
    StructuredOutputOptions as StructuredOutputOptions,
)

@dataclass
class LMFormatEnforcerGrammar(StructuredOutputGrammar):
    token_enforcer: lmformatenforcer.TokenEnforcer
    current_tokens_prefix: list[int] = field(default_factory=list)
    def accept_tokens(self, request_id: str, tokens: list[int]) -> bool: ...
    def validate_tokens(self, tokens: list[int]) -> list[int]: ...
    def rollback(self, num_tokens: int) -> None: ...
    def fill_bitmask(self, bitmask: torch.Tensor, batch_index: int) -> None: ...
    def is_terminated(self) -> bool: ...
    def reset(self) -> None: ...

@dataclass
class LMFormatEnforcerBackend(StructuredOutputBackend):
    tokenizer_data = ...
    def __post_init__(self) -> None: ...
    def compile_grammar(
        self, request_type: StructuredOutputOptions, grammar_spec: str
    ) -> StructuredOutputGrammar: ...
    def allocate_token_bitmask(self, max_num_seqs: int) -> torch.Tensor: ...
    def destroy(self) -> None: ...

def validate_structured_output_request_lm_format_enforcer(params: SamplingParams): ...
