import llguidance
import torch
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any
from vllm.logger import init_logger as init_logger
from vllm.sampling_params import SamplingParams as SamplingParams
from vllm.utils.import_utils import LazyLoader as LazyLoader
from vllm.v1.structured_output.backend_types import (
    StructuredOutputBackend as StructuredOutputBackend,
    StructuredOutputGrammar as StructuredOutputGrammar,
    StructuredOutputOptions as StructuredOutputOptions,
)
from vllm.v1.structured_output.request import (
    get_structured_output_key as get_structured_output_key,
)

logger: Incomplete

def has_guidance_unsupported_json_features(schema: dict[str, Any]) -> bool: ...
def process_for_additional_properties(
    guide_json: str | dict[str, Any],
) -> dict[str, Any]: ...
@dataclass
class GuidanceBackend(StructuredOutputBackend):
    disable_any_whitespace = ...
    disable_additional_properties = ...
    ll_tokenizer = ...
    def __post_init__(self) -> None: ...
    serialized_grammar = ...
    def compile_grammar(
        self, request_type: StructuredOutputOptions, grammar_spec: str
    ) -> StructuredOutputGrammar: ...
    def allocate_token_bitmask(self, max_num_seqs: int): ...
    def destroy(self) -> None: ...

@dataclass
class GuidanceGrammar(StructuredOutputGrammar):
    ll_matcher: llguidance.LLMatcher
    ll_tokenizer: llguidance.LLTokenizer
    vocab_size: int
    printed_error: bool = ...
    terminated: bool = ...
    rollback_lag: int = ...
    def check_error(self) -> None: ...
    def accept_tokens(self, request_id: str, tokens: list[int]) -> bool: ...
    def validate_tokens(self, tokens: list[int]) -> list[int]: ...
    def rollback(self, num_tokens: int) -> None: ...
    def fill_bitmask(self, bitmask: torch.Tensor, idx: int) -> None: ...
    def is_terminated(self) -> bool: ...
    def reset(self) -> None: ...

def serialize_guidance_grammar(
    request_type: StructuredOutputOptions,
    grammar_spec: str | dict[str, Any],
    disable_any_whitespace: bool = False,
    disable_additional_properties: bool = False,
) -> str: ...
def validate_guidance_grammar(
    sampling_params: SamplingParams, tokenizer: llguidance.LLTokenizer | None = None
) -> None: ...
