from enum import Enum

class HarmonyEncodingName(Enum):
    HARMONY_GPT_OSS = ...

class HarmonyEncoding: ...
class HarmonyError(Exception): ...

class Role(Enum):
    ASSISTANT = ...

class StreamableParser:
    last_content_delta: str
    current_channel: str | None
    current_recipient: str | None

    def __init__(self, encoding: HarmonyEncoding, role: Role = ...) -> None: ...
    def process(self, token_id: int) -> None: ...

def load_harmony_encoding(name: HarmonyEncodingName) -> HarmonyEncoding: ...
