"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from mflux.models.common.weights.loading.weight_definition import WeightDefinitionType

if TYPE_CHECKING: ...

class ModelSaver:
    @staticmethod
    def save_model(
        model: Any, bits: int, base_path: str, weight_definition: WeightDefinitionType
    ) -> None: ...
