"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.lora.mapping.lora_mapping import LoRAMapping, LoRATarget

class QwenLoRAMapping(LoRAMapping):
    @staticmethod
    def get_mapping() -> List[LoRATarget]:
        ...
    


