"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.mapping.weight_mapping import WeightMapping, WeightTarget

class QwenWeightMapping(WeightMapping):
    @staticmethod
    def get_transformer_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_vae_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_text_encoder_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_mapping() -> List[WeightTarget]:
        ...
    


