import torch.nn as nn
from _typeshed import Incomplete
from vllm.config import get_cached_compilation_config as get_cached_compilation_config
from vllm.logger import init_logger as init_logger
from vllm.model_executor.utils import (
    maybe_disable_graph_partition as maybe_disable_graph_partition,
)
from vllm.platforms import current_platform as current_platform

logger: Incomplete
op_registry: dict[str, type["CustomOp"] | type["PluggableLayer"]]
op_registry_oot: dict[str, type["CustomOp"] | type["PluggableLayer"]]

class PluggableLayer(nn.Module):
    def __new__(cls, *args, **kwargs): ...
    @classmethod
    def register(cls, name: str): ...
    @classmethod
    def register_oot(cls, _decorated_layer_cls=None, name: str | None = None): ...

class CustomOp(nn.Module):
    def __new__(cls, *args, **kwargs): ...
    def __init__(
        self, *, enforce_enable: bool = False, compile_native: bool = False
    ) -> None: ...
    def forward(self, *args, **kwargs): ...
    def forward_native(self, *args, **kwargs) -> None: ...
    def forward_cuda(self, *args, **kwargs) -> None: ...
    def forward_hip(self, *args, **kwargs): ...
    def forward_xpu(self, *args, **kwargs): ...
    def forward_cpu(self, *args, **kwargs): ...
    def forward_tpu(self, *args, **kwargs): ...
    def forward_oot(self, *args, **kwargs): ...
    def dispatch_forward(self, compile_native: bool): ...
    def maybe_compile(self, fn, *, enable: bool = True): ...
    @classmethod
    def enabled(cls) -> bool: ...
    @staticmethod
    def default_on() -> bool: ...
    @classmethod
    def register(
        cls, name: str, dynamic_arg_dims: dict[str, int | list[int]] | None = None
    ): ...
    @classmethod
    def register_oot(cls, _decorated_op_cls=None, name: str | None = None): ...
