import torch
from _typeshed import Incomplete
from collections.abc import Callable, Hashable
from fractions import Fraction
from torch.nn import Parameter
from weakref import WeakValueDictionary

__all__ = [
    "BasevLLMParameter",
    "PackedvLLMParameter",
    "PerTensorScaleParameter",
    "ModelWeightParameter",
    "ChannelQuantScaleParameter",
    "GroupQuantScaleParameter",
    "PackedColumnParameter",
    "RowvLLMParameter",
]

class BasevLLMParameter(Parameter):
    def __new__(cls, data: torch.Tensor | None, **kwargs): ...
    tp_rank: Incomplete
    tp_size: Incomplete
    def __init__(self, data: torch.Tensor, weight_loader: Callable) -> None: ...
    @property
    def weight_loader(self) -> Callable: ...
    @weight_loader.setter
    def weight_loader(self, value: Callable): ...
    @weight_loader.deleter
    def weight_loader(self) -> None: ...
    def load_column_parallel_weight(self, loaded_weight: torch.Tensor): ...
    def load_row_parallel_weight(self, loaded_weight: torch.Tensor): ...
    def load_merged_column_weight(self, loaded_weight: torch.Tensor, **kwargs): ...
    def load_qkv_weight(self, loaded_weight: torch.Tensor, **kwargs): ...
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None): ...

class _ColumnvLLMParameter(BasevLLMParameter):
    def __init__(self, output_dim: int, **kwargs) -> None: ...
    @property
    def output_dim(self): ...
    def load_column_parallel_weight(self, loaded_weight: torch.Tensor): ...
    def load_merged_column_weight(self, loaded_weight: torch.Tensor, **kwargs): ...
    def load_qkv_weight(self, loaded_weight: torch.Tensor, **kwargs): ...

class RowvLLMParameter(BasevLLMParameter):
    def __init__(self, input_dim: int, **kwargs) -> None: ...
    @property
    def input_dim(self): ...
    def load_row_parallel_weight(self, loaded_weight: torch.Tensor): ...

class ModelWeightParameter(_ColumnvLLMParameter, RowvLLMParameter): ...
class GroupQuantScaleParameter(_ColumnvLLMParameter, RowvLLMParameter): ...
class ChannelQuantScaleParameter(_ColumnvLLMParameter): ...

class PerTensorScaleParameter(BasevLLMParameter):
    def __init__(self, **kwargs) -> None: ...
    def load_row_parallel_weight(self, *args, **kwargs) -> None: ...
    def load_merged_column_weight(self, *args, **kwargs) -> None: ...
    def load_qkv_weight(self, *args, **kwargs) -> None: ...
    def load_column_parallel_weight(self, *args, **kwargs) -> None: ...

class PackedColumnParameter(_ColumnvLLMParameter):
    def __init__(
        self,
        packed_factor: int | Fraction,
        packed_dim: int,
        marlin_tile_size: int | None = None,
        **kwargs,
    ) -> None: ...
    @property
    def packed_dim(self): ...
    @property
    def packed_factor(self): ...
    @property
    def marlin_tile_size(self): ...
    def adjust_shard_indexes_for_packing(self, shard_size, shard_offset): ...

class PackedvLLMParameter(ModelWeightParameter):
    def __init__(
        self,
        packed_factor: int | Fraction,
        packed_dim: int,
        marlin_tile_size: int | None = None,
        **kwargs,
    ) -> None: ...
    @property
    def packed_dim(self): ...
    @property
    def packed_factor(self): ...
    @property
    def marlin_tile_size(self): ...
    def adjust_shard_indexes_for_packing(self, shard_size, shard_offset): ...

class BlockQuantScaleParameter(_ColumnvLLMParameter, RowvLLMParameter): ...

class SharedWeightParameter(BasevLLMParameter):
    tensors_registry: WeakValueDictionary
    local_tensors: set[torch.Tensor]
    partitions: dict[int, ModelWeightParameter | Parameter]
    def __new__(cls, **kwargs): ...
    kwargs: Incomplete
    def __init__(self, input_dim: int = 1, output_dim: int = 0, **kwargs) -> None: ...
    def add_partition(self, index: int, data_key: Hashable, *args, **kwargs): ...
    def load_column_parallel_weight(self, loaded_weight: torch.Tensor): ...
    def load_row_parallel_weight(self, loaded_weight: torch.Tensor): ...
    def load_merged_column_weight(self, loaded_weight: torch.Tensor, **kwargs): ...
    def load_qkv_weight(self, loaded_weight: torch.Tensor, **kwargs): ...
    def process_weights_after_loading(self) -> None: ...
    @property
    def data(self) -> None: ...
