import torch
from typing import Any
from vllm.utils.torch_utils import is_torch_equal_or_newer as is_torch_equal_or_newer

def set_weight_attrs(weight: torch.Tensor, weight_attrs: dict[str, Any] | None): ...
def replace_parameter(
    layer: torch.nn.Module, param_name: str, new_data: torch.Tensor | None
): ...
def get_packed_modules_mapping(model: torch.nn.Module) -> dict[str, list[str]]: ...
def get_moe_expert_mapping(
    model: torch.nn.Module,
) -> list[tuple[str, str, int, str]]: ...
def maybe_disable_graph_partition(current_backend: str) -> dict[str, bool]: ...
