import ctypes
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any
from vllm.logger import init_logger as init_logger
from vllm.platforms import current_platform as current_platform
from vllm.utils.system_utils import find_loaded_library as find_loaded_library

logger: Incomplete
cudaError_t = ctypes.c_int
cudaMemcpyKind = ctypes.c_int

class cudaIpcMemHandle_t(ctypes.Structure): ...

@dataclass
class Function:
    name: str
    restype: Any
    argtypes: list[Any]

class CudaRTLibrary:
    exported_functions: Incomplete
    cuda_to_hip_mapping: Incomplete
    path_to_library_cache: dict[str, Any]
    path_to_dict_mapping: dict[str, dict[str, Any]]
    lib: Incomplete
    funcs: Incomplete
    def __init__(self, so_file: str | None = None) -> None: ...
    def CUDART_CHECK(self, result: cudaError_t) -> None: ...
    def cudaGetErrorString(self, error: cudaError_t) -> str: ...
    def cudaSetDevice(self, device: int) -> None: ...
    def cudaDeviceSynchronize(self) -> None: ...
    def cudaDeviceReset(self) -> None: ...
    def cudaMalloc(self, size: int) -> ctypes.c_void_p: ...
    def cudaFree(self, devPtr: ctypes.c_void_p) -> None: ...
    def cudaMemset(self, devPtr: ctypes.c_void_p, value: int, count: int) -> None: ...
    def cudaMemcpy(
        self, dst: ctypes.c_void_p, src: ctypes.c_void_p, count: int
    ) -> None: ...
    def cudaIpcGetMemHandle(self, devPtr: ctypes.c_void_p) -> cudaIpcMemHandle_t: ...
    def cudaIpcOpenMemHandle(self, handle: cudaIpcMemHandle_t) -> ctypes.c_void_p: ...
