from flashinfer.comm.mnnvl import CommBackend as CommBackend
from typing import Any
from vllm.utils.flashinfer import has_flashinfer_all2all as has_flashinfer_all2all

class CustomCommunicator(CommBackend):
    def __init__(self, group) -> None: ...
    def Get_rank(self) -> int: ...
    def Get_size(self) -> int: ...
    def allgather(self, data: int): ...
    def bcast(self, data: Any, root: int) -> Any: ...
    def barrier(self) -> None: ...
    def Split(self, color: int, key: int) -> CustomCommunicator: ...
