import ray
import torch
from _typeshed import Incomplete
from ray.experimental.channel.communicator import (
    Communicator,
    TorchTensorAllocator as TorchTensorAllocator,
)
from torch.distributed import ReduceOp
from typing import Any
from vllm.distributed.device_communicators.base_device_communicator import (
    DeviceCommunicatorBase as DeviceCommunicatorBase,
)
from vllm.distributed.parallel_state import get_pp_group as get_pp_group
from vllm.logger import init_logger as init_logger
from vllm.utils.torch_utils import current_stream as current_stream

logger: Incomplete

class RayPPCommunicator(Communicator):
    def __init__(
        self,
        world_size: int,
        comm_id: Any,
        rank: int | None,
        actor_handles: list["ray.actor.ActorHandle"],
        cuda_stream: torch.cuda.Stream | None,
        use_communication_streams: bool = False,
    ) -> None: ...
    def initialize(self, rank: int) -> None: ...
    def get_actor_handles(self) -> list["ray.actor.ActorHandle"]: ...
    def get_rank(self, actor: ray.actor.ActorHandle) -> int: ...
    def get_self_rank(self) -> int | None: ...
    def get_world_size(self) -> int: ...
    def send(self, buf: torch.Tensor, peer_rank: int) -> None: ...
    def recv(
        self,
        shape: tuple[int, ...],
        dtype: torch.dtype,
        peer_rank: int,
        allocator: TorchTensorAllocator,
    ) -> torch.Tensor: ...
    def allgather(self, send_buf: torch.Tensor, recv_buf: torch.Tensor): ...
    def allreduce(
        self, send_buf: torch.Tensor, recv_buf: torch.Tensor, op: ReduceOp = ...
    ): ...
    def reducescatter(
        self, send_buf: torch.Tensor, recv_buf: torch.Tensor, op: ReduceOp = ...
    ): ...
    @property
    def recv_stream(self): ...
    @property
    def send_stream(self): ...
    def destroy(self) -> None: ...
    def get_transport_name(self) -> str: ...
    @classmethod
    def generate_communicator_id(cls) -> Any: ...
