"""
This type stub file was generated by pyright.
"""

from mflux.models.depth_pro.model.depth_pro_model import DepthProModel

class DepthProInitializer:
    @staticmethod
    def init(model: DepthProModel, quantize: int | None = ...) -> None: ...
