import torch
from _typeshed import Incomplete
from vllm.logger import init_logger as init_logger
from vllm.utils.math_utils import round_up as round_up
from vllm.v1.worker.ubatching import dbo_current_ubatch_id as dbo_current_ubatch_id

logger: Incomplete

class WorkspaceManager:
    def __init__(
        self, device: torch.device, num_ubatches: int | None = None
    ) -> None: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def is_locked(self) -> bool: ...
    def get_simultaneous(
        self, *shapes_and_dtypes: tuple[tuple[int, ...], torch.dtype]
    ) -> list[torch.Tensor]: ...

def is_workspace_manager_initialized() -> bool: ...
def current_workspace_manager() -> WorkspaceManager: ...
def init_workspace_manager(
    device: torch.device, num_ubatches: int | None = None
) -> None: ...
def lock_workspace() -> None: ...
def unlock_workspace() -> None: ...
def reset_workspace_manager() -> None: ...
