name: "🐛 Bug Report"
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels: ["Type: Bug", "Status: Triage"]
body:
    - type: textarea
      id: description
      attributes:
          label: What is the issue?
          description: What happened? What did you expect to happen?
      validations:
          required: true
    - type: dropdown
      id: os
      attributes:
          label: OS
          description: Which operating system are you using?
          multiple: true
          options:
              - Linux
              - macOS
              - Windows
              - Docker
              - WSL2
              - Other
      validations:
          required: false
    - type: dropdown
      id: gpu
      attributes:
          label: GPU
          description: Which GPU(s) are you using?
          multiple: true
          options:
              - Nvidia
              - AMD
              - Intel
              - Apple
              - Other
      validations:
          required: false
    - type: dropdown
      id: cpu
      attributes:
          label: CPU
          description: Which CPU(s) are you using?
          multiple: true
          options:
              - Intel
              - AMD
              - Apple
              - Other
      validations:
          required: false
    - type: textarea
      id: system-other
      attributes:
          label: Additional System Information
          description: Any other system information you would like to share that might be relevant to the bug.
          placeholder: e.g., software versions, configurations, GPU models, VRAM, etc.
      validations:
          required: false
    - type: textarea
      id: logs
      attributes:
        label: Logs or Console Output
        description: Paste any relevant logs or console output here (**DO NOT INCLUDE PRIVATE INFORMATION**).
        placeholder: "Error messages, warnings, etc."
      validations:
        required: false