"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class MetaData:
    quantization_level: int | None = ...
    mflux_version: str | None = ...


@dataclass
class LoadedWeights:
    components: dict[str, dict]
    meta_data: MetaData
    def __getattr__(self, name: str) -> dict | None:
        ...
    
    def num_transformer_blocks(self, component_name: str = ...) -> int:
        ...
    
    def num_single_transformer_blocks(self, component_name: str = ...) -> int:
        ...
    


