"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from mflux.models.common.weights.loading.loaded_weights import LoadedWeights
from mflux.models.common.weights.loading.weight_definition import (
    ComponentDefinition,
    WeightDefinitionType,
)

if TYPE_CHECKING: ...
logger = ...

class WeightLoader:
    @staticmethod
    def load_single(
        component: ComponentDefinition, repo_id: str, file_pattern: str = ...
    ) -> LoadedWeights: ...
    @staticmethod
    def load(
        weight_definition: WeightDefinitionType, model_path: str | None = ...
    ) -> LoadedWeights: ...
