"""
This type stub file was generated by pyright.
"""

import mlx.core as mx

class WeightTransforms:
    @staticmethod
    def reshape_gamma_to_1d(tensor: mx.array) -> mx.array: ...
    @staticmethod
    def transpose_patch_embed(tensor: mx.array) -> mx.array: ...
    @staticmethod
    def transpose_conv3d_weight(tensor: mx.array) -> mx.array: ...
    @staticmethod
    def transpose_conv2d_weight(tensor: mx.array) -> mx.array: ...
    @staticmethod
    def transpose_conv_transpose2d_weight(tensor: mx.array) -> mx.array: ...
