"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class Attention(nn.Module):
    def __init__(
        self, dim: int = ..., head_dim: int = ..., num_heads: int = ...
    ) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
