"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn

class DinoVisionTransformer(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, x: mx.array) -> tuple[mx.array, mx.array, mx.array]:
        ...
    


