import numpy.typing as npt
import torch
from .base import MediaIO as MediaIO
from _typeshed import Incomplete
from pathlib import Path
from vllm.utils.import_utils import PlaceholderModule as PlaceholderModule
from vllm.utils.serial_utils import tensor2base64 as tensor2base64

def extract_audio_from_video_bytes(data: bytes) -> tuple[npt.NDArray, float]: ...
def is_video(data: bytes) -> bool: ...

class AudioMediaIO(MediaIO[tuple[npt.NDArray, float]]):
    kwargs: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def load_bytes(self, data: bytes) -> tuple[npt.NDArray, float]: ...
    def load_base64(self, media_type: str, data: str) -> tuple[npt.NDArray, float]: ...
    def load_file(self, filepath: Path) -> tuple[npt.NDArray, float]: ...
    def encode_base64(
        self, media: tuple[npt.NDArray, int], *, audio_format: str = "WAV"
    ) -> str: ...

class AudioEmbeddingMediaIO(MediaIO[torch.Tensor]):
    def __init__(self) -> None: ...
    def load_bytes(self, data: bytes) -> torch.Tensor: ...
    def load_base64(self, media_type: str, data: str) -> torch.Tensor: ...
    def load_file(self, filepath: Path) -> torch.Tensor: ...
    def encode_base64(self, media: torch.Tensor) -> str: ...
