import torch
from ..image import convert_image_mode as convert_image_mode, rgba_to_rgb as rgba_to_rgb
from .base import MediaIO as MediaIO, MediaWithBytes as MediaWithBytes
from PIL import Image
from _typeshed import Incomplete
from pathlib import Path
from vllm.utils.serial_utils import tensor2base64 as tensor2base64

class ImageMediaIO(MediaIO[Image.Image]):
    image_mode: Incomplete
    kwargs: Incomplete
    rgba_background_color: Incomplete
    def __init__(self, image_mode: str = "RGB", **kwargs) -> None: ...
    def load_bytes(self, data: bytes) -> MediaWithBytes[Image.Image]: ...
    def load_base64(
        self, media_type: str, data: str
    ) -> MediaWithBytes[Image.Image]: ...
    def load_file(self, filepath: Path) -> MediaWithBytes[Image.Image]: ...
    def encode_base64(
        self, media: Image.Image, *, image_format: str = "PNG"
    ) -> str: ...

class ImageEmbeddingMediaIO(MediaIO[torch.Tensor]):
    def __init__(self) -> None: ...
    def load_bytes(self, data: bytes) -> torch.Tensor: ...
    def load_base64(self, media_type: str, data: str) -> torch.Tensor: ...
    def load_file(self, filepath: Path) -> torch.Tensor: ...
    def encode_base64(self, media: torch.Tensor) -> str: ...
