%llguidance {}

start: %%ENTRY_PRODUCTION%%
TEXT: /[^\[](.|\n)*/
function_call_expression: "[" function_call "]"
function_call: function_name "(" parameter_list ")"
function_name: %%FUNCTION_NAME%%
parameter_list: parameter | parameter WS "," WS parameter_list | ""
parameter: parameter_name WS "=" WS parameter_value
parameter_name: /[a-zA-Z_][a-zA-Z0-9_]*/
parameter_value: value

value: object
     | array
     | STRING
     | NUMBER
     | ("true" | "false" | "null") WS

object: "{" WS (STRING ":" WS value ("," WS STRING ":" WS value)*)? "}" WS
array: "[" WS (value ("," WS value)*)? "]" WS

// escapes
STRING: "\"" ((/[^"\\\x7F\x00-\x1F]/ | "\\" (/["\\bfnrt]/ | "u" /[0-9a-fA-F]/{4,4})))* "\"" WS

NUMBER: "-"? (/[0-9]/ | /[1-9]/ /[0-9]/{0,15}) ("." /[0-9]/+)? (/[eE]/ /[-+]/? /[0-9]/ /[1-9]/{0,15})? WS

// Optional space: by convention, applied in this grammar after literal chars when allowed
WS: ""
     | " "
     | "\n" /[ \t]/{0,20}
