import numpy as np
import torch
from _typeshed import Incomplete
from vllm.config import VllmConfig as VllmConfig
from vllm.distributed import (
    get_tensor_model_parallel_rank as get_tensor_model_parallel_rank,
)
from vllm.forward_context import get_forward_context as get_forward_context
from vllm.platforms import current_platform as current_platform

logger: Incomplete

class RoutedExpertsCapturer:
    def __init__(self) -> None: ...
    @classmethod
    def create(cls) -> RoutedExpertsCapturer: ...
    @staticmethod
    def get_instance() -> RoutedExpertsCapturer | None: ...
    dp_rank: Incomplete
    def init_buffer(
        self,
        max_num_batched_tokens: int,
        max_num_kv_tokens: int,
        vllm_config: VllmConfig,
    ) -> None: ...
    def capture(self, layer_id: int, topk_ids: torch.Tensor) -> None: ...
    def clear_buffer(self) -> None: ...
    def save_captured_experts(self, indices: np.ndarray) -> None: ...
    def cleanup(self) -> None: ...
    def __del__(self) -> None: ...

class RoutedExpertsReader:
    def __init__(self) -> None: ...
    @classmethod
    def create(cls) -> RoutedExpertsReader: ...
    @staticmethod
    def get_instance() -> RoutedExpertsReader | None: ...
    dp_rank: Incomplete
    def attach_buffer(
        self, max_num_kv_tokens: int, vllm_config: VllmConfig
    ) -> None: ...
    def get_routed_experts(self, indices: np.ndarray) -> np.ndarray: ...
    def cleanup(self) -> None: ...
    def __del__(self) -> None: ...
