"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class AdaLayerNormZeroSingle(nn.Module):
    def __init__(self) -> None:
        ...

    def __call__(self, hidden_states: mx.array, text_embeddings: mx.array) -> tuple[mx.array, mx.array]:
        ...
    


