"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class EmbedND(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, ids: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def rope(pos: mx.array, dim: int, theta: float) -> mx.array:
        ...
    


