"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class FeedForward(nn.Module):
    def __init__(self, activation_function) -> None:
        ...
    
    def __call__(self, hidden_states: mx.array) -> mx.array:
        ...
    


