"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn
from typing import Any
from mflux.models.flux.model.flux_transformer.single_block_attention import SingleBlockAttention
from mflux.models.flux.model.flux_transformer.ada_layer_norm_zero_single import AdaLayerNormZeroSingle

class SingleTransformerBlock(nn.Module):
    attn: SingleBlockAttention
    norm: AdaLayerNormZeroSingle

    def __init__(self, layer: Any) -> None:
        ...

    def __call__(self, hidden_states: mx.array, text_embeddings: mx.array, rotary_embeddings: mx.array) -> tuple[mx.array, mx.array]:
        ...

    def _apply_feed_forward_and_projection(
        self, norm_hidden_states: mx.array, attn_output: mx.array, gate: mx.array
    ) -> mx.array:
        ...
    


