"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class TextEmbedder(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, caption: mx.array) -> mx.array:
        ...
    


