"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn
from mflux.models.common.config import ModelConfig

class TimeTextEmbed(nn.Module):
    def __init__(self, model_config: ModelConfig) -> None:
        ...
    
    def __call__(self, time_step: mx.array, pooled_projection: mx.array, guidance: mx.array) -> mx.array:
        ...
    


