"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class TimestepEmbedder(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, sample: mx.array) -> mx.array:
        ...
    


