from typing import Any, Sequence

from torch import backends as backends
from torch import cuda as cuda
from torch import distributed as distributed

__version__: str

class version:
    cuda: str

class dtype: ...

bfloat16: dtype
float16: dtype
float32: dtype
int8: dtype
int32: dtype
int64: dtype
long: dtype
float8_e4m3fn: dtype

class Tensor:
    shape: Sequence[int]
    dtype: dtype
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def to(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def view(self, *shape: Any) -> Tensor: ...
    def squeeze(self, dim: int = ...) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def permute(self, *dims: int) -> Tensor: ...
    def float(self) -> Tensor: ...
    def numpy(self) -> Any: ...
    def numel(self) -> int: ...
    def nelement(self) -> int: ...
    @property
    def is_cuda(self) -> bool: ...
    @property
    def device(self) -> device: ...
    def __len__(self) -> int: ...
    def data_ptr(self) -> int: ...
    def tolist(self) -> Any: ...
    def abs(self) -> Tensor: ...
    def max(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def sum(self, dim: int = ...) -> Tensor: ...
    def item(self) -> float: ...

def tensor(data: Any, dtype: dtype | None = None, device: Any = None) -> Tensor: ...
def zeros(*size: Any, dtype: dtype | None = None, device: Any = None) -> Tensor: ...
def empty(*size: Any, dtype: dtype | None = None, device: Any = None) -> Tensor: ...
def from_numpy(ndarray: Any) -> Tensor: ...
def inference_mode() -> Any: ...

class device:
    def __init__(self, type: str, index: int = ...) -> None: ...
