"""
This type stub file was generated by pyright.
"""

import mlx.core as mx

class LoraTransforms:
    @staticmethod
    def split_q_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_k_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_v_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_q_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_k_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_v_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_q_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_k_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_v_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_mlp_up(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_q_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_k_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_v_down(tensor: mx.array) -> mx.array:
        ...
    
    @staticmethod
    def split_single_mlp_down(tensor: mx.array) -> mx.array:
        ...
    


