"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn
from collections.abc import Callable
from dataclasses import dataclass
from mflux.models.common.lora.mapping.lora_mapping import LoRATarget

@dataclass
class PatternMatch:
    source_pattern: str
    target_path: str
    matrix_name: str
    transpose: bool
    transform: Callable[[mx.array], mx.array] | None = ...

class LoRALoader:
    @staticmethod
    def load_and_apply_lora(
        lora_mapping: list[LoRATarget],
        transformer: nn.Module,
        lora_paths: list[str] | None = ...,
        lora_scales: list[float] | None = ...,
    ) -> tuple[list[str], list[float]]: ...
