"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from collections.abc import Callable
from dataclasses import dataclass
from typing import List, Protocol

@dataclass
class LoRATarget:
    model_path: str
    possible_up_patterns: List[str]
    possible_down_patterns: List[str]
    possible_alpha_patterns: List[str] = ...
    up_transform: Callable[[mx.array], mx.array] | None = ...
    down_transform: Callable[[mx.array], mx.array] | None = ...


class LoRAMapping(Protocol):
    @staticmethod
    def get_mapping() -> List[LoRATarget]:
        ...
    


