"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class Decoder(nn.Module):
    def __init__(self, enable_tiling: bool = ..., split_direction: str = ...) -> None:
        ...
    
    def __call__(self, latents: mx.array) -> mx.array:
        ...
    


