import numpy.typing as npt
from .base import get_cache_dir as get_cache_dir
from PIL import Image
from _typeshed import Incomplete
from dataclasses import dataclass
from functools import lru_cache
from typing import Any
from vllm.utils.import_utils import PlaceholderModule as PlaceholderModule

@lru_cache
def download_video_asset(filename: str) -> str: ...
def video_to_ndarrays(path: str, num_frames: int = -1) -> npt.NDArray: ...
def video_to_pil_images_list(path: str, num_frames: int = -1) -> list[Image.Image]: ...
def video_get_metadata(path: str, num_frames: int = -1) -> dict[str, Any]: ...

VideoAssetName: Incomplete

@dataclass(frozen=True)
class VideoAsset:
    name: VideoAssetName
    num_frames: int = ...
    @property
    def filename(self) -> str: ...
    @property
    def video_path(self) -> str: ...
    @property
    def pil_images(self) -> list[Image.Image]: ...
    @property
    def np_ndarrays(self) -> npt.NDArray: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def get_audio(self, sampling_rate: float | None = None) -> npt.NDArray: ...
