"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn
from mflux.models.common.vae.tiling_config import TilingConfig

class VAEUtil:
    @staticmethod
    def encode(vae: nn.Module, image: mx.array, tiling_config: TilingConfig | None = ...) -> mx.array:
        ...
    
    @staticmethod
    def decode(vae: nn.Module, latent: mx.array, tiling_config: TilingConfig | None = ...) -> mx.array:
        ...
    


