"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class CLIPEmbeddings(nn.Module):
    def __init__(self, dims: int) -> None: ...
    def __call__(self, tokens: mx.array) -> mx.array: ...
