"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class CLIPEncoderLayer(nn.Module):
    def __init__(self, layer: int) -> None: ...
    def __call__(
        self, hidden_states: mx.array, causal_attention_mask: mx.array
    ) -> mx.array: ...
