"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from pathlib import Path
from typing import Any
from tqdm import tqdm
from mflux.models.common.config.model_config import ModelConfig

logger = ...
class Config:
    def __init__(self, model_config: ModelConfig, num_inference_steps: int = ..., height: int = ..., width: int = ..., guidance: float = ..., image_path: Path | str | None = ..., image_strength: float | None = ..., depth_image_path: Path | str | None = ..., redux_image_paths: list[Path | str] | None = ..., redux_image_strengths: list[float] | None = ..., masked_image_path: Path | str | None = ..., controlnet_strength: float | None = ..., scheduler: str = ...) -> None:
        ...
    
    @property
    def height(self) -> int:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    @width.setter
    def width(self, value): # -> None:
        ...
    
    @property
    def image_seq_len(self) -> int:
        ...
    
    @property
    def guidance(self) -> float:
        ...
    
    @property
    def num_inference_steps(self) -> int:
        ...
    
    @property
    def precision(self) -> mx.Dtype:
        ...
    
    @property
    def num_train_steps(self) -> int:
        ...
    
    @property
    def image_path(self) -> Path | None:
        ...
    
    @property
    def image_strength(self) -> float | None:
        ...
    
    @property
    def depth_image_path(self) -> Path | None:
        ...
    
    @property
    def redux_image_paths(self) -> list[Path] | None:
        ...
    
    @property
    def redux_image_strengths(self) -> list[float] | None:
        ...
    
    @property
    def masked_image_path(self) -> Path | None:
        ...
    
    @property
    def init_time_step(self) -> int:
        ...
    
    @property
    def time_steps(self) -> tqdm:
        ...
    
    @property
    def controlnet_strength(self) -> float | None:
        ...
    
    @property
    def scheduler(self) -> Any:
        ...
    


