from _typeshed import Incomplete
from collections import OrderedDict
from collections.abc import Mapping
from vllm.config import SchedulerConfig as SchedulerConfig
from vllm.logger import init_logger as init_logger
from vllm.v1.request import Request as Request

logger: Incomplete

class EncoderCacheManager:
    cache_size: Incomplete
    num_free_slots: Incomplete
    num_freeable_slots: Incomplete
    cached: dict[str, set[str]]
    freeable: OrderedDict[str, int]
    freed: list[str]
    def __init__(self, cache_size: int) -> None: ...
    def reset(self) -> None: ...
    def check_and_update_cache(self, request: Request, input_id: int) -> bool: ...
    def can_allocate(
        self,
        request: Request,
        input_id: int,
        encoder_compute_budget: int,
        num_embeds_to_schedule: int,
    ) -> bool: ...
    def allocate(self, request: Request, input_id: int) -> None: ...
    def get_cached_input_ids(self, request: Request) -> set[int]: ...
    def free_encoder_input(self, request: Request, input_id: int) -> None: ...
    def free(self, request: Request) -> None: ...
    def get_freed_mm_hashes(self) -> list[str]: ...

def compute_mm_encoder_budget(
    scheduler_config: SchedulerConfig, mm_max_toks_per_item: Mapping[str, int]
) -> tuple[int, int]: ...

class EncoderDecoderCacheManager(EncoderCacheManager):
    cache_size: Incomplete
    num_free_slots: Incomplete
    allocated: list[str]
    to_free: list[str]
    def __init__(self, cache_size: int) -> None: ...
    def reset(self) -> None: ...
    def check_and_update_cache(self, request: Request, input_id: int) -> bool: ...
    def can_allocate(
        self,
        request: Request,
        input_id: int,
        encoder_compute_budget: int,
        num_embeds_to_schedule: int,
    ) -> bool: ...
    def allocate(self, request: Request, input_id: int) -> None: ...
    def free(self, request: Request) -> None: ...
    def get_cached_input_ids(self, request: Request) -> set[int]: ...
    def get_freed_mm_hashes(self) -> list[str]: ...
    def free_encoder_input(self, request: Request, input_id: int) -> None: ...
