from _typeshed import Incomplete
from collections.abc import Callable as Callable, Iterable, Iterator, Sequence
from dataclasses import dataclass
from typing import Any, TypeAlias, overload
from vllm import envs as envs
from vllm.config import VllmConfig as VllmConfig
from vllm.logger import init_logger as init_logger
from vllm.utils.hashing import sha256_cbor as sha256_cbor, xxhash_cbor as xxhash_cbor
from vllm.utils.math_utils import cdiv as cdiv
from vllm.utils.mem_utils import format_gib as format_gib
from vllm.v1.kv_cache_interface import (
    ChunkedLocalAttentionSpec as ChunkedLocalAttentionSpec,
    FullAttentionSpec as FullAttentionSpec,
    KVCacheConfig as KVCacheConfig,
    KVCacheGroupSpec as KVCacheGroupSpec,
    KVCacheSpec as KVCacheSpec,
    KVCacheTensor as KVCacheTensor,
    SlidingWindowSpec as SlidingWindowSpec,
    UniformTypeKVCacheSpecs as UniformTypeKVCacheSpecs,
)
from vllm.v1.request import Request as Request
from vllm.v1.utils import tensor_data as tensor_data

BlockHash: Incomplete
BlockHashWithGroupId: Incomplete
ExternalBlockHash: TypeAlias = bytes | int

def make_block_hash_with_group_id(
    block_hash: BlockHash, group_id: int
) -> BlockHashWithGroupId: ...
def get_block_hash(key: BlockHashWithGroupId) -> BlockHash: ...
def get_group_id(key: BlockHashWithGroupId) -> int: ...
def maybe_convert_block_hash(hash_bytes: BlockHash) -> ExternalBlockHash: ...

logger: Incomplete
NONE_HASH: BlockHash

def init_none_hash(hash_fn: Callable[[Any], bytes]): ...
@dataclass(slots=True)
class KVCacheBlock:
    block_id: int
    ref_cnt: int = ...
    prev_free_block: KVCacheBlock | None = ...
    next_free_block: KVCacheBlock | None = ...
    is_null: bool = ...
    @property
    def block_hash(self) -> BlockHashWithGroupId | None: ...
    @block_hash.setter
    def block_hash(self, block_hash: BlockHashWithGroupId): ...
    def reset_hash(self) -> None: ...

class FreeKVCacheBlockQueue:
    num_free_blocks: Incomplete
    fake_free_list_head: Incomplete
    fake_free_list_tail: Incomplete
    def __init__(self, blocks: list[KVCacheBlock]) -> None: ...
    def popleft(self) -> KVCacheBlock: ...
    def popleft_n(self, n: int) -> list[KVCacheBlock]: ...
    def remove(self, block: KVCacheBlock) -> None: ...
    def append(self, block: KVCacheBlock) -> None: ...
    def append_n(self, blocks: list[KVCacheBlock]) -> None: ...
    def get_all_free_blocks(self) -> list[KVCacheBlock]: ...

def need_extra_keys(request: Request) -> bool: ...
def generate_block_hash_extra_keys(
    request: Request, start_token_idx: int, end_token_idx: int, start_mm_idx: int
) -> tuple[tuple[Any, ...] | None, int]: ...
def hash_block_tokens(
    hash_function: Callable[[Any], bytes],
    parent_block_hash: BlockHash | None,
    curr_block_token_ids: Sequence[int],
    extra_keys: tuple[Any, ...] | None = None,
) -> BlockHash: ...
def get_request_block_hasher(
    block_size: int, caching_hash_fn: Callable[[Any], bytes]
) -> Callable[[Request], list[BlockHash]]: ...
def max_memory_usage_bytes(
    vllm_config: VllmConfig, kv_cache_specs: Iterable[KVCacheSpec]
) -> int: ...
def estimate_max_model_len(
    vllm_config: VllmConfig,
    kv_cache_spec: dict[str, KVCacheSpec],
    available_memory: int,
) -> int: ...
def check_enough_kv_cache_memory(
    vllm_config: VllmConfig,
    kv_cache_spec: dict[str, KVCacheSpec],
    available_memory: int,
): ...
def create_kv_cache_group_specs(
    kv_cache_spec: dict[str, KVCacheSpec], grouped_layer_names: list[list[str]]
) -> list[KVCacheGroupSpec]: ...
def is_kv_cache_spec_uniform(kv_cache_spec: dict[str, KVCacheSpec]) -> bool: ...
def get_max_concurrency_for_kv_cache_config(
    vllm_config: VllmConfig, kv_cache_config: KVCacheConfig
) -> float: ...
def may_override_num_blocks(vllm_config: VllmConfig, num_blocks: int) -> int: ...
def get_num_blocks(
    vllm_config: VllmConfig, num_layers: int, available_memory: int, page_size: int
) -> int: ...
def get_uniform_page_size(kv_cache_specs: Iterable[KVCacheSpec]) -> int: ...
def is_kv_cache_page_size_uniform(kv_cache_spec: dict[str, KVCacheSpec]) -> bool: ...
def unify_kv_cache_spec_page_size(
    kv_cache_spec: dict[str, KVCacheSpec],
) -> dict[str, KVCacheSpec]: ...
def is_kv_cache_type_attention_free(kv_cache_spec: dict[str, KVCacheSpec]) -> bool: ...
def get_kv_cache_config_from_groups(
    vllm_config: VllmConfig,
    kv_cache_groups: list[KVCacheGroupSpec],
    available_memory: int,
) -> KVCacheConfig: ...
def unify_hybrid_kv_cache_specs(kv_cache_spec: dict[str, KVCacheSpec]): ...
def get_kv_cache_groups(
    vllm_config: VllmConfig, kv_cache_spec: dict[str, KVCacheSpec]
) -> list[KVCacheGroupSpec]: ...
def generate_scheduler_kv_cache_config(
    kv_cache_configs: list[KVCacheConfig],
) -> KVCacheConfig: ...
def get_kv_cache_configs(
    vllm_config: VllmConfig,
    kv_cache_specs: list[dict[str, KVCacheSpec]],
    available_memory: list[int],
) -> list[KVCacheConfig]: ...

class BlockHashListWithBlockSize:
    block_hashes: Incomplete
    scale_factor: Incomplete
    def __init__(
        self,
        block_hashes: list[BlockHash],
        hash_block_size: int,
        target_block_size: int,
    ) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, idx: int) -> BlockHash: ...
    @overload
    def __getitem__(self, idx: slice) -> list[BlockHash]: ...
    def __iter__(self) -> Iterator[BlockHash]: ...

BlockHashList = list[BlockHash] | BlockHashListWithBlockSize
