from _typeshed import Incomplete
from collections import deque
from vllm.v1.core.kv_cache_utils import KVCacheBlock as KVCacheBlock
from vllm.v1.metrics.stats import KVCacheEvictionEvent as KVCacheEvictionEvent

class BlockMetricsState:
    birth_time_ns: Incomplete
    last_access_ns: Incomplete
    access_history: deque[int]
    def __init__(self) -> None: ...
    def record_access(self) -> None: ...
    def get_lifetime_seconds(self) -> float: ...
    def get_idle_time_seconds(self) -> float: ...
    def get_reuse_gaps_seconds(self) -> list[float]: ...

class KVCacheMetricsCollector:
    sample_rate: Incomplete
    block_metrics: dict[int, BlockMetricsState]
    def __init__(self, sample_rate: float = 0.01) -> None: ...
    def should_sample_block(self) -> bool: ...
    def on_block_allocated(self, block: KVCacheBlock) -> None: ...
    def on_block_accessed(self, block: KVCacheBlock) -> None: ...
    def on_block_evicted(self, block: KVCacheBlock) -> None: ...
    def reset(self) -> None: ...
    def drain_events(self) -> list[KVCacheEvictionEvent]: ...
