from _typeshed import Incomplete
from collections.abc import Iterable, Sequence
from openai.types.responses.tool import Tool as Tool
from openai_harmony import Message, StreamableParser
from typing import Literal
from vllm import envs as envs
from vllm.entrypoints.openai.chat_completion.protocol import (
    ChatCompletionToolsParam as ChatCompletionToolsParam,
)
from vllm.logger import init_logger as init_logger

logger: Incomplete
REASONING_EFFORT: Incomplete
BUILTIN_TOOL_TO_MCP_SERVER_LABEL: dict[str, str]
MCP_BUILTIN_TOOLS: set[str]

def has_custom_tools(tool_types: set[str]) -> bool: ...
def get_encoding(): ...
def get_system_message(
    model_identity: str | None = None,
    reasoning_effort: Literal["high", "medium", "low"] | None = None,
    start_date: str | None = None,
    browser_description: str | None = None,
    python_description: str | None = None,
    container_description: str | None = None,
    instructions: str | None = None,
    with_custom_tools: bool = False,
) -> Message: ...
def create_tool_definition(tool: ChatCompletionToolsParam | Tool): ...
def get_developer_message(
    instructions: str | None = None,
    tools: list[Tool | ChatCompletionToolsParam] | None = None,
) -> Message: ...
def get_user_message(content: str) -> Message: ...
def parse_chat_inputs_to_harmony_messages(chat_msgs: list) -> list[Message]: ...
def auto_drop_analysis_messages(msgs: list[Message]) -> list[Message]: ...
def flatten_chat_text_content(content: str | list | None) -> str | None: ...
def parse_chat_input_to_harmony_message(
    chat_msg, tool_id_names: dict[str, str] | None = None
) -> list[Message]: ...
def render_for_completion(messages: list[Message]) -> list[int]: ...
def get_stop_tokens_for_assistant_actions() -> list[int]: ...
def get_streamable_parser_for_assistant() -> StreamableParser: ...
def parse_output_into_messages(token_ids: Iterable[int]) -> StreamableParser: ...
def parse_chat_output(
    token_ids: Sequence[int],
) -> tuple[str | None, str | None, bool]: ...
