"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from mflux.models.common.config.model_config import ModelConfig

if TYPE_CHECKING:
    ...
logger = ...
class ConfigResolution:
    RULES = ...
    @staticmethod
    def resolve(model_name: str, base_model: str | None = ...) -> ModelConfig:
        ...
    


