"""
This type stub file was generated by pyright.
"""

from pathlib import Path

logger = ...
class LoraResolution:
    RULES = ...
    _registry: dict[str, Path] = ...
    @staticmethod
    def resolve(path: str) -> str:
        ...
    
    @staticmethod
    def resolve_paths(paths: list[str] | None) -> list[str]:
        ...
    
    @staticmethod
    def resolve_scales(scales: list[float] | None, num_paths: int) -> list[float]:
        ...
    
    @staticmethod
    def get_registry() -> dict[str, Path]:
        ...
    
    @staticmethod
    def discover_files(library_paths: list[Path]) -> dict[str, Path]:
        ...
    


