"""
This type stub file was generated by pyright.
"""

from pathlib import Path

logger = ...
class PathResolution:
    RULES = ...
    @staticmethod
    def resolve(path: str | None, patterns: list[str] | None = ...) -> Path | None:
        ...
    


