"""
This type stub file was generated by pyright.
"""

logger = ...

class QuantizationResolution:
    RULES = ...
    @staticmethod
    def resolve(
        stored: int | None, requested: int | None
    ) -> tuple[int | None, str | None]: ...
