import torch
from _typeshed import Incomplete
from collections.abc import Iterable
from typing import Any
from vllm.config import VllmConfig as VllmConfig
from vllm.distributed.kv_events import (
    BlockStored as BlockStored,
    KVCacheEvent as KVCacheEvent,
    KVConnectorKVEvents as KVConnectorKVEvents,
    KVEventAggregator as KVEventAggregator,
)
from vllm.distributed.kv_transfer.kv_connector.v1.base import (
    KVConnectorBase_V1 as KVConnectorBase_V1,
    KVConnectorMetadata as KVConnectorMetadata,
    KVConnectorRole as KVConnectorRole,
)
from vllm.forward_context import ForwardContext as ForwardContext
from vllm.logger import init_logger as init_logger
from vllm.v1.attention.backend import AttentionMetadata as AttentionMetadata
from vllm.v1.core.kv_cache_manager import KVCacheBlocks as KVCacheBlocks
from vllm.v1.core.sched.output import SchedulerOutput as SchedulerOutput
from vllm.v1.kv_cache_interface import KVCacheConfig as KVCacheConfig
from vllm.v1.outputs import KVConnectorOutput as KVConnectorOutput
from vllm.v1.request import Request as Request

logger: Incomplete

class LMCacheKVEvents(KVConnectorKVEvents):
    def __init__(self, num_workers: int) -> None: ...
    def add_events(self, events: list[KVCacheEvent]) -> None: ...
    def aggregate(self) -> LMCacheKVEvents: ...
    def increment_workers(self, count: int = 1) -> None: ...
    def get_all_events(self) -> list[KVCacheEvent]: ...
    def get_number_of_workers(self) -> int: ...
    def clear_events(self) -> None: ...

class LMCacheConnectorV1(KVConnectorBase_V1):
    @classmethod
    def requires_piecewise_for_cudagraph(cls, extra_config: dict[str, Any]) -> bool: ...
    def __init__(
        self,
        vllm_config: VllmConfig,
        role: KVConnectorRole,
        kv_cache_config: KVCacheConfig,
    ) -> None: ...
    def register_kv_caches(self, kv_caches: dict[str, torch.Tensor]): ...
    def start_load_kv(self, forward_context: ForwardContext, **kwargs: Any) -> None: ...
    def wait_for_layer_load(self, layer_name: str) -> None: ...
    def save_kv_layer(
        self,
        layer_name: str,
        kv_layer: torch.Tensor,
        attn_metadata: AttentionMetadata,
        **kwargs: Any,
    ) -> None: ...
    def wait_for_save(self) -> None: ...
    def get_finished(
        self, finished_req_ids: set[str]
    ) -> tuple[set[str] | None, set[str] | None]: ...
    def get_block_ids_with_load_errors(self) -> set[int]: ...
    def get_kv_connector_kv_cache_events(self) -> LMCacheKVEvents | None: ...
    def get_num_new_matched_tokens(
        self, request: Request, num_computed_tokens: int
    ) -> tuple[int | None, bool]: ...
    def update_state_after_alloc(
        self, request: Request, blocks: KVCacheBlocks, num_external_tokens: int
    ): ...
    def build_connector_meta(
        self, scheduler_output: SchedulerOutput
    ) -> KVConnectorMetadata: ...
    def update_connector_output(self, connector_output: KVConnectorOutput): ...
    def request_finished(
        self, request: Request, block_ids: list[int]
    ) -> tuple[bool, dict[str, Any] | None]: ...
    def take_events(self) -> Iterable["KVCacheEvent"]: ...
