"""
This type stub file was generated by pyright.
"""

import mlx.core as mx

"""
This type stub file was generated by pyright.
"""
class FluxLatentCreator:
    @staticmethod
    def create_noise(seed: int, height: int, width: int) -> mx.array:
        ...
    
    @staticmethod
    def pack_latents(latents: mx.array, height: int, width: int, num_channels_latents: int = ...) -> mx.array:
        ...
    
    @staticmethod
    def unpack_latents(latents: mx.array, height: int, width: int) -> mx.array:
        ...
    


