from _typeshed import DataclassInstance, Incomplete
from collections.abc import Callable as Callable
from torch._C._profiler import _ProfilerEvent

def trim_string_front(string: str, width: int) -> str: ...
def trim_string_back(string: str, width: int) -> str: ...

class TablePrinter:
    row_cls: Incomplete
    fieldnames: Incomplete
    column_widths: Incomplete
    def __init__(
        self, row_cls: type[DataclassInstance], column_widths: dict[str, int]
    ) -> None: ...
    def print_table(self, rows: list[DataclassInstance]): ...

def indent_string(
    string: str, indent: int, indent_style: Callable[[int], str] | str = " "
) -> str: ...
def event_has_module(event: _ProfilerEvent) -> bool: ...
def event_is_torch_op(event: _ProfilerEvent) -> bool: ...
def event_arg_repr(arg) -> str: ...
def event_torch_op_repr(event: _ProfilerEvent) -> str: ...
def event_module_repr(event: _ProfilerEvent) -> str: ...
def event_torch_op_stack_trace(
    curr_event: _ProfilerEvent, until: Callable[[_ProfilerEvent], bool]
) -> str: ...
