"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class Attention(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, input_array: mx.array) -> mx.array:
        ...
    


