"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

"""
This type stub file was generated by pyright.
"""
class T5Encoder(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, tokens: mx.array):
        ...
    


