import msgspec

class LoRARequest(msgspec.Struct, omit_defaults=True, array_like=True):
    lora_name: str
    lora_int_id: int
    lora_path: str = ...
    base_model_name: str | None = msgspec.field(default=None)
    tensorizer_config_dict: dict | None = ...
    load_inplace: bool = ...
    def __post_init__(self) -> None: ...
    @property
    def adapter_id(self): ...
    @property
    def name(self): ...
    @property
    def path(self): ...
    def __eq__(self, value: object) -> bool: ...
    def __hash__(self) -> int: ...
