from typing import Protocol

from shared.types.graphs.topology import Topology
from shared.types.models import ModelId, ModelMetadata
from shared.types.worker.common import InstanceId
from shared.types.worker.downloads import DownloadProgress
from shared.types.worker.instances import Instance


class ClusterAPI(Protocol):
    def get_topology(self) -> Topology: ...

    def list_instances(self) -> list[Instance]: ...

    def get_instance(self, instance_id: InstanceId) -> Instance: ...

    def create_instance(self, model_id: ModelId) -> InstanceId: ...

    def remove_instance(self, instance_id: InstanceId) -> None: ...

    def get_model_metadata(self, model_id: ModelId) -> ModelMetadata: ...

    def download_model(self, model_id: ModelId) -> None: ...

    def get_download_progress(self, model_id: ModelId) -> DownloadProgress: ...
