"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.mapping.weight_mapping import WeightMapping, WeightTarget

class FIBOVLMWeightMapping(WeightMapping):
    @staticmethod
    def get_vlm_decoder_mapping(num_layers: int = ...) -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_vlm_visual_mapping(depth: int = ...) -> List[WeightTarget]:
        ...
    


