# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "Keypair",
]

@typing.final
class Keypair:
    r"""
    Identity keypair of a node.
    """
    @staticmethod
    def generate() -> Keypair:
        r"""
        Generate a new Ed25519 keypair.
        """
    @staticmethod
    def from_bytes(bytes: bytes) -> Keypair:
        r"""
        Construct an Ed25519 keypair from secret key bytes
        """
    def to_bytes(self) -> bytes:
        r"""
        Get the secret key bytes underlying the keypair
        """
    def to_node_id(self) -> builtins.str:
        r"""
        Convert the `Keypair` into the corresponding `PeerId` string, which we use as our `NodeId`.
        """
