"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class T5DenseReluDense(nn.Module):
    def __init__(self) -> None: ...
    def __call__(self, hidden_states: mx.array) -> mx.array: ...
    @staticmethod
    def new_gelu(input_array: mx.array) -> mx.array: ...
