"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from dataclasses import dataclass

"""
This type stub file was generated by pyright.
"""

@dataclass
class TokenizerOutput:
    input_ids: mx.array
    attention_mask: mx.array
    pixel_values: mx.array | None = ...
    image_grid_thw: mx.array | None = ...
