"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from mflux.models.common.tokenizer.tokenizer import BaseTokenizer
from mflux.models.common.weights.loading.weight_definition import TokenizerDefinition

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING: ...

class TokenizerLoader:
    @staticmethod
    def load(definition: TokenizerDefinition, model_path: str) -> BaseTokenizer: ...
    @staticmethod
    def load_all(
        definitions: list[TokenizerDefinition],
        model_path: str,
        max_length_overrides: dict[str, int] | None = ...,
    ) -> dict[str, BaseTokenizer]: ...
