import argparse
from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Literal
from vllm.config import config as config
from vllm.engine.arg_utils import (
    AsyncEngineArgs as AsyncEngineArgs,
    optional_type as optional_type,
)
from vllm.entrypoints.chat_utils import (
    ChatTemplateContentFormatOption as ChatTemplateContentFormatOption,
    validate_chat_template as validate_chat_template,
)
from vllm.entrypoints.constants import (
    H11_MAX_HEADER_COUNT_DEFAULT as H11_MAX_HEADER_COUNT_DEFAULT,
    H11_MAX_INCOMPLETE_EVENT_SIZE_DEFAULT as H11_MAX_INCOMPLETE_EVENT_SIZE_DEFAULT,
)
from vllm.entrypoints.openai.models.protocol import LoRAModulePath as LoRAModulePath
from vllm.logger import init_logger as init_logger
from vllm.tool_parsers import ToolParserManager as ToolParserManager
from vllm.utils.argparse_utils import FlexibleArgumentParser as FlexibleArgumentParser

logger: Incomplete

class LoRAParserAction(argparse.Action):
    def __call__(
        self,
        parser: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: str | Sequence[str] | None,
        option_string: str | None = None,
    ): ...

@config
class BaseFrontendArgs:
    lora_modules: list[LoRAModulePath] | None = ...
    chat_template: str | None = ...
    chat_template_content_format: ChatTemplateContentFormatOption = ...
    trust_request_chat_template: bool = ...
    default_chat_template_kwargs: dict[str, Any] | None = ...
    response_role: str = ...
    return_tokens_as_token_ids: bool = ...
    disable_frontend_multiprocessing: bool = ...
    enable_auto_tool_choice: bool = ...
    exclude_tools_when_tool_choice_none: bool = ...
    tool_call_parser: str | None = ...
    tool_parser_plugin: str = ...
    tool_server: str | None = ...
    log_config_file: str | None = ...
    max_log_len: int | None = ...
    enable_prompt_tokens_details: bool = ...
    enable_server_load_tracking: bool = ...
    enable_force_include_usage: bool = ...
    enable_tokenizer_info_endpoint: bool = ...
    enable_log_outputs: bool = ...
    enable_log_deltas: bool = ...
    log_error_stack: bool = ...
    tokens_only: bool = ...
    @classmethod
    def add_cli_args(cls, parser: FlexibleArgumentParser) -> FlexibleArgumentParser: ...

@config
class FrontendArgs(BaseFrontendArgs):
    host: str | None = ...
    port: int = ...
    uds: str | None = ...
    uvicorn_log_level: Literal[
        "critical", "error", "warning", "info", "debug", "trace"
    ] = ...
    disable_uvicorn_access_log: bool = ...
    disable_access_log_for_endpoints: str | None = ...
    allow_credentials: bool = ...
    allowed_origins: list[str] = ...
    allowed_methods: list[str] = ...
    allowed_headers: list[str] = ...
    api_key: list[str] | None = ...
    ssl_keyfile: str | None = ...
    ssl_certfile: str | None = ...
    ssl_ca_certs: str | None = ...
    enable_ssl_refresh: bool = ...
    ssl_cert_reqs: int = ...
    ssl_ciphers: str | None = ...
    root_path: str | None = ...
    middleware: list[str] = ...
    enable_request_id_headers: bool = ...
    disable_fastapi_docs: bool = ...
    h11_max_incomplete_event_size: int = ...
    h11_max_header_count: int = ...
    enable_offline_docs: bool = ...

def make_arg_parser(parser: FlexibleArgumentParser) -> FlexibleArgumentParser: ...
def validate_parsed_serve_args(args: argparse.Namespace): ...
def create_parser_for_docs() -> FlexibleArgumentParser: ...
