"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.mapping.weight_mapping import (
    WeightMapping,
    WeightTarget,
)

class DepthProWeightMapping(WeightMapping):
    @staticmethod
    def get_mapping() -> List[WeightTarget]: ...
