"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.loading.weight_definition import (
    ComponentDefinition,
    TokenizerDefinition,
)

"""
This type stub file was generated by pyright.
"""

class DepthProWeightDefinition:
    @staticmethod
    def get_components() -> List[ComponentDefinition]: ...
    @staticmethod
    def get_tokenizers() -> List[TokenizerDefinition]: ...
    @staticmethod
    def get_download_patterns() -> List[str]: ...
    @staticmethod
    def quantization_predicate(path: str, module) -> bool: ...
