"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenTimesteps(nn.Module):
    def __init__(self, proj_dim: int = ..., scale: float = ...) -> None: ...
    def __call__(self, timesteps: mx.array) -> mx.array: ...
