"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.mapping.weight_mapping import WeightMapping, WeightTarget

class FluxWeightMapping(WeightMapping):
    @staticmethod
    def get_transformer_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_controlnet_transformer_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_vae_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_t5_encoder_mapping() -> List[WeightTarget]:
        ...
    
    @staticmethod
    def get_clip_encoder_mapping() -> List[WeightTarget]:
        ...
    


