"""
This type stub file was generated by pyright.
"""

from mflux.models.common.lora.mapping.lora_mapping import LoRAMapping, LoRATarget

class FluxLoRAMapping(LoRAMapping):
    @staticmethod
    def get_mapping() -> list[LoRATarget]: ...
