"""
This type stub file was generated by pyright.
"""

from typing import List
from mflux.models.common.weights.loading.weight_definition import ComponentDefinition, TokenizerDefinition

"""
This type stub file was generated by pyright.
"""
class FluxWeightDefinition:
    @staticmethod
    def get_components() -> List[ComponentDefinition]:
        ...
    
    @staticmethod
    def get_tokenizers() -> List[TokenizerDefinition]:
        ...
    
    @staticmethod
    def get_download_patterns() -> List[str]:
        ...
    
    @staticmethod
    def quantization_predicate(path: str, module) -> bool:
        ...
    


class FluxControlnetWeightDefinition:
    @staticmethod
    def get_controlnet_component() -> ComponentDefinition:
        ...
    
    @staticmethod
    def get_components() -> List[ComponentDefinition]:
        ...
    
    @staticmethod
    def get_tokenizers() -> List[TokenizerDefinition]:
        ...
    
    @staticmethod
    def get_download_patterns() -> List[str]:
        ...
    
    @staticmethod
    def quantization_predicate(path: str, module) -> bool:
        ...
    


class FluxReduxWeightDefinition:
    @staticmethod
    def get_components() -> List[ComponentDefinition]:
        ...
    
    @staticmethod
    def get_tokenizers() -> List[TokenizerDefinition]:
        ...
    
    @staticmethod
    def get_download_patterns() -> List[str]:
        ...
    
    @staticmethod
    def quantization_predicate(path: str, module) -> bool:
        ...
    


