"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class AbsoluteBoxValues:
    top: int
    right: int
    bottom: int
    left: int
    ...

class BoxValueError(ValueError): ...

@dataclass
class BoxValues:
    top: int | str
    right: int | str
    bottom: int | str
    left: int | str
    def normalize_to_dimensions(self, width, height) -> AbsoluteBoxValues: ...
    @staticmethod
    def parse(value, delimiter=...) -> BoxValues: ...
