"""
This type stub file was generated by pyright.
"""

from pathlib import Path

log = ...
class MetadataBuilder:
    _IPTC_PROMPT_MAX_BYTES = ...
    @staticmethod
    def embed_metadata(metadata: dict, path: str | Path) -> None:
        ...
    
    @staticmethod
    def build_xmp_packet(metadata: dict) -> str:
        ...
    
    @staticmethod
    def build_iptc_binary(metadata: dict) -> bytes:
        ...
    


