"""
This type stub file was generated by pyright.
"""

import mlx.core as mx

class FiboLatentCreator:
    @staticmethod
    def create_noise(seed: int, height: int, width: int) -> mx.array:
        ...
    
    @staticmethod
    def pack_latents(latents: mx.array, height: int, width: int) -> mx.array:
        ...
    
    @staticmethod
    def unpack_latents(latents: mx.array, height: int, width: int) -> mx.array:
        ...
    


