import enum
import torch
from _typeshed import Incomplete
from datetime import timedelta
from torch.distributed import PrefixStore as PrefixStore, ProcessGroup as ProcessGroup
from typing import Any, NamedTuple
from vllm.config import VllmConfig as VllmConfig
from vllm.inputs import ProcessorInputs as ProcessorInputs
from vllm.logger import init_logger as init_logger
from vllm.pooling_params import PoolingParams as PoolingParams
from vllm.sampling_params import SamplingParams as SamplingParams
from vllm.utils.argparse_utils import FlexibleArgumentParser as FlexibleArgumentParser
from vllm.v1.attention.backends.registry import (
    AttentionBackendEnum as AttentionBackendEnum,
)
from vllm.v1.attention.selector import (
    AttentionSelectorConfig as AttentionSelectorConfig,
)

logger: Incomplete

def in_wsl() -> bool: ...

class PlatformEnum(enum.Enum):
    CUDA = ...
    ROCM = ...
    TPU = ...
    XPU = ...
    CPU = ...
    OOT = ...
    UNSPECIFIED = ...

class CpuArchEnum(enum.Enum):
    X86 = ...
    ARM = ...
    POWERPC = ...
    S390X = ...
    RISCV = ...
    OTHER = ...
    UNKNOWN = ...

class DeviceCapability(NamedTuple):
    major: int
    minor: int
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def as_version_str(self) -> str: ...
    def to_int(self) -> int: ...

class Platform:
    device_name: str
    device_type: str
    dispatch_key: str
    ray_device_key: str
    device_control_env_var: str
    ray_noset_device_env_vars: list[str]
    simple_compile_backend: str
    dist_backend: str
    supported_quantization: list[str]
    additional_env_vars: list[str]
    @property
    def pass_key(self) -> str: ...
    @property
    def supported_dtypes(self) -> list[torch.dtype]: ...
    def is_cuda(self) -> bool: ...
    def is_rocm(self) -> bool: ...
    def is_tpu(self) -> bool: ...
    def is_xpu(self) -> bool: ...
    def is_cpu(self) -> bool: ...
    def is_out_of_tree(self) -> bool: ...
    def is_unspecified(self) -> bool: ...
    def get_max_output_tokens(self, prompt_len: int) -> int: ...
    def is_cuda_alike(self) -> bool: ...
    def is_sleep_mode_available(self) -> bool: ...
    @classmethod
    def get_pass_manager_cls(cls) -> str: ...
    @classmethod
    def get_compile_backend(cls) -> str: ...
    @classmethod
    def device_id_to_physical_device_id(cls, device_id: int): ...
    @classmethod
    def import_kernels(cls) -> None: ...
    @classmethod
    def get_attn_backend_cls(
        cls,
        selected_backend: AttentionBackendEnum,
        attn_selector_config: AttentionSelectorConfig,
        num_heads: int | None = None,
    ) -> str: ...
    @classmethod
    def get_supported_vit_attn_backends(cls) -> list["AttentionBackendEnum"]: ...
    @classmethod
    def get_vit_attn_backend(
        cls,
        head_size: int,
        dtype: torch.dtype,
        backend: AttentionBackendEnum | None = None,
    ) -> AttentionBackendEnum: ...
    @classmethod
    def get_device_capability(cls, device_id: int = 0) -> DeviceCapability | None: ...
    @classmethod
    def has_device_capability(
        cls, capability: tuple[int, int] | int, device_id: int = 0
    ) -> bool: ...
    @classmethod
    def is_device_capability(
        cls, capability: tuple[int, int] | int, device_id: int = 0
    ) -> bool: ...
    @classmethod
    def is_device_capability_family(
        cls, capability: int, device_id: int = 0
    ) -> bool: ...
    @classmethod
    def get_device_name(cls, device_id: int = 0) -> str: ...
    @classmethod
    def get_device_uuid(cls, device_id: int = 0) -> str: ...
    @classmethod
    def get_device_total_memory(cls, device_id: int = 0) -> int: ...
    @classmethod
    def inference_mode(cls): ...
    @classmethod
    def set_device(cls, device: torch.device) -> None: ...
    @classmethod
    def pre_register_and_update(
        cls, parser: FlexibleArgumentParser | None = None
    ) -> None: ...
    @classmethod
    def apply_config_platform_defaults(cls, vllm_config: VllmConfig) -> None: ...
    @classmethod
    def check_and_update_config(cls, vllm_config: VllmConfig) -> None: ...
    @classmethod
    def update_block_size_for_backend(cls, vllm_config: VllmConfig) -> None: ...
    @classmethod
    def verify_model_arch(cls, model_arch: str) -> None: ...
    @classmethod
    def verify_quantization(cls, quant: str) -> None: ...
    @classmethod
    def get_cpu_architecture(cls) -> CpuArchEnum: ...
    @classmethod
    def is_pin_memory_available(cls) -> bool: ...
    @classmethod
    def get_current_memory_usage(
        cls, device: torch.types.Device | None = None
    ) -> float: ...
    @classmethod
    def get_punica_wrapper(cls) -> str: ...
    @classmethod
    def get_infinity_values(cls, dtype: torch.dtype) -> tuple[float, float]: ...
    @classmethod
    def can_update_inplace(cls) -> bool: ...
    @classmethod
    def get_lora_vocab_padding_size(cls) -> int: ...
    @classmethod
    def get_device_communicator_cls(cls) -> str: ...
    @classmethod
    def supports_mx(cls) -> bool: ...
    @classmethod
    def supports_fp8(cls) -> bool: ...
    @classmethod
    def is_fp8_fnuz(cls) -> bool: ...
    @classmethod
    def fp8_dtype(cls) -> torch.dtype: ...
    @classmethod
    def use_all_gather(cls) -> bool: ...
    @classmethod
    def use_custom_allreduce(cls) -> bool: ...
    @classmethod
    def opaque_attention_op(cls) -> bool: ...
    @classmethod
    def validate_request(
        cls, processed_inputs: ProcessorInputs, params: SamplingParams | PoolingParams
    ) -> None: ...
    def __getattr__(self, key: str): ...
    def get_global_graph_pool(self) -> Any: ...
    @classmethod
    def get_static_graph_wrapper_cls(cls) -> str: ...
    @classmethod
    def stateless_init_device_torch_dist_pg(
        cls,
        backend: str,
        prefix_store: PrefixStore,
        group_rank: int,
        group_size: int,
        timeout: timedelta,
    ) -> ProcessGroup: ...
    @classmethod
    def check_if_supports_dtype(cls, dtype: torch.dtype): ...
    @classmethod
    def support_hybrid_kv_cache(cls) -> bool: ...
    @classmethod
    def support_static_graph_mode(cls) -> bool: ...
    @classmethod
    def use_custom_op_collectives(cls) -> bool: ...
    @classmethod
    def use_sync_weight_loader(cls) -> bool: ...
    @classmethod
    def make_synced_weight_loader(cls, original_weight_loader): ...
    @classmethod
    def get_nixl_supported_devices(cls) -> dict[str, tuple[str, ...]]: ...
    @classmethod
    def get_nixl_memory_type(cls) -> str | None: ...
    @classmethod
    def check_max_model_len(cls, max_model_len: int) -> int: ...
    @classmethod
    def set_additional_forward_context(cls, *args, **kwargs) -> dict[str, Any]: ...
    @classmethod
    def num_compute_units(cls, device_id: int = 0) -> int: ...

class UnspecifiedPlatform(Platform):
    device_type: str
