import dataclasses
from _typeshed import Incomplete
from collections.abc import Generator
from contextlib import contextmanager
from typing import Any

@dataclasses.dataclass
class CompilationCounter:
    num_models_seen: int = ...
    num_graphs_seen: int = ...
    num_piecewise_graphs_seen: int = ...
    num_piecewise_capturable_graphs_seen: int = ...
    num_backend_compilations: int = ...
    num_gpu_runner_capture_triggers: int = ...
    num_cudagraph_captured: int = ...
    num_inductor_compiles: int = ...
    num_eager_compiles: int = ...
    num_cache_entries_updated: int = ...
    num_compiled_artifacts_saved: int = ...
    num_compiled_artifacts_loaded: int = ...
    stock_torch_compile_count: int = ...
    def clone(self) -> CompilationCounter: ...
    @contextmanager
    def expect(self, **kwargs: Any) -> Generator[None, None, None]: ...

compilation_counter: Incomplete
