"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn

class MultiresConvDecoder(nn.Module):
    def __init__(self) -> None:
        ...
    
    def __call__(self, x0_latent: mx.array, x1_latent: mx.array, x0_features: mx.array, x1_features: mx.array, x_global_features: mx.array) -> mx.array:
        ...
    


