"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
import mlx.nn as nn

class ResidualBlock(nn.Module):
    def __init__(self, num_features: int) -> None:
        ...
    
    def __call__(self, x: mx.array) -> mx.array:
        ...
    


