import dataclasses
import socket
import torch
from _typeshed import Incomplete
from collections import deque
from collections.abc import Sequence
from datetime import timedelta
from torch.distributed import ProcessGroup, Store as Store
from torch.distributed.distributed_c10d import PrefixStore
from typing import Any
from vllm.logger import init_logger as init_logger
from vllm.utils.network_utils import get_tcp_uri as get_tcp_uri
from vllm.utils.system_utils import suppress_stdout as suppress_stdout

logger: Incomplete
USE_SCHED_YIELD: Incomplete

def sched_yield() -> None: ...
def ensure_divisibility(numerator, denominator) -> None: ...
def divide(numerator, denominator): ...
def split_tensor_along_last_dim(
    tensor: torch.Tensor, num_partitions: int, contiguous_split_chunks: bool = False
) -> Sequence[torch.Tensor]: ...
def get_pp_indices(
    num_hidden_layers: int, pp_rank: int, pp_size: int
) -> tuple[int, int]: ...
@dataclasses.dataclass
class StatelessProcessGroup:
    rank: int
    world_size: int
    store: torch._C._distributed_c10d.Store
    socket: socket.socket | None
    data_expiration_seconds: int = ...
    send_dst_counter: dict[int, int] = dataclasses.field(default_factory=dict)
    recv_src_counter: dict[int, int] = dataclasses.field(default_factory=dict)
    broadcast_send_counter: int = ...
    broadcast_recv_src_counter: dict[int, int] = dataclasses.field(default_factory=dict)
    entries: deque[tuple[str, float]] = dataclasses.field(default_factory=deque)
    def __post_init__(self) -> None: ...
    def send_obj(self, obj: Any, dst: int): ...
    def expire_data(self) -> None: ...
    def recv_obj(self, src: int) -> Any: ...
    def broadcast_obj(self, obj: Any | None, src: int) -> Any: ...
    def all_gather_obj(self, obj: Any) -> list[Any]: ...
    def broadcast(self, tensor: torch.Tensor, src: int) -> torch.Tensor: ...
    def send(self, tensor: torch.Tensor, dst: int): ...
    def recv(self, tensor: torch.Tensor, src: int) -> torch.Tensor: ...
    def all_reduce(self, tensor: torch.Tensor, op=...) -> torch.Tensor: ...
    def barrier(self, timeout: float = 30.0): ...
    @staticmethod
    def create(
        host: str,
        port: int,
        rank: int,
        world_size: int,
        data_expiration_seconds: int = 3600,
        store_timeout: int = 300,
    ) -> StatelessProcessGroup: ...

def init_gloo_process_group(
    prefix_store: PrefixStore, group_rank: int, group_size: int, timeout: timedelta
) -> ProcessGroup: ...
def stateless_init_torch_distributed_process_group(
    host: str,
    port: int,
    rank: int,
    world_size: int,
    backend: str,
    group_name: str | None = None,
    return_store: bool = False,
) -> ProcessGroup | tuple[ProcessGroup, Store]: ...
def stateless_destroy_torch_distributed_process_group(pg: ProcessGroup) -> None: ...
def get_worker_rank_suffix(global_rank: int | None = None) -> str: ...
