from typing import Any, Self

class safe_open:
    def __init__(self, filename: str, framework: str = "pt") -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...
    def keys(self) -> list[str]: ...
    def get_tensor(self, name: str) -> Any: ...
