"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenTimestepEmbedding(nn.Module):
    def __init__(self, proj_dim: int, inner_dim: int) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
