"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from mflux.callbacks.callback import AfterLoopCallback, BeforeLoopCallback, InLoopCallback, InterruptCallback
from mflux.callbacks.generation_context import GenerationContext
from mflux.models.common.config.config import Config

if TYPE_CHECKING:
    ...
class CallbackRegistry:
    def __init__(self) -> None:
        ...
    
    def register(self, callback) -> None:
        ...
    
    def start(self, seed: int, prompt: str, config: Config) -> GenerationContext:
        ...
    
    def before_loop_callbacks(self) -> list[BeforeLoopCallback]:
        ...
    
    def in_loop_callbacks(self) -> list[InLoopCallback]:
        ...
    
    def after_loop_callbacks(self) -> list[AfterLoopCallback]:
        ...
    
    def interrupt_callbacks(self) -> list[InterruptCallback]:
        ...
    


