import torch
from _typeshed import Incomplete
from cutlass.base_dsl.typing import JitArgument
from dataclasses import dataclass
from functools import lru_cache

StaticTypes: Incomplete
load_cubin_module_data_og: Incomplete
cute_compile_og: Incomplete
torch2cute_dtype_map: Incomplete

@lru_cache
def get_max_active_clusters(cluster_size): ...
@lru_cache
def get_device_capacity(device: torch.device = None) -> tuple[int, int]: ...
@dataclass
class ParamsBase:
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

@dataclass
class ArgumentsBase(JitArgument):
    def __c_pointers__(self): ...
    def __get_mlir_types__(self): ...
    def __new_from_mlir_values__(self, values): ...

def load_cubin_module_data_patched(cubin_data, filepath): ...
def cute_compile_patched(*args, **kwargs): ...
def assume_strides_aligned(t): ...
def assume_tensor_aligned(t): ...
def to_cute_tensor(
    t,
    assumed_align: int = 16,
    leading_dim: int = -1,
    fully_dynamic: bool = False,
    enable_tvm_ffi: bool = True,
): ...
def get_broadcast_dims(tensor: torch.Tensor) -> tuple[bool, ...]: ...
