import enum

class NamedBarrierFwd(enum.IntEnum):
    Epilogue = ...
    WarpSchedulerWG1 = ...
    WarpSchedulerWG2 = ...
    WarpSchedulerWG3 = ...
    PFull = ...
    PEmpty = ...

class NamedBarrierBwd(enum.IntEnum):
    Epilogue = ...
    WarpSchedulerWG1 = ...
    WarpSchedulerWG2 = ...
    WarpSchedulerWG3 = ...
    PdS = ...
    dQFullWG0 = ...
    dQFullWG1 = ...
    dQEmptyWG0 = ...
    dQEmptyWG1 = ...

class NamedBarrierBwdSm100(enum.IntEnum):
    EpilogueWG1 = ...
    EpilogueWG2 = ...
    Compute = ...
    dQaccReduce = ...
