import cutlass
import cutlass.cute as cute
from _typeshed import Incomplete
from cutlass import Int32
from cutlass._mlir import ir as ir
from cutlass.cute import FastDivmodDivisor
from dataclasses import dataclass
from typing_extensions import override
from vllm.vllm_flash_attn.cute.fast_math import clz as clz

class WorkTileInfo(cutlass.utils.WorkTileInfo):
    @override
    def __new_from_mlir_values__(self, values: list[ir.Value]) -> WorkTileInfo: ...

@dataclass
class ParamsBase:
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

@dataclass
class TileSchedulerArguments(ParamsBase):
    num_block: Int32
    num_head: Int32
    num_batch: Int32
    num_splits: Int32
    seqlen_k: Int32
    headdim: Int32
    headdim_v: Int32
    total_q: Int32
    tile_shape_mn: cutlass.Constexpr[tuple[int, int]]
    cluster_shape_mn: cutlass.Constexpr[tuple[int, int]] = ...
    mCuSeqlensQ: cute.Tensor | None = ...
    mSeqUsedQ: cute.Tensor | None = ...
    qhead_per_kvhead_packgqa: cutlass.Constexpr[int] = ...
    element_size: cutlass.Constexpr[int] = ...
    is_persistent: cutlass.Constexpr[bool] = ...
    lpt: cutlass.Constexpr[bool] = ...
    is_split_kv: cutlass.Constexpr[bool] = ...
    head_swizzle: cutlass.Constexpr[bool] = ...

class SingleTileScheduler:
    @dataclass
    class Params(ParamsBase):
        num_block: Int32
        num_head: Int32
        num_batch: Int32
        num_splits: Int32
        num_splits_divmod: FastDivmodDivisor
        is_split_kv: cutlass.Constexpr[bool] = ...
        cluster_shape_mn: cutlass.Constexpr[tuple[int, int]] = ...
        @staticmethod
        def create(
            args: TileSchedulerArguments, *, loc=None, ip=None
        ) -> SingleTileScheduler.Params: ...

    params: Incomplete
    def __init__(
        self, params: Params, blk_coord: cute.Coord, *, loc=None, ip=None
    ) -> None: ...
    @staticmethod
    def to_underlying_arguments(
        args: TileSchedulerArguments, *, loc=None, ip=None
    ) -> Params: ...
    @staticmethod
    def create(params: Params, *, loc=None, ip=None) -> SingleTileScheduler: ...
    @staticmethod
    def get_grid_shape(
        params: Params, *, loc=None, ip=None
    ) -> tuple[Int32, Int32, Int32]: ...
    def get_current_work(self, *, loc=None, ip=None) -> WorkTileInfo: ...
    def initial_work_tile_info(self, *, loc=None, ip=None): ...
    def prefetch_next_work(self, *, loc=None, ip=None) -> None: ...
    def advance_to_next_work(self, *, loc=None, ip=None) -> None: ...
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

class StaticPersistentTileScheduler:
    @dataclass
    class Params(ParamsBase):
        num_block_divmod: FastDivmodDivisor
        num_head_divmod: FastDivmodDivisor
        total_blocks: Int32
        @staticmethod
        def create(
            args: TileSchedulerArguments, *, loc=None, ip=None
        ) -> StaticPersistentTileScheduler.Params: ...

    params: Incomplete
    def __init__(
        self, params: Params, tile_idx: Int32, *, loc=None, ip=None
    ) -> None: ...
    @staticmethod
    def to_underlying_arguments(
        args: TileSchedulerArguments, *, loc=None, ip=None
    ) -> Params: ...
    @staticmethod
    def create(
        params: Params, *, loc=None, ip=None
    ) -> StaticPersistentTileScheduler: ...
    @staticmethod
    def get_grid_shape(
        params: Params, *, loc=None, ip=None
    ) -> tuple[Int32, Int32, Int32]: ...
    def get_current_work(self, *, loc=None, ip=None) -> WorkTileInfo: ...
    def initial_work_tile_info(self, *, loc=None, ip=None): ...
    def prefetch_next_work(self, *, loc=None, ip=None) -> None: ...
    def advance_to_next_work(self, *, loc=None, ip=None) -> None: ...
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

class SingleTileLPTScheduler:
    @dataclass
    class Params(ParamsBase):
        total_blocks: Int32
        num_splits: Int32
        num_block: Int32
        l2_minor: Int32
        num_block_divmod: FastDivmodDivisor
        num_head_divmod: FastDivmodDivisor
        l2_minor_divmod: FastDivmodDivisor
        l2_major_divmod: FastDivmodDivisor
        l2_minor_residual_divmod: FastDivmodDivisor
        num_hb_quotient: Int32
        is_split_kv: cutlass.Constexpr[bool] = ...
        @staticmethod
        @cute.jit
        def create(
            args: TileSchedulerArguments, *, loc=None, ip=None
        ) -> SingleTileLPTScheduler.Params: ...

    params: Incomplete
    def __init__(
        self, params: Params, tile_idx: Int32, split_idx: Int32, *, loc=None, ip=None
    ) -> None: ...
    @staticmethod
    def to_underlying_arguments(
        args: TileSchedulerArguments, *, loc=None, ip=None
    ) -> Params: ...
    @staticmethod
    @cute.jit
    def create(params: Params, *, loc=None, ip=None) -> SingleTileLPTScheduler: ...
    @staticmethod
    def get_grid_shape(
        params: Params, *, loc=None, ip=None
    ) -> tuple[Int32, Int32, Int32]: ...
    @cute.jit
    def get_current_work(self, *, loc=None, ip=None) -> WorkTileInfo: ...
    def initial_work_tile_info(self, *, loc=None, ip=None): ...
    def prefetch_next_work(self, *, loc=None, ip=None) -> None: ...
    def advance_to_next_work(self, *, loc=None, ip=None) -> None: ...
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

class SingleTileLPTBwdScheduler:
    @dataclass
    class Params(ParamsBase):
        total_blocks: Int32
        num_block: Int32
        l2_minor: Int32
        num_head_divmod: FastDivmodDivisor
        l2_minor_divmod: FastDivmodDivisor
        l2_major_divmod: FastDivmodDivisor
        l2_minor_residual_divmod: FastDivmodDivisor
        num_hb_quotient: Int32
        cluster_shape_mn: cutlass.Constexpr[tuple[int, int]] = ...
        spt: cutlass.Constexpr[bool] = ...
        @staticmethod
        @cute.jit
        def create(
            args: TileSchedulerArguments, *, loc=None, ip=None
        ) -> SingleTileLPTBwdScheduler.Params: ...

    params: Incomplete
    def __init__(
        self, params: Params, tile_idx: Int32, *, loc=None, ip=None
    ) -> None: ...
    @staticmethod
    def to_underlying_arguments(
        args: TileSchedulerArguments, *, loc=None, ip=None
    ) -> Params: ...
    @staticmethod
    @cute.jit
    def create(params: Params, *, loc=None, ip=None) -> SingleTileLPTBwdScheduler: ...
    @staticmethod
    def get_grid_shape(
        params: Params, *, loc=None, ip=None
    ) -> tuple[Int32, Int32, Int32]: ...
    @cute.jit
    def get_current_work(self, *, loc=None, ip=None) -> cutlass.utils.WorkTileInfo: ...
    def initial_work_tile_info(self, *, loc=None, ip=None): ...
    def prefetch_next_work(self, *, loc=None, ip=None) -> None: ...
    def advance_to_next_work(self, *, loc=None, ip=None) -> None: ...
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...

class SingleTileVarlenScheduler:
    @dataclass
    class Params(ParamsBase):
        num_head: Int32
        num_batch: Int32
        total_q: Int32
        num_splits: Int32
        max_kvblock_in_l2: Int32
        tile_shape_mn: cutlass.Constexpr[tuple[int, int]]
        mCuSeqlensQ: cute.Tensor | None = ...
        mSeqUsedQ: cute.Tensor | None = ...
        qhead_per_kvhead_packgqa: cutlass.Constexpr[int] = ...
        lpt: cutlass.Constexpr[bool] = ...
        is_split_kv: cutlass.Constexpr[bool] = ...
        head_swizzle: cutlass.Constexpr[bool] = ...
        @staticmethod
        @cute.jit
        def create(
            args: TileSchedulerArguments, *, loc=None, ip=None
        ) -> SingleTileVarlenScheduler.Params: ...

    params: Incomplete
    def __init__(
        self, params: Params, tile_idx: Int32, split_idx: Int32, *, loc=None, ip=None
    ) -> None: ...
    @staticmethod
    def to_underlying_arguments(
        args: TileSchedulerArguments, *, loc=None, ip=None
    ) -> Params: ...
    @staticmethod
    def create(params: Params, *, loc=None, ip=None) -> SingleTileVarlenScheduler: ...
    @staticmethod
    def get_grid_shape(
        params: Params, *, loc=None, ip=None
    ) -> tuple[Int32, Int32, Int32]: ...
    @cute.jit
    def get_current_work(self, *, loc=None, ip=None) -> WorkTileInfo: ...
    def initial_work_tile_info(self, *, loc=None, ip=None): ...
    def prefetch_next_work(self, *, loc=None, ip=None) -> None: ...
    def advance_to_next_work(self, *, loc=None, ip=None) -> None: ...
    def __extract_mlir_values__(self): ...
    def __new_from_mlir_values__(self, values): ...
