"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenImageMidBlock3D(nn.Module):
    def __init__(self, dim: int, num_layers: int = ...) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
