"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenImageRMSNorm(nn.Module):
    def __init__(self, num_channels: int, eps: float = ..., images: bool = ...) -> None:
        ...
    
    def __call__(self, x: mx.array) -> mx.array:
        ...
    


