"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from mlx import nn

class QwenImageResBlock3D(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None: ...
    def __call__(self, x: mx.array) -> mx.array: ...
