import torch
from vllm.multimodal.inputs import MultiModalFeatureSpec as MultiModalFeatureSpec

class EncoderCache:
    mm_features: dict[str, list[MultiModalFeatureSpec]]
    encoder_outputs: dict[str, torch.Tensor]
    def __init__(self) -> None: ...
    def add_request(
        self, req_id: str, mm_features: list[MultiModalFeatureSpec]
    ) -> None: ...
    def remove_request(self, req_id: str) -> None: ...
    def reset_mm_cache(self) -> None: ...
    def reset_encoder_cache(self) -> None: ...
    def free_encoder_cache(self, mm_hash: str) -> None: ...
