import torch
from collections.abc import Callable as Callable
from torch._dynamo import disable as _dynamo_disable

@_dynamo_disable
def is_oink_available_for_device(device_index: int) -> bool: ...
def has_fused_add_rms_norm() -> bool: ...
def rmsnorm(x: torch.Tensor, weight: torch.Tensor, eps: float) -> torch.Tensor: ...
def fused_add_rms_norm_(
    x: torch.Tensor, residual: torch.Tensor, weight: torch.Tensor, eps: float
) -> None: ...
def fused_add_rms_norm(
    x: torch.Tensor, residual: torch.Tensor, weight: torch.Tensor, eps: float
) -> tuple[torch.Tensor, torch.Tensor]: ...
