from _typeshed import Incomplete
from collections.abc import Callable as Callable
from typing import Any, Literal

VLLM_HOST_IP: str
VLLM_PORT: int | None
VLLM_RPC_BASE_PATH: str
VLLM_USE_MODELSCOPE: bool
VLLM_RINGBUFFER_WARNING_INTERVAL: int
VLLM_NCCL_SO_PATH: str | None
LD_LIBRARY_PATH: str | None
VLLM_ROCM_SLEEP_MEM_CHUNK_SIZE: int
LOCAL_RANK: int
CUDA_VISIBLE_DEVICES: str | None
VLLM_ENGINE_ITERATION_TIMEOUT_S: int
VLLM_ENGINE_READY_TIMEOUT_S: int
VLLM_API_KEY: str | None
VLLM_DEBUG_LOG_API_SERVER_RESPONSE: bool
S3_ACCESS_KEY_ID: str | None
S3_SECRET_ACCESS_KEY: str | None
S3_ENDPOINT_URL: str | None
VLLM_MODEL_REDIRECT_PATH: str | None
VLLM_CACHE_ROOT: str
VLLM_CONFIG_ROOT: str
VLLM_USAGE_STATS_SERVER: str
VLLM_NO_USAGE_STATS: bool
VLLM_DO_NOT_TRACK: bool
VLLM_USAGE_SOURCE: str
VLLM_CONFIGURE_LOGGING: bool
VLLM_LOGGING_LEVEL: str
VLLM_LOGGING_PREFIX: str
VLLM_LOGGING_STREAM: str
VLLM_LOGGING_CONFIG_PATH: str | None
VLLM_LOGGING_COLOR: str
NO_COLOR: bool
VLLM_LOG_STATS_INTERVAL: float
VLLM_TRACE_FUNCTION: int
VLLM_USE_FLASHINFER_SAMPLER: bool | None
VLLM_PP_LAYER_PARTITION: str | None
VLLM_CPU_KVCACHE_SPACE: int | None
VLLM_CPU_OMP_THREADS_BIND: str
VLLM_CPU_NUM_OF_RESERVED_CPU: int | None
VLLM_CPU_SGL_KERNEL: bool
VLLM_XLA_CACHE_PATH: str
VLLM_XLA_CHECK_RECOMPILATION: bool
VLLM_FUSED_MOE_CHUNK_SIZE: int
VLLM_ENABLE_FUSED_MOE_ACTIVATION_CHUNKING: bool
VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE: Literal["auto", "nccl", "shm"]
VLLM_USE_RAY_COMPILED_DAG_OVERLAP_COMM: bool
VLLM_USE_RAY_WRAPPED_PP_COMM: bool
VLLM_XLA_USE_SPMD: bool
VLLM_WORKER_MULTIPROC_METHOD: Literal["fork", "spawn"]
VLLM_ASSETS_CACHE: str
VLLM_ASSETS_CACHE_MODEL_CLEAN: bool
VLLM_IMAGE_FETCH_TIMEOUT: int
VLLM_VIDEO_FETCH_TIMEOUT: int
VLLM_AUDIO_FETCH_TIMEOUT: int
VLLM_MEDIA_URL_ALLOW_REDIRECTS: bool
VLLM_MEDIA_LOADING_THREAD_COUNT: int
VLLM_MAX_AUDIO_CLIP_FILESIZE_MB: int
VLLM_VIDEO_LOADER_BACKEND: str
VLLM_MEDIA_CONNECTOR: str
VLLM_MM_HASHER_ALGORITHM: str
VLLM_TARGET_DEVICE: str
VLLM_MAIN_CUDA_VERSION: str
VLLM_FLOAT32_MATMUL_PRECISION: Literal["highest", "high", "medium"]
MAX_JOBS: str | None
NVCC_THREADS: str | None
VLLM_USE_PRECOMPILED: bool
VLLM_SKIP_PRECOMPILED_VERSION_SUFFIX: bool
VLLM_DOCKER_BUILD_CONTEXT: bool
VLLM_KEEP_ALIVE_ON_ENGINE_DEATH: bool
CMAKE_BUILD_TYPE: Literal["Debug", "Release", "RelWithDebInfo"] | None
VERBOSE: bool
VLLM_ALLOW_LONG_MAX_MODEL_LEN: bool
VLLM_RPC_TIMEOUT: int
VLLM_HTTP_TIMEOUT_KEEP_ALIVE: int
VLLM_PLUGINS: list[str] | None
VLLM_LORA_RESOLVER_CACHE_DIR: str | None
VLLM_LORA_RESOLVER_HF_REPO_LIST: str | None
VLLM_USE_AOT_COMPILE: bool
VLLM_USE_BYTECODE_HOOK: bool
VLLM_FORCE_AOT_LOAD: bool
VLLM_USE_MEGA_AOT_ARTIFACT: bool
VLLM_USE_TRITON_AWQ: bool
VLLM_ALLOW_RUNTIME_LORA_UPDATING: bool
VLLM_SKIP_P2P_CHECK: bool
VLLM_DISABLED_KERNELS: list[str]
VLLM_DISABLE_PYNCCL: bool
VLLM_USE_OINK_OPS: bool
VLLM_ROCM_USE_AITER: bool
VLLM_ROCM_USE_AITER_PAGED_ATTN: bool
VLLM_ROCM_USE_AITER_LINEAR: bool
VLLM_ROCM_USE_AITER_MOE: bool
VLLM_ROCM_USE_AITER_RMSNORM: bool
VLLM_ROCM_USE_AITER_MLA: bool
VLLM_ROCM_USE_AITER_MHA: bool
VLLM_ROCM_USE_AITER_FP4_ASM_GEMM: bool
VLLM_ROCM_USE_AITER_TRITON_ROPE: bool
VLLM_ROCM_USE_AITER_FP8BMM: bool
VLLM_ROCM_USE_AITER_FP4BMM: bool
VLLM_ROCM_USE_AITER_UNIFIED_ATTENTION: bool
VLLM_ROCM_USE_AITER_FUSION_SHARED_EXPERTS: bool
VLLM_ROCM_USE_AITER_TRITON_GEMM: bool
VLLM_ROCM_USE_SKINNY_GEMM: bool
VLLM_ROCM_FP8_PADDING: bool
VLLM_ROCM_MOE_PADDING: bool
VLLM_ROCM_CUSTOM_PAGED_ATTN: bool
VLLM_ROCM_SHUFFLE_KV_CACHE_LAYOUT: bool
VLLM_ENABLE_V1_MULTIPROCESSING: bool
VLLM_LOG_BATCHSIZE_INTERVAL: float
VLLM_DISABLE_COMPILE_CACHE: bool
Q_SCALE_CONSTANT: int
K_SCALE_CONSTANT: int
V_SCALE_CONSTANT: int
VLLM_SERVER_DEV_MODE: bool
VLLM_V1_OUTPUT_PROC_CHUNK_SIZE: int
VLLM_MLA_DISABLE: bool
VLLM_RAY_PER_WORKER_GPUS: float
VLLM_RAY_BUNDLE_INDICES: str
VLLM_CUDART_SO_PATH: str | None
VLLM_DP_RANK: int
VLLM_DP_RANK_LOCAL: int
VLLM_DP_SIZE: int
VLLM_USE_STANDALONE_COMPILE: bool
VLLM_ENABLE_PREGRAD_PASSES: bool
VLLM_DP_MASTER_IP: str
VLLM_DP_MASTER_PORT: int
VLLM_MOE_DP_CHUNK_SIZE: int
VLLM_ENABLE_MOE_DP_CHUNK: bool
VLLM_RANDOMIZE_DP_DUMMY_INPUTS: bool
VLLM_RAY_DP_PACK_STRATEGY: Literal["strict", "fill", "span"]
VLLM_RAY_EXTRA_ENV_VAR_PREFIXES_TO_COPY: str
VLLM_RAY_EXTRA_ENV_VARS_TO_COPY: str
VLLM_MARLIN_USE_ATOMIC_ADD: bool
VLLM_MARLIN_INPUT_DTYPE: Literal["int8", "fp8"] | None
VLLM_MXFP4_USE_MARLIN: bool | None
VLLM_DEEPEPLL_NVFP4_DISPATCH: bool
VLLM_V1_USE_OUTLINES_CACHE: bool
VLLM_TPU_BUCKET_PADDING_GAP: int
VLLM_TPU_MOST_MODEL_LEN: int | None
VLLM_TPU_USING_PATHWAYS: bool
VLLM_USE_DEEP_GEMM: bool
VLLM_MOE_USE_DEEP_GEMM: bool
VLLM_USE_DEEP_GEMM_E8M0: bool
VLLM_USE_DEEP_GEMM_TMA_ALIGNED_SCALES: bool
VLLM_DEEP_GEMM_WARMUP: Literal["skip", "full", "relax"]
VLLM_USE_FUSED_MOE_GROUPED_TOPK: bool
VLLM_BLOCKSCALE_FP8_GEMM_FLASHINFER: bool
VLLM_USE_FLASHINFER_MOE_FP16: bool
VLLM_USE_FLASHINFER_MOE_FP8: bool
VLLM_USE_FLASHINFER_MOE_FP4: bool
VLLM_USE_FLASHINFER_MOE_INT4: bool
VLLM_FLASHINFER_MOE_BACKEND: Literal["throughput", "latency", "masked_gemm"]
VLLM_FLASHINFER_ALLREDUCE_BACKEND: Literal["auto", "trtllm", "mnnvl"]
VLLM_FLASHINFER_WORKSPACE_BUFFER_SIZE: int
VLLM_XGRAMMAR_CACHE_MB: int
VLLM_MSGPACK_ZERO_COPY_THRESHOLD: int
VLLM_ALLOW_INSECURE_SERIALIZATION: bool
VLLM_DISABLE_REQUEST_ID_RANDOMIZATION: bool
VLLM_NIXL_SIDE_CHANNEL_HOST: str
VLLM_NIXL_SIDE_CHANNEL_PORT: int
VLLM_MOONCAKE_BOOTSTRAP_PORT: int
VLLM_MAX_TOKENS_PER_EXPERT_FP4_MOE: int
VLLM_TOOL_PARSE_REGEX_TIMEOUT_SECONDS: int
VLLM_MQ_MAX_CHUNK_BYTES_MB: int
VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS: int
VLLM_KV_CACHE_LAYOUT: Literal["NHD", "HND"] | None
VLLM_COMPUTE_NANS_IN_LOGITS: bool
VLLM_USE_NVFP4_CT_EMULATIONS: bool
VLLM_ROCM_QUICK_REDUCE_QUANTIZATION: Literal["FP", "INT8", "INT6", "INT4", "NONE"]
VLLM_ROCM_QUICK_REDUCE_CAST_BF16_TO_FP16: bool
VLLM_ROCM_QUICK_REDUCE_MAX_SIZE_BYTES_MB: int | None
VLLM_NIXL_ABORT_REQUEST_TIMEOUT: int
VLLM_MORIIO_CONNECTOR_READ_MODE: bool
VLLM_MORIIO_QP_PER_TRANSFER: int
VLLM_MORIIO_POST_BATCH_SIZE: int
VLLM_MORIIO_NUM_WORKERS: int
VLLM_MOONCAKE_ABORT_REQUEST_TIMEOUT: int
VLLM_ENABLE_CUDAGRAPH_GC: bool
VLLM_LOOPBACK_IP: str
VLLM_ALLOW_CHUNKED_LOCAL_ATTN_WITH_HYBRID_KV_CACHE: bool
VLLM_ENABLE_RESPONSES_API_STORE: bool
VLLM_NVFP4_GEMM_BACKEND: str | None
VLLM_HAS_FLASHINFER_CUBIN: bool
VLLM_USE_FLASHINFER_MOE_MXFP4_MXFP8: bool
VLLM_USE_FLASHINFER_MOE_MXFP4_BF16: bool
VLLM_ROCM_FP8_MFMA_PAGE_ATTN: bool
VLLM_USE_FLASHINFER_MOE_MXFP4_MXFP8_CUTLASS: bool
VLLM_ALLREDUCE_USE_SYMM_MEM: bool
VLLM_ALLREDUCE_USE_FLASHINFER: bool
VLLM_TUNED_CONFIG_FOLDER: str | None
VLLM_GPT_OSS_SYSTEM_TOOL_MCP_LABELS: set[str]
VLLM_USE_EXPERIMENTAL_PARSER_CONTEXT: bool
VLLM_GPT_OSS_HARMONY_SYSTEM_INSTRUCTIONS: bool
VLLM_SYSTEM_START_DATE: str | None
VLLM_TOOL_JSON_ERROR_AUTOMATIC_RETRY: bool
VLLM_CUSTOM_SCOPES_FOR_PROFILING: bool
VLLM_NVTX_SCOPES_FOR_PROFILING: bool
VLLM_KV_EVENTS_USE_INT_BLOCK_HASHES: bool
VLLM_OBJECT_STORAGE_SHM_BUFFER_NAME: str
VLLM_DEEPEP_BUFFER_SIZE_MB: int
VLLM_DEEPEP_HIGH_THROUGHPUT_FORCE_INTRA_NODE: bool
VLLM_DEEPEP_LOW_LATENCY_USE_MNNVL: bool
VLLM_DBO_COMM_SMS: int
VLLM_PATTERN_MATCH_DEBUG: str | None
VLLM_DEBUG_DUMP_PATH: str | None
VLLM_ENABLE_INDUCTOR_MAX_AUTOTUNE: bool
VLLM_ENABLE_INDUCTOR_COORDINATE_DESCENT_TUNING: bool
VLLM_USE_NCCL_SYMM_MEM: bool
VLLM_NCCL_INCLUDE_PATH: str | None
VLLM_USE_FBGEMM: bool
VLLM_GC_DEBUG: str
VLLM_DEBUG_WORKSPACE: bool
VLLM_DISABLE_SHARED_EXPERTS_STREAM: bool
VLLM_SHARED_EXPERTS_STREAM_TOKEN_THRESHOLD: int
VLLM_COMPILE_CACHE_SAVE_FORMAT: Literal["binary", "unpacked"]
VLLM_USE_V2_MODEL_RUNNER: bool
VLLM_LOG_MODEL_INSPECTION: bool
VLLM_DEBUG_MFU_METRICS: bool
VLLM_WEIGHT_OFFLOADING_DISABLE_PIN_MEMORY: bool
VLLM_WEIGHT_OFFLOADING_DISABLE_UVA: bool
VLLM_DISABLE_LOG_LOGO: bool
VLLM_LORA_DISABLE_PDL: bool
VLLM_ENABLE_CUDA_COMPATIBILITY: bool
VLLM_CUDA_COMPATIBILITY_PATH: str | None
VLLM_ELASTIC_EP_SCALE_UP_LAUNCH: bool
VLLM_ELASTIC_EP_DRAIN_REQUESTS: bool
VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS: bool

def get_default_cache_root(): ...
def get_default_config_root(): ...
def maybe_convert_int(value: str | None) -> int | None: ...
def maybe_convert_bool(value: str | None) -> bool | None: ...
def disable_compile_cache() -> bool: ...
def use_aot_compile() -> bool: ...
def env_with_choices(
    env_name: str,
    default: str | None,
    choices: list[str] | Callable[[], list[str]],
    case_sensitive: bool = True,
) -> Callable[[], str | None]: ...
def env_list_with_choices(
    env_name: str,
    default: list[str],
    choices: list[str] | Callable[[], list[str]],
    case_sensitive: bool = True,
) -> Callable[[], list[str]]: ...
def env_set_with_choices(
    env_name: str,
    default: list[str],
    choices: list[str] | Callable[[], list[str]],
    case_sensitive: bool = True,
) -> Callable[[], set[str]]: ...
def get_vllm_port() -> int | None: ...
def get_env_or_set_default(
    env_name: str, default_factory: Callable[[], str]
) -> Callable[[], str]: ...

logger: Incomplete
environment_variables: dict[str, Callable[[], Any]]

def __getattr__(name: str): ...
def enable_envs_cache() -> None: ...
def disable_envs_cache() -> None: ...
def __dir__(): ...
def is_set(name: str): ...
def validate_environ(hard_fail: bool) -> None: ...
def compile_factors() -> dict[str, object]: ...
