import msgspec
from typing import Any
from vllm.config import ModelConfig as ModelConfig, PoolerConfig as PoolerConfig
from vllm.sampling_params import RequestOutputKind as RequestOutputKind
from vllm.tasks import PoolingTask as PoolingTask

class LateInteractionParams(msgspec.Struct, omit_defaults=True, array_like=True):
    mode: str
    query_key: str
    query_uses: int | None = ...

class PoolingParams(msgspec.Struct, omit_defaults=True, array_like=True):
    use_activation: bool | None = ...
    dimensions: int | None = ...
    step_tag_id: int | None = ...
    returned_token_ids: list[int] | None = ...
    task: PoolingTask | None = ...
    requires_token_ids: bool = ...
    skip_reading_prefix_cache: bool | None = ...
    late_interaction_params: LateInteractionParams | None = ...
    extra_kwargs: dict[str, Any] | None = ...
    output_kind: RequestOutputKind = ...
    @property
    def all_parameters(self) -> list[str]: ...
    @property
    def valid_parameters(self): ...
    def clone(self) -> PoolingParams: ...
    def verify(self, model_config: ModelConfig) -> None: ...
    def __post_init__(self) -> None: ...
