import msgspec
from _typeshed import Incomplete
from enum import Enum, IntEnum
from functools import cached_property as cached_property
from typing import Any
from vllm.config import (
    ModelConfig as ModelConfig,
    SpeculativeConfig as SpeculativeConfig,
    StructuredOutputsConfig as StructuredOutputsConfig,
)
from vllm.exceptions import VLLMValidationError as VLLMValidationError
from vllm.logger import init_logger as init_logger
from vllm.tokenizers import TokenizerLike as TokenizerLike
from vllm.utils.mistral import is_mistral_tokenizer as is_mistral_tokenizer
from vllm.v1.serial_utils import PydanticMsgspecMixin as PydanticMsgspecMixin

logger: Incomplete

class SamplingType(IntEnum):
    GREEDY = 0
    RANDOM = 1
    RANDOM_SEED = 2

class StructuredOutputsParams:
    json: str | dict | None
    regex: str | None
    choice: list[str] | None
    grammar: str | None
    json_object: bool | None
    disable_any_whitespace: bool
    disable_additional_properties: bool
    whitespace_pattern: str | None
    structural_tag: str | None
    def __post_init__(self) -> None: ...
    def all_constraints_none(self) -> bool: ...
    def all_non_structural_tag_constraints_none(self) -> bool: ...

class RepetitionDetectionParams:
    max_pattern_size: int
    min_pattern_size: int
    min_count: int
    def __post_init__(self) -> None: ...

class RequestOutputKind(Enum):
    CUMULATIVE = 0
    DELTA = 1
    FINAL_ONLY = 2

class SamplingParams(
    PydanticMsgspecMixin, msgspec.Struct, omit_defaults=True, dict=True
):
    n: int = ...
    presence_penalty: float = ...
    frequency_penalty: float = ...
    repetition_penalty: float = ...
    temperature: float = ...
    top_p: float = ...
    top_k: int = ...
    min_p: float = ...
    seed: int | None = ...
    stop: str | list[str] | None = ...
    stop_token_ids: list[int] | None = ...
    ignore_eos: bool = ...
    max_tokens: int | None = ...
    min_tokens: int = ...
    logprobs: int | None = ...
    prompt_logprobs: int | None = ...
    flat_logprobs: bool = ...
    detokenize: bool = ...
    skip_special_tokens: bool = ...
    spaces_between_special_tokens: bool = ...
    include_stop_str_in_output: bool = ...
    output_kind: RequestOutputKind = ...
    skip_clone: bool = ...
    output_text_buffer_length: int = ...
    structured_outputs: StructuredOutputsParams | None = ...
    logit_bias: dict[int, float] | None = ...
    allowed_token_ids: list[int] | None = ...
    extra_args: dict[str, Any] | None = ...
    bad_words: list[str] | None = ...
    skip_reading_prefix_cache: bool | None = ...
    repetition_detection: RepetitionDetectionParams | None = ...
    @staticmethod
    def from_optional(
        n: int | None = 1,
        presence_penalty: float | None = 0.0,
        frequency_penalty: float | None = 0.0,
        repetition_penalty: float | None = 1.0,
        temperature: float | None = 1.0,
        top_p: float | None = 1.0,
        top_k: int = 0,
        min_p: float = 0.0,
        seed: int | None = None,
        stop: str | list[str] | None = None,
        stop_token_ids: list[int] | None = None,
        bad_words: list[str] | None = None,
        include_stop_str_in_output: bool = False,
        ignore_eos: bool = False,
        max_tokens: int | None = 16,
        min_tokens: int = 0,
        logprobs: int | None = None,
        prompt_logprobs: int | None = None,
        detokenize: bool = True,
        skip_special_tokens: bool = True,
        spaces_between_special_tokens: bool = True,
        output_kind: RequestOutputKind = ...,
        structured_outputs: StructuredOutputsParams | None = None,
        logit_bias: dict[int, float] | dict[str, float] | None = None,
        allowed_token_ids: list[int] | None = None,
        extra_args: dict[str, Any] | None = None,
        skip_clone: bool = False,
        repetition_detection: RepetitionDetectionParams | None = None,
    ) -> SamplingParams: ...
    def __post_init__(self) -> None: ...
    def update_from_generation_config(
        self, generation_config: dict[str, Any], eos_token_id: int | None = None
    ) -> None: ...
    def update_from_tokenizer(self, tokenizer: TokenizerLike) -> None: ...
    @cached_property
    def sampling_type(self) -> SamplingType: ...
    @property
    def eos_token_id(self) -> int | None: ...
    @property
    def all_stop_token_ids(self) -> set[int]: ...
    @property
    def bad_words_token_ids(self) -> list[list[int]] | None: ...
    def clone(self) -> SamplingParams: ...
    def verify(
        self,
        model_config: ModelConfig,
        speculative_config: SpeculativeConfig | None,
        structured_outputs_config: StructuredOutputsConfig | None,
        tokenizer: TokenizerLike | None,
    ) -> None: ...
    @staticmethod
    def for_sampler_warmup() -> SamplingParams: ...

class BeamSearchParams(msgspec.Struct, omit_defaults=True, dict=True):
    beam_width: int
    max_tokens: int
    ignore_eos: bool = ...
    temperature: float = ...
    length_penalty: float = ...
    include_stop_str_in_output: bool = ...
