"""
This type stub file was generated by pyright.
"""

from functools import partial
from typing import Callable

import mlx.core as mx
import mlx.nn as nn

class QuantizedSwitchLinear(nn.Module):
    weight: mx.array
    scales: mx.array
    biases: mx.array
    bias: mx.array | None
    group_size: int
    bits: int
    mode: str

    def __init__(
        self,
        input_dims: int,
        output_dims: int,
        num_experts: int,
        bias: bool = ...,
        group_size: int = ...,
        bits: int = ...,
        mode: str = ...,
    ) -> None: ...
    @property
    def input_dims(self) -> int: ...
    @property
    def output_dims(self) -> int: ...
    @property
    def num_experts(self) -> int: ...
    def __call__(
        self, x: mx.array, indices: mx.array, sorted_indices: bool = ...
    ) -> mx.array: ...

class SwitchLinear(nn.Module):
    weight: mx.array
    bias: mx.array | None

    def __init__(
        self, input_dims: int, output_dims: int, num_experts: int, bias: bool = ...
    ) -> None: ...
    @property
    def input_dims(self) -> int: ...
    @property
    def output_dims(self) -> int: ...
    @property
    def num_experts(self) -> int: ...
    def __call__(
        self, x: mx.array, indices: mx.array, sorted_indices: bool = ...
    ) -> mx.array: ...
    def to_quantized(
        self, group_size: int = ..., bits: int = ..., mode: str = ...
    ) -> QuantizedSwitchLinear: ...

@partial(mx.compile, shapeless=True)
def swiglu(x: mx.array, gate: mx.array) -> mx.array: ...
def _gather_sort(
    x: mx.array, indices: mx.array
) -> tuple[mx.array, mx.array, mx.array]: ...
def _scatter_unsort(
    x: mx.array, inv_order: mx.array, shape: tuple[int, ...]
) -> mx.array: ...

class SwiGLU(nn.Module):
    def __init__(self) -> None: ...
    def __call__(self, x: mx.array, gate: mx.array) -> mx.array: ...

class SwitchGLU(nn.Module):
    gate_proj: SwitchLinear
    up_proj: SwitchLinear
    down_proj: SwitchLinear
    activation: SwiGLU

    def __init__(
        self,
        input_dims: int,
        hidden_dims: int,
        num_experts: int,
        activation: object = ...,
        bias: bool = ...,
    ) -> None: ...
    def __call__(self, x: mx.array, indices: mx.array) -> mx.array: ...

class SwitchMLP(nn.Module):
    fc1: SwitchLinear
    fc2: SwitchLinear
    activation: Callable[[mx.array], mx.array]

    def __init__(
        self,
        input_dims: int,
        hidden_dims: int,
        num_experts: int,
        activation: object = ...,
        bias: bool = ...,
    ) -> None: ...
    def __call__(self, x: mx.array, indices: mx.array) -> mx.array: ...
