import argparse
import contextlib
import torch
from _typeshed import Incomplete
from collections.abc import Generator, MutableMapping
from dataclasses import dataclass, field
from tensorizer import (
    DecryptionParams as DecryptionParams,
    EncryptionParams as EncryptionParams,
    TensorDeserializer as TensorDeserializer,
    TensorSerializer as TensorSerializer,
)
from tensorizer.stream_io import open_stream as open_stream
from tensorizer.utils import (
    convert_bytes as convert_bytes,
    get_mem_usage as get_mem_usage,
    no_init_or_tensor as no_init_or_tensor,
)
from torch.utils._python_dispatch import TorchDispatchMode
from transformers import PretrainedConfig
from typing import Any
from vllm.config import ModelConfig, ParallelConfig
from vllm.utils.argparse_utils import FlexibleArgumentParser

__all__ = [
    "EncryptionParams",
    "DecryptionParams",
    "TensorDeserializer",
    "TensorSerializer",
    "open_stream",
    "convert_bytes",
    "get_mem_usage",
    "no_init_or_tensor",
    "TensorizerConfig",
]

class MetaTensorMode(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None): ...

class _NoInitOrTensorImpl:
    is_active: Incomplete
    @classmethod
    @contextlib.contextmanager
    def context_manager(cls) -> Generator[None]: ...

@dataclass
class TensorizerConfig(MutableMapping):
    tensorizer_uri: str | None = ...
    tensorizer_dir: str | None = ...
    vllm_tensorized: bool | None = ...
    verify_hash: bool | None = ...
    num_readers: int | None = ...
    encryption_keyfile: str | None = ...
    s3_access_key_id: str | None = ...
    s3_secret_access_key: str | None = ...
    s3_endpoint: str | None = ...
    lora_dir: str | None = ...
    stream_kwargs: dict[str, Any] | None = ...
    serialization_kwargs: dict[str, Any] | None = ...
    deserialization_kwargs: dict[str, Any] | None = ...
    model_class: type[torch.nn.Module] | None = field(init=False, default=None)
    hf_config: PretrainedConfig | None = field(init=False, default=None)
    dtype: str | torch.dtype | None = field(init=False, default=None)
    def __post_init__(self) -> None: ...
    def to_serializable(self) -> dict[str, Any]: ...
    def verify_with_parallel_config(self, parallel_config: ParallelConfig) -> None: ...
    def verify_with_model_config(self, model_config: ModelConfig) -> None: ...
    def open_stream(self, tensorizer_args: TensorizerArgs | None = None): ...
    def keys(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, item: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key) -> None: ...

@dataclass
class TensorizerArgs:
    tensorizer_uri: str | None = ...
    tensorizer_dir: str | None = ...
    encryption_keyfile: str | None = ...
    file_obj = ...
    s3_access_key_id = ...
    s3_secret_access_key = ...
    s3_endpoint = ...
    stream_kwargs = ...
    deserialization_kwargs = ...
    def __init__(self, tensorizer_config: TensorizerConfig) -> None: ...
    @staticmethod
    def add_cli_args(parser: FlexibleArgumentParser) -> FlexibleArgumentParser: ...
    @classmethod
    def from_cli_args(cls, args: argparse.Namespace) -> TensorizerArgs: ...
