from _typeshed import Incomplete
from fastapi import FastAPI as FastAPI, Request as Request
from vllm.engine.protocol import EngineClient as EngineClient
from vllm.logger import init_logger as init_logger

logger: Incomplete

def engine_client(request: Request) -> EngineClient: ...

router: Incomplete

async def sleep(raw_request: Request): ...
async def wake_up(raw_request: Request): ...
async def is_sleeping(raw_request: Request): ...
def attach_router(app: FastAPI): ...
