from _typeshed import Incomplete
from asyncio import AbstractEventLoop, Task
from collections.abc import AsyncGenerator, Awaitable, Callable as Callable
from concurrent.futures import Executor
from transformers.tokenization_utils_base import BatchEncoding
from typing import TypeVar
from typing_extensions import ParamSpec

P = ParamSpec("P")
T = TypeVar("T")

class AsyncMicrobatchTokenizer:
    tokenizer: Incomplete
    max_batch_size: Incomplete
    batch_wait_timeout_s: Incomplete
    def __init__(
        self, tokenizer, max_batch_size: int = 32, batch_wait_timeout_s: float = 0.002
    ) -> None: ...
    async def __call__(self, prompt, **kwargs) -> BatchEncoding: ...
    async def encode(self, prompt, **kwargs) -> list[int]: ...
    async def decode(self, token_ids, **kwargs) -> str: ...
    def __del__(self) -> None: ...

def cancel_task_threadsafe(task: Task): ...
def make_async(
    func: Callable[P, T], executor: Executor | None = None
) -> Callable[P, Awaitable[T]]: ...
def run_in_loop(loop: AbstractEventLoop, function: Callable, *args): ...
def in_loop(event_loop: AbstractEventLoop) -> bool: ...
def anext(it: AsyncGenerator[T, None]): ...
async def merge_async_iterators(
    *iterators: AsyncGenerator[T, None],
) -> AsyncGenerator[tuple[int, T], None]: ...
async def collect_from_async_generator(
    iterator: AsyncGenerator[T, None],
) -> list[T]: ...
