import cachetools
from _typeshed import Incomplete
from collections import UserDict
from collections.abc import Callable as Callable, Iterator, KeysView, Mapping
from typing import NamedTuple, overload

class _Sentinel: ...

ALL_PINNED_SENTINEL: Incomplete

class _MappingOrderCacheView(UserDict[_K, _V]):
    ordered_keys: Incomplete
    def __init__(
        self, data: Mapping[_K, _V], ordered_keys: Mapping[_K, None]
    ) -> None: ...
    def __iter__(self) -> Iterator[_K]: ...
    def keys(self) -> KeysView[_K]: ...

class CacheInfo(NamedTuple):
    hits: int
    total: int
    @property
    def hit_ratio(self) -> float: ...
    def __sub__(self, other: CacheInfo): ...

class LRUCache(cachetools.LRUCache[_K, _V]):
    pinned_items: Incomplete
    def __init__(
        self, capacity: float, getsizeof: Callable[[_V], float] | None = None
    ) -> None: ...
    def __getitem__(self, key: _K, *, update_info: bool = True) -> _V: ...
    def __delitem__(self, key: _K) -> None: ...
    @property
    def cache(self) -> Mapping[_K, _V]: ...
    @property
    def order(self) -> Mapping[_K, None]: ...
    @property
    def capacity(self) -> float: ...
    @property
    def usage(self) -> float: ...
    def stat(self, *, delta: bool = False) -> CacheInfo: ...
    def touch(self, key: _K) -> None: ...
    @overload
    def get(self, key: _K, /) -> _V | None: ...
    @overload
    def get(self, key: _K, /, default: _V | _T) -> _V | _T: ...
    @overload
    def pop(self, key: _K) -> _V: ...
    @overload
    def pop(self, key: _K, default: _V | _T) -> _V | _T: ...
    def put(self, key: _K, value: _V) -> None: ...
    def pin(self, key: _K) -> None: ...
    def remove_oldest(self, *, remove_pinned: bool = False) -> None: ...
    def popitem(self, remove_pinned: bool = False): ...
    def clear(self) -> None: ...
