from collections.abc import Callable as Callable, Generator, Iterable, Mapping, Sequence
from typing import Generic, Literal, TypeVar
from typing_extensions import TypeIs, overload

T = TypeVar("T")

class LazyDict(Mapping[str, _V], Generic[_V]):
    def __init__(self, factory: dict[str, Callable[[], _V]]) -> None: ...
    def __getitem__(self, key: str) -> _V: ...
    def __setitem__(self, key: str, value: Callable[[], _V]): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

def as_list(maybe_list: Iterable[T]) -> list[T]: ...
def is_list_of(
    value: object,
    typ: type[T] | tuple[type[T], ...],
    *,
    check: Literal["first", "all"] = "first",
) -> TypeIs[list[T]]: ...
@overload
def common_prefix(items: Sequence[str]) -> str: ...
@overload
def common_prefix(items: Sequence[Sequence[T]]) -> Sequence[T]: ...
def chunk_list(lst: list[T], chunk_size: int) -> Generator[list[T]]: ...
def flatten_2d_lists(lists: Iterable[Iterable[T]]) -> list[T]: ...
def full_groupby(values: Iterable[_V], *, key: Callable[[_V], _K]): ...
def swap_dict_values(obj: dict[_K, _V], key1: _K, key2: _K) -> None: ...
