from _typeshed import Incomplete

class Counter:
    counter: Incomplete
    def __init__(self, start: int = 0) -> None: ...
    def __next__(self) -> int: ...
    def reset(self) -> None: ...

class AtomicCounter:
    def __init__(self, initial: int = 0) -> None: ...
    @property
    def value(self) -> int: ...
    def inc(self, num: int = 1) -> int: ...
    def dec(self, num: int = 1) -> int: ...
