from _hashlib import HASH
from collections.abc import Callable as Callable
from typing import Any

def sha256(input: Any) -> bytes: ...
def sha256_cbor(input: Any) -> bytes: ...
def xxhash(input: Any) -> bytes: ...
def xxhash_cbor(input: Any) -> bytes: ...
def get_hash_fn_by_name(hash_fn_name: str) -> Callable[[Any], bytes]: ...
def safe_hash(data: bytes, usedforsecurity: bool = True) -> HASH: ...
