import os
from _typeshed import Incomplete
from functools import cache
from types import ModuleType
from typing import Any
from typing_extensions import Never
from vllm.logger import init_logger as init_logger

logger: Incomplete

def import_pynvml(): ...
@cache
def import_triton_kernels() -> None: ...
def import_from_path(module_name: str, file_path: str | os.PathLike): ...
def resolve_obj_by_qualname(qualname: str) -> Any: ...
@cache
def get_vllm_optional_dependencies(): ...

class _PlaceholderBase:
    def __getattr__(self, key: str) -> Never: ...
    def __lt__(self, other: object): ...
    def __le__(self, other: object): ...
    def __eq__(self, other: object): ...
    def __ne__(self, other: object): ...
    def __gt__(self, other: object): ...
    def __ge__(self, other: object): ...
    def __hash__(self): ...
    def __bool__(self) -> bool: ...
    def __call__(self, *args: object, **kwargs: object): ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: object): ...
    def __setitem__(self, key: object, value: object): ...
    def __delitem__(self, key: object): ...
    def __add__(self, other: object): ...
    def __sub__(self, other: object): ...
    def __mul__(self, other: object): ...
    def __matmul__(self, other: object): ...
    def __truediv__(self, other: object): ...
    def __floordiv__(self, other: object): ...
    def __mod__(self, other: object): ...
    def __divmod__(self, other: object): ...
    def __pow__(self, other: object, modulo: object = ...): ...
    def __lshift__(self, other: object): ...
    def __rshift__(self, other: object): ...
    def __and__(self, other: object): ...
    def __xor__(self, other: object): ...
    def __or__(self, other: object): ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __abs__(self): ...
    def __invert__(self): ...
    def __index__(self) -> int: ...
    def __round__(self, ndigits: object = ...): ...
    def __trunc__(self) -> int: ...
    def __floor__(self) -> int: ...
    def __ceil__(self) -> int: ...
    def __enter__(self): ...
    def __exit__(self, *args: object, **kwargs: object): ...

class PlaceholderModule(_PlaceholderBase):
    def __init__(self, name: str) -> None: ...
    def placeholder_attr(self, attr_path: str): ...
    def __getattr__(self, key: str) -> Never: ...

class _PlaceholderModuleAttr(_PlaceholderBase):
    def __init__(self, module: PlaceholderModule, attr_path: str) -> None: ...
    def placeholder_attr(self, attr_path: str): ...
    def __getattr__(self, key: str) -> Never: ...

class LazyLoader(ModuleType):
    def __init__(
        self, local_name: str, parent_module_globals: dict[str, Any], name: str
    ) -> None: ...
    def __getattr__(self, item: Any) -> Any: ...
    def __dir__(self) -> list[str]: ...

def has_deep_ep() -> bool: ...
def has_deep_gemm() -> bool: ...
def has_triton_kernels() -> bool: ...
def has_tilelang() -> bool: ...
def has_arctic_inference() -> bool: ...
def has_helion() -> bool: ...
def has_aiter() -> bool: ...
def has_mori() -> bool: ...
