RCP_LN2: float

def cdiv(a: int, b: int) -> int: ...
def next_power_of_2(n: int) -> int: ...
def prev_power_of_2(n: int) -> int: ...
def round_up(x: int, y: int) -> int: ...
def round_down(x: int, y: int) -> int: ...
def largest_power_of_2_divisor(n: int) -> int: ...
