import contextlib
import torch.types
import types
from .mem_constants import GiB_bytes as GiB_bytes, MiB_bytes as MiB_bytes
from _typeshed import Incomplete
from collections.abc import Generator
from dataclasses import dataclass, field
from functools import cache
from vllm.platforms import current_platform as current_platform

def format_mib(b: int) -> str: ...
def format_gib(b: int) -> str: ...
@cache
def get_max_shared_memory_bytes(gpu: int = 0) -> int: ...
def get_cpu_memory() -> int: ...

class DeviceMemoryProfiler:
    device: Incomplete
    def __init__(self, device: torch.types.Device | None = None) -> None: ...
    def current_memory_usage(self) -> float: ...
    initial_memory: Incomplete
    def __enter__(self): ...
    final_memory: Incomplete
    consumed_memory: Incomplete
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...

@dataclass
class MemorySnapshot:
    torch_peak: int = ...
    free_memory: int = ...
    total_memory: int = ...
    cuda_memory: int = ...
    torch_memory: int = ...
    non_torch_memory: int = ...
    timestamp: float = ...
    device: torch.types.Device = ...
    auto_measure: bool = ...
    device_ = ...
    def __post_init__(self) -> None: ...
    def measure(self) -> None: ...
    def __sub__(self, other: MemorySnapshot) -> MemorySnapshot: ...

@dataclass
class MemoryProfilingResult:
    non_kv_cache_memory: int = ...
    torch_peak_increase: int = ...
    non_torch_increase: int = ...
    weights_memory: int = ...
    before_create: MemorySnapshot = field(default_factory=MemorySnapshot)
    profile_time: float = ...
    before_profile = ...
    after_profile = ...
    def __post_init__(self) -> None: ...

@contextlib.contextmanager
def memory_profiling(
    baseline_snapshot: MemorySnapshot, weights_memory: int = 0
) -> Generator[MemoryProfilingResult, None, None]: ...
