import contextlib
import psutil
import zmq
import zmq.asyncio
from _typeshed import Incomplete
from collections.abc import Iterator, Sequence
from typing import Any
from vllm.logger import init_logger as init_logger

logger: Incomplete

def close_sockets(sockets: Sequence[zmq.Socket | zmq.asyncio.Socket]): ...
def get_ip() -> str: ...
def test_loopback_bind(address: str, family: int) -> bool: ...
def get_loopback_ip() -> str: ...
def is_valid_ipv6_address(address: str) -> bool: ...
def split_host_port(host_port: str) -> tuple[str, int]: ...
def join_host_port(host: str, port: int) -> str: ...
def get_distributed_init_method(ip: str, port: int) -> str: ...
def get_tcp_uri(ip: str, port: int) -> str: ...
def get_open_zmq_ipc_path() -> str: ...
def get_open_zmq_inproc_path() -> str: ...
def get_open_port() -> int: ...
def get_open_ports_list(count: int = 5) -> list[int]: ...
def find_process_using_port(port: int) -> psutil.Process | None: ...
def split_zmq_path(path: str) -> tuple[str, str, str]: ...
def make_zmq_path(scheme: str, host: str, port: int | None = None) -> str: ...
def make_zmq_socket(
    ctx: zmq.asyncio.Context | zmq.Context,
    path: str,
    socket_type: Any,
    bind: bool | None = None,
    identity: bytes | None = None,
    linger: int | None = None,
) -> zmq.Socket | zmq.asyncio.Socket: ...
@contextlib.contextmanager
def zmq_socket_ctx(
    path: str,
    socket_type: Any,
    bind: bool | None = None,
    linger: int = 0,
    identity: bytes | None = None,
) -> Iterator[zmq.Socket]: ...
