from _typeshed import Incomplete
from collections.abc import Generator
from contextlib import contextmanager

def print_tensor(tensor_obj, prefix, tensor_list=None): ...
def process_layer_params(module_obj): ...
def construct_marker_dict_and_push(
    module_name, module_obj, in_tensor, kwargs=None, out_tensor=None
) -> None: ...

class ResultHolder:
    result: Incomplete

@contextmanager
def layerwise_nvtx_marker_context(
    module_name, module_obj, in_tensor=None, kwargs=None
) -> Generator[Incomplete]: ...

class PytHooks:
    module_to_name_map: Incomplete
    def __init__(self) -> None: ...
    def module_fwd_hook(self, module_obj, in_tensor, out_tensor) -> None: ...
    def module_fwd_pre_hook(self, module_obj, in_tensor, kwargs) -> None: ...
    def register_hooks(self, network_model, module_prefix: str = "top") -> None: ...
