from collections.abc import Sequence
from functools import cache
from typing import Any

def cuda_is_initialized() -> bool: ...
def xpu_is_initialized() -> bool: ...
def cuda_get_device_properties(
    device, names: Sequence[str], init_cuda: bool = False
) -> tuple[Any, ...]: ...
@cache
def is_pin_memory_available() -> bool: ...
@cache
def is_uva_available() -> bool: ...
@cache
def num_compute_units(device_id: int = 0) -> int: ...
