from typing import Any

class ExtensionManager:
    name2class: dict[str, type]
    def __init__(self) -> None: ...
    def register(self, name: str): ...
    def load(self, cls_name: str, *args, **kwargs) -> Any: ...
