import contextlib
from .platform_utils import (
    cuda_is_initialized as cuda_is_initialized,
    xpu_is_initialized as xpu_is_initialized,
)
from _typeshed import Incomplete
from collections.abc import Callable as Callable, Generator, Iterator
from pathlib import Path
from vllm.logger import init_logger as init_logger
from vllm.platforms import current_platform as current_platform
from vllm.platforms.interface import in_wsl as in_wsl
from vllm.ray.lazy_utils import is_in_ray_actor as is_in_ray_actor

logger: Incomplete
CYAN: str
RESET: str

def update_environment_variables(envs_dict: dict[str, str]): ...
@contextlib.contextmanager
def set_env_var(key: str, value: str) -> Iterator[None]: ...
@contextlib.contextmanager
def suppress_stdout() -> Generator[None]: ...
def unique_filepath(fn: Callable[[int], Path]) -> Path: ...
def get_mp_context(): ...
def set_process_title(name: str, suffix: str = "", prefix: str = ...) -> None: ...
def decorate_logs(process_name: str | None = None) -> None: ...
def kill_process_tree(pid: int): ...
def set_ulimit(target_soft_limit: int = 65535): ...
def find_loaded_library(lib_name: str) -> str | None: ...
